/- Correctness of the bit-blaster's ripple-carry arithmetic family
   (issue #68, v0.15.0): `ripple_carry`, `blast_add`, `blast_sub`, `blast_ult`.

   This file is HAND-WRITTEN (BlastKernel.lean is generated by regen-blaster.sh
   and must not be edited). It builds on the pure-model infrastructure of
   BlasterProof.lean (`pSim` / `pEvalLit`, append-monotonicity, `AigWF`,
   the gadget-spec idiom and `simulate_spec`).

   Proof architecture:
   * `pCarry` is a PURE Boolean restatement of the ripple-carry chain:
     `c_0 = cin`, `c_{i+1} = atLeastTwo a_i b_i c_i` (the majority function).
     The gate structure emits `(a_i ∧ b_i) ∨ ((a_i ⊕ b_i) ∧ c_i)`, which equals
     the majority function (`or_and_xor_eq_atLeastTwo`, an 8-case `Bool` check).
   * `ripple_body_gadget` is the FULL-ADDER gadget spec: one loop iteration
     appends exactly 9 gates (two XOR gadgets à 3, two AND, one OR), preserves
     `AigWF` and — by append-monotonicity — every pre-existing literal value,
     and returns a sum literal valued `a_i ⊕ (b_i ⊕ c_i)` and a carry literal
     valued `atLeastTwo a_i b_i c_i` (values w.r.t. the PRE-state aig).
   * `RippleInv` is the loop invariant: after `i` bits, the original AIG is a
     prefix, the carry literal evaluates to `pCarry … i` and sum literal `j`
     evaluates to `a_j ⊕ (b_j ⊕ pCarry … j)` — the classic adder invariant in
     Boolean (carry-chain) form rather than numeric form. The NUMERIC content
     (the carry chain computes the carries of `A.toNat + B.toNat + cin`) is not
     re-proved here: core Lean's `BitVec.carry` is defined numerically and
     `BitVec.carry_succ` / `BitVec.getLsbD_add_add_bool` /
     `BitVec.ult_eq_not_carry` provide the (already machine-checked)
     numeric ↔ bitwise bridge, which `pCarry_eq_carry` taps into.
   * The headline theorems compose the loop spec with `simulate_spec` and lift
     to `BitVec w` for ALL widths `w`:
     - `blast_add_bitvec`  : output word denotes `A + B`
     - `blast_sub_bitvec`  : output word denotes `A - B`   (two's complement:
                             `A - B = A + ~~~B + 1`)
     - `blast_ult_bitvec`  : output literal = `decide (A < B)` (borrow:
                             carry-out of `A + ~~~B + 1` is `!(A <ᵤ B)`)
   * `lit_false` / `lit_true` refer to node 0, so the `blast_add`/`blast_sub`/
     `blast_ult` theorems assume node 0 is the constant-false node (which
     `aig_new` guarantees); `pEvalLit_node_zero` turns that into values.
-/
import BlasterProof

open Aeneas Aeneas.Std Result

set_option maxHeartbeats 1000000

namespace blast_kernel.spec

/- ══════════════════════ THE PURE CARRY CHAIN ══════════════════════ -/

/-- Default literal for out-of-range reads (every use below is guarded). -/
def dLit : Lit := { node := 0#usize, neg := false }

/-- The pure ripple-carry chain: the value of the carry after `i` full-adder
    stages, reading the operand bits through `pEvalLit` under `vals`. -/
def pCarry (vals : List Bool) (a b : List Lit) (c0 : Bool) : Nat → Bool
  | 0 => c0
  | i + 1 =>
    Bool.atLeastTwo (pEvalLit vals (a.getD i dLit)) (pEvalLit vals (b.getD i dLit))
      (pCarry vals a b c0 i)

/-- The gate structure `(x ∧ y) ∨ ((x ⊕ y) ∧ c)` computes the majority
    (at-least-two) function — the carry of a full adder. 8-case Bool check. -/
theorem or_and_xor_eq_atLeastTwo (x y c : Bool) :
    ((x && y) || ((x ^^ y) && c)) = Bool.atLeastTwo x y c := by
  cases x <;> cases y <;> cases c <;> rfl

/-- Append-monotonicity for the carry chain: appending nodes to the AIG does
    not change the carry chain of words whose literals refer to existing
    nodes. -/
theorem pCarry_stable {ns ns' : List Node} (hpre : ns <+: ns') {a b : List Lit}
    (ha : ∀ l ∈ a, l.node.val < ns.length)
    (hb : ∀ l ∈ b, l.node.val < ns.length)
    (c0 : Bool) (inp : List Bool) (i : Nat)
    (hia : i ≤ a.length) (hib : i ≤ b.length) :
    pCarry (pSim inp ns') a b c0 i = pCarry (pSim inp ns) a b c0 i := by
  induction i with
  | zero => rfl
  | succ i ih =>
    have hia' : i < a.length := by omega
    have hib' : i < b.length := by omega
    simp only [pCarry, getD_eq_getElem_of_lt hia', getD_eq_getElem_of_lt hib',
      ih (by omega) (by omega),
      pEvalLit_stable hpre _ (ha _ (List.getElem_mem hia')) inp,
      pEvalLit_stable hpre _ (hb _ (List.getElem_mem hib')) inp]

/-- The pure carry chain coincides with core Lean's numerically-defined
    `BitVec.carry` on denoting words (via `BitVec.carry_succ`). -/
theorem pCarry_eq_carry {vals : List Bool} {a b : List Lit} {w : Nat}
    {A B : BitVec w} (hA : Denotes vals a w A) (hB : Denotes vals b w B)
    (c0 : Bool) (i : Nat) (hi : i ≤ w) :
    pCarry vals a b c0 i = BitVec.carry i A B c0 := by
  obtain ⟨hal, hAj⟩ := hA
  obtain ⟨hbl, hBj⟩ := hB
  induction i with
  | zero => simp [pCarry]
  | succ i ih =>
    have hia : i < a.length := by omega
    have hib : i < b.length := by omega
    rw [BitVec.carry_succ]
    simp only [pCarry, getD_eq_getElem_of_lt hia, getD_eq_getElem_of_lt hib,
      ih (by omega), hAj i hia, hBj i hib]

/- ══════════════ LEAF SPECS AND CONSTANT LITERALS ══════════════ -/

theorem lit_false_spec :
    lit_false ⦃ l => l = { node := 0#usize, neg := false } ⦄ := by
  unfold lit_false
  simp

theorem lit_true_spec :
    lit_true ⦃ l => l = { node := 0#usize, neg := true } ⦄ := by
  unfold lit_true
  simp

/-- A literal referring to node 0 evaluates to its negation flag whenever
    node 0 is the constant-FALSE node (as `aig_new` guarantees). -/
theorem pEvalLit_node_zero {ns : List Node} (hne : 0 < ns.length)
    (h0 : ns[0]'hne = Node.False) (inp : List Bool) (b : Bool) :
    pEvalLit (pSim inp ns) { node := 0#usize, neg := b } = b := by
  have htake : ns.take 1 = [Node.False] := by
    cases ns with
    | nil => simp at hne
    | cons hd tl =>
      simp only [List.getElem_cons_zero] at h0
      simp [h0]
  have hpre : pSim inp (ns.take 1) <+: pSim inp ns :=
    pSim_prefix_of_prefix inp (List.take_prefix 1 ns)
  have hval : pSim inp (ns.take 1) = [false] := by
    rw [htake]
    simp [pSim, pSimAux, pNodeVal]
  have hget : (pSim inp ns).getD 0 false = false := by
    rw [getD_of_prefix hpre (by rw [hval]; simp), hval]
    rfl
  rw [List.getD_eq_getElem?_getD] at hget
  cases b <;> simp [pEvalLit, hget]

/- ══════════════════ THE FULL-ADDER GADGET ══════════════════ -/

/-- **Full-adder gadget spec** (one iteration of the `ripple_carry` loop body,
    in the running case `i < w`): appends exactly 9 gates (two XOR gadgets à
    three, two AND, one OR), preserves well-formedness — and, by
    append-monotonicity, the value of every pre-existing literal — pushes one
    sum literal valued `a_i ⊕ (b_i ⊕ c)` and returns a carry literal valued
    `atLeastTwo a_i b_i c` (majority), all w.r.t. the PRE-state aig. -/
theorem ripple_body_gadget (a b : Slice Lit) (w : Std.Usize) (aig1 : Aig)
    (carry : Lit) (sum : alloc.vec.Vec Lit) (i : Std.Usize)
    (hi : i.val < w.val)
    (hia : i.val < a.val.length) (hib : i.val < b.val.length)
    (hcap : aig1.nodes.val.length + 9 ≤ Usize.max)
    (hsumcap : sum.val.length < Usize.max)
    (hx : (a.val[i.val]'hia).node.val < aig1.nodes.val.length)
    (hy : (b.val[i.val]'hib).node.val < aig1.nodes.val.length)
    (hc : carry.node.val < aig1.nodes.val.length) :
    ripple_carry_loop.body a b w aig1 carry sum i ⦃ r =>
      ∃ aig2 carry2 sum2 i2 s,
        r = ControlFlow.cont (aig2, carry2, sum2, i2) ∧
        i2.val = i.val + 1 ∧
        aig2.nodes.val.length = aig1.nodes.val.length + 9 ∧
        aig1.nodes.val <+: aig2.nodes.val ∧
        (∀ L, AigWF aig1.nodes.val L → AigWF aig2.nodes.val L) ∧
        sum2.val = sum.val ++ [s] ∧
        s.node.val < aig2.nodes.val.length ∧
        carry2.node.val < aig2.nodes.val.length ∧
        ∀ inp : List Bool,
          pEvalLit (pSim inp aig2.nodes.val) s
            = (pEvalLit (pSim inp aig1.nodes.val) (a.val[i.val]'hia)
               ^^ (pEvalLit (pSim inp aig1.nodes.val) (b.val[i.val]'hib)
                   ^^ pEvalLit (pSim inp aig1.nodes.val) carry)) ∧
          pEvalLit (pSim inp aig2.nodes.val) carry2
            = Bool.atLeastTwo
                (pEvalLit (pSim inp aig1.nodes.val) (a.val[i.val]'hia))
                (pEvalLit (pSim inp aig1.nodes.val) (b.val[i.val]'hib))
                (pEvalLit (pSim inp aig1.nodes.val) carry) ⦄ := by
  unfold ripple_carry_loop.body
  split
  · step as ⟨la, hla⟩
    step as ⟨lb, hlb⟩
    have hx' : la.node.val < aig1.nodes.val.length := by rw [hla]; exact hx
    have hy' : lb.node.val < aig1.nodes.val.length := by rw [hlb]; exact hy
    step with (push_xor_gadget aig1 la lb (by omega) hx' hy') as
      ⟨p, aigA, hp1, hp2, hp3, hp4, hp5⟩
    have hcA : carry.node.val < aigA.nodes.val.length := by omega
    step with (push_xor_gadget aigA p carry (by omega) hp3 hcA) as
      ⟨s, aigB, hs1, hs2, hs3, hs4, hs5⟩
    step as ⟨sum2, hsum2⟩
    have hlaB : la.node.val < aigB.nodes.val.length := by omega
    have hlbB : lb.node.val < aigB.nodes.val.length := by omega
    step with (push_and_gadget aigB la lb (by omega) hlaB hlbB) as
      ⟨g, aigC, hg1, hg2, hg3, hg4, hg5⟩
    have hpC : p.node.val < aigC.nodes.val.length := by omega
    have hcC : carry.node.val < aigC.nodes.val.length := by omega
    step with (push_and_gadget aigC p carry (by omega) hpC hcC) as
      ⟨t, aigD, ht1, ht2, ht3, ht4, ht5⟩
    have hgD : g.node.val < aigD.nodes.val.length := by omega
    step with (push_or_gadget aigD g t (by omega) hgD ht3) as
      ⟨c2, aigE, hE1, hE2, hE3, hE4, hE5⟩
    step as ⟨i1, hi1⟩
    simp only [← hla, ← hlb]
    refine ⟨aigE, c2, sum2, i1, s, rfl, by scalar_tac, by omega,
      hp2.trans (hs2.trans (hg2.trans (ht2.trans hE2))),
      fun L hL => hE4 L (ht4 L (hg4 L (hs4 L (hp4 L hL)))),
      hsum2, by omega, hE3, ?_⟩
    intro inp
    constructor
    · -- sum bit: s = a_i ⊕ (b_i ⊕ c)
      rw [pEvalLit_stable (hg2.trans (ht2.trans hE2)) s hs3 inp, hs5 inp,
        hp5 inp, pEvalLit_stable hp2 carry hc inp]
      exact Bool.xor_assoc _ _ _
    · -- carry out: c2 = atLeastTwo a_i b_i c
      rw [hE5 inp, pEvalLit_stable ht2 g hg3 inp, hg5 inp, ht5 inp,
        pEvalLit_stable (hs2.trans hg2) p hp3 inp, hp5 inp,
        pEvalLit_stable (hp2.trans hs2) la hx' inp,
        pEvalLit_stable (hp2.trans hs2) lb hy' inp,
        pEvalLit_stable (hp2.trans (hs2.trans hg2)) carry hc inp]
      exact or_and_xor_eq_atLeastTwo _ _ _
  · exfalso
    scalar_tac

/- ══════════════════ THE RIPPLE-CARRY LOOP INVARIANT ══════════════════ -/

/-- Loop invariant of `ripple_carry` after `i` processed bits: 9 gates per bit
    were appended, the original AIG is a prefix (nothing existing was
    touched), well-formedness is preserved, the carry literal evaluates —
    under the CURRENT aig — to the pure carry chain `pCarry … i`, and sum
    literal `j` evaluates to `a_j ⊕ (b_j ⊕ pCarry … j)`, all operand values
    taken under the ORIGINAL aig. -/
def RippleInv (aig : Aig) (a b : Slice Lit) (cin : Lit)
    (aig1 : Aig) (carry1 : Lit) (sum1 : alloc.vec.Vec Lit) (i : Nat) : Prop :=
  i ≤ a.val.length ∧
  aig1.nodes.val.length = aig.nodes.val.length + 9 * i ∧
  aig.nodes.val <+: aig1.nodes.val ∧
  (∀ L, AigWF aig.nodes.val L → AigWF aig1.nodes.val L) ∧
  sum1.val.length = i ∧
  (∀ l ∈ sum1.val, l.node.val < aig1.nodes.val.length) ∧
  carry1.node.val < aig1.nodes.val.length ∧
  (∀ inp : List Bool,
    pEvalLit (pSim inp aig1.nodes.val) carry1
      = pCarry (pSim inp aig.nodes.val) a.val b.val
          (pEvalLit (pSim inp aig.nodes.val) cin) i) ∧
  ∀ (inp : List Bool) (j : Nat) (hj1 : j < sum1.val.length)
    (hj2 : j < a.val.length) (hj3 : j < b.val.length),
    pEvalLit (pSim inp aig1.nodes.val) sum1.val[j]
      = (pEvalLit (pSim inp aig.nodes.val) a.val[j]
         ^^ (pEvalLit (pSim inp aig.nodes.val) b.val[j]
             ^^ pCarry (pSim inp aig.nodes.val) a.val b.val
                  (pEvalLit (pSim inp aig.nodes.val) cin) j))

theorem RippleInv.init (aig : Aig) (a b : Slice Lit) (cin : Lit)
    (hcin : cin.node.val < aig.nodes.val.length) :
    RippleInv aig a b cin aig cin (alloc.vec.Vec.new Lit) 0 := by
  refine ⟨Nat.zero_le _, by simp, List.prefix_refl _, fun _ h => h, by simp,
    by simp, hcin, fun _ => rfl, ?_⟩
  intro _ j hj1 _ _
  simp at hj1

/-- Preservation: one full-adder gadget for bit `i` re-establishes the
    invariant at `i + 1`. -/
theorem RippleInv.step {aig : Aig} {a b : Slice Lit} {cin : Lit}
    {aig1 aig2 : Aig} {carry1 carry2 : Lit} {sum1 sum2 : alloc.vec.Vec Lit}
    {s : Lit} {i : Nat}
    (h : RippleInv aig a b cin aig1 carry1 sum1 i)
    (hia : i < a.val.length) (hib : i < b.val.length)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hglen : aig2.nodes.val.length = aig1.nodes.val.length + 9)
    (hgpre : aig1.nodes.val <+: aig2.nodes.val)
    (hgwf : ∀ L, AigWF aig1.nodes.val L → AigWF aig2.nodes.val L)
    (hsum2 : sum2.val = sum1.val ++ [s])
    (hs : s.node.val < aig2.nodes.val.length)
    (hc2 : carry2.node.val < aig2.nodes.val.length)
    (hsem : ∀ inp : List Bool,
      pEvalLit (pSim inp aig2.nodes.val) s
        = (pEvalLit (pSim inp aig1.nodes.val) (a.val[i]'hia)
           ^^ (pEvalLit (pSim inp aig1.nodes.val) (b.val[i]'hib)
               ^^ pEvalLit (pSim inp aig1.nodes.val) carry1)) ∧
      pEvalLit (pSim inp aig2.nodes.val) carry2
        = Bool.atLeastTwo
            (pEvalLit (pSim inp aig1.nodes.val) (a.val[i]'hia))
            (pEvalLit (pSim inp aig1.nodes.val) (b.val[i]'hib))
            (pEvalLit (pSim inp aig1.nodes.val) carry1)) :
    RippleInv aig a b cin aig2 carry2 sum2 (i + 1) := by
  obtain ⟨hile, hlen1, hpre1, hwf1, hslen, hsrng, hcrng, hcsem, hssem⟩ := h
  refine ⟨by omega, by omega, hpre1.trans hgpre,
    fun L hL => hgwf L (hwf1 L hL), by rw [hsum2]; simp [hslen], ?_, hc2,
    ?_, ?_⟩
  · intro l hl
    rw [hsum2] at hl
    rcases List.mem_append.mp hl with h' | h'
    · exact Nat.lt_of_lt_of_le (hsrng l h') hgpre.length_le
    · simp only [List.mem_singleton] at h'
      subst h'
      exact hs
  · -- carry chain advances by one majority stage
    intro inp
    rw [(hsem inp).2,
      pEvalLit_stable hpre1 _ (ha _ (List.getElem_mem hia)) inp,
      pEvalLit_stable hpre1 _ (hb _ (List.getElem_mem hib)) inp,
      hcsem inp]
    simp only [pCarry, getD_eq_getElem_of_lt hia, getD_eq_getElem_of_lt hib]
  · -- sum bits: old ones are stable, the fresh one is the full-adder sum
    intro inp j hj1 hj2 hj3
    have hj1' : j < sum1.val.length + 1 := by
      rw [hsum2] at hj1
      simpa using hj1
    rcases Nat.lt_or_ge j sum1.val.length with hji | hji
    · have hgetj : sum2.val[j]'hj1 = sum1.val[j]'hji := by
        simp only [hsum2]
        exact List.getElem_append_left hji
      rw [hgetj, pEvalLit_stable hgpre _ (hsrng _ (List.getElem_mem _)) inp]
      exact hssem inp j hji hj2 hj3
    · have hjeq : j = i := by omega
      subst hjeq
      have hgetj : sum2.val[j]'hj1 = s := by
        simp only [hsum2]
        exact List.getElem_concat_length (by omega) _
      rw [hgetj, (hsem inp).1,
        pEvalLit_stable hpre1 _ (ha _ (List.getElem_mem hia)) inp,
        pEvalLit_stable hpre1 _ (hb _ (List.getElem_mem hib)) inp,
        hcsem inp]

/- ══════════════════ THE RIPPLE-CARRY LOOP SPEC ══════════════════ -/

theorem ripple_carry_loop_spec (aig : Aig) (a b : Slice Lit) (cin : Lit)
    (w : Std.Usize) (hw : w.val = a.val.length)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + 9 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hcin : cin.node.val < aig.nodes.val.length) :
    ripple_carry_loop aig a b cin (alloc.vec.Vec.new Lit) w 0#usize ⦃ q =>
      RippleInv aig a b cin q.1 q.2.1 q.2.2 a.val.length ⦄ := by
  unfold ripple_carry_loop
  apply loop.spec_decr_nat
    (measure := fun (s : Aig × Lit × alloc.vec.Vec Lit × Std.Usize) =>
      a.val.length - s.2.2.2.val)
    (inv := fun (s : Aig × Lit × alloc.vec.Vec Lit × Std.Usize) =>
      RippleInv aig a b cin s.1 s.2.1 s.2.2.1 s.2.2.2.val)
  · rintro ⟨aig1, carry1, sum1, i⟩ hinv
    dsimp only at hinv ⊢
    obtain ⟨hile, hlen1, hpre1, hwf1, hslen, hsrng, hcrng, hcsem, hssem⟩ := hinv
    by_cases hlt : i.val < w.val
    · have hia : i.val < a.val.length := by omega
      have hib : i.val < b.val.length := by omega
      have hcap1 : aig1.nodes.val.length + 9 ≤ Usize.max := by omega
      have hsumcap : sum1.val.length < Usize.max := by
        have := a.length_ineq
        omega
      have hx : (a.val[i.val]'hia).node.val < aig1.nodes.val.length := by
        have := ha _ (List.getElem_mem hia)
        omega
      have hy : (b.val[i.val]'hib).node.val < aig1.nodes.val.length := by
        have := hb _ (List.getElem_mem hib)
        omega
      apply WP.spec_mono (ripple_body_gadget a b w aig1 carry1 sum1 i hlt hia
        hib hcap1 hsumcap hx hy hcrng)
      rintro r ⟨aig2, carry2, sum2, i2, s, rfl, hi2, hg1, hg2, hg3, hg4, hg5,
        hg6, hg7⟩
      dsimp only
      refine ⟨?_, by omega⟩
      rw [hi2]
      exact RippleInv.step
        ⟨hile, hlen1, hpre1, hwf1, hslen, hsrng, hcrng, hcsem, hssem⟩
        hia hib ha hb hg1 hg2 hg3 hg4 hg5 hg6 hg7
    · unfold ripple_carry_loop.body
      split
      · exfalso
        scalar_tac
      · have hieq : i.val = a.val.length := by scalar_tac
        rw [← hieq]
        exact ⟨hile, hlen1, hpre1, hwf1, hslen, hsrng, hcrng, hcsem, hssem⟩
  · exact RippleInv.init aig a b cin hcin

/-- **Correctness of `ripple_carry`** against the pure model: appends
    `9 · |a|` gates, preserves everything existing, and — under any input
    assignment — the returned sum word carries the full-adder sum bits and
    the returned carry literal the final carry of the chain. -/
theorem ripple_carry_spec (aig : Aig) (a b : Slice Lit) (cin : Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + 9 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hcin : cin.node.val < aig.nodes.val.length) :
    ripple_carry aig a b cin ⦃ p =>
      p.1.1.val.length = a.val.length ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.2.nodes.val.length = aig.nodes.val.length + 9 * a.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ l ∈ p.1.1.val, l.node.val < p.2.nodes.val.length) ∧
      p.1.2.node.val < p.2.nodes.val.length ∧
      (∀ inp : List Bool,
        pEvalLit (pSim inp p.2.nodes.val) p.1.2
          = pCarry (pSim inp aig.nodes.val) a.val b.val
              (pEvalLit (pSim inp aig.nodes.val) cin) a.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj1 : j < p.1.1.val.length)
        (hj2 : j < a.val.length) (hj3 : j < b.val.length),
        pEvalLit (pSim inp p.2.nodes.val) p.1.1.val[j]
          = (pEvalLit (pSim inp aig.nodes.val) a.val[j]
             ^^ (pEvalLit (pSim inp aig.nodes.val) b.val[j]
                 ^^ pCarry (pSim inp aig.nodes.val) a.val b.val
                      (pEvalLit (pSim inp aig.nodes.val) cin) j)) ⦄ := by
  unfold ripple_carry
  step with (ripple_carry_loop_spec aig a b cin (Slice.len a) (by scalar_tac)
    hab hcap ha hb hcin) as ⟨aig1, carry, sum, hinv⟩
  obtain ⟨_, hlen, hpre, hwf, hslen, hsrng, hcrng, hcsem, hssem⟩ := hinv
  exact ⟨hslen, hpre, by omega, hwf, hsrng, hcrng, hcsem, hssem⟩

/- ══════════════════ `word_not` ══════════════════ -/

/-- `word_not` maps `lit_not` over the word: no gates, output literal `j` is
    literal `j` with the negation flag flipped. Total correctness. -/
theorem word_not_spec (a : Slice Lit) :
    word_not a ⦃ out =>
      out.val = a.val.map (fun l => { l with neg := !l.neg }) ⦄ := by
  unfold word_not word_not_loop
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      a.val.length - s.2.val)
    (inv := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      s.2.val ≤ a.val.length ∧
      s.1.val = (a.val.map (fun l => { l with neg := !l.neg })).take s.2.val)
  · rintro ⟨out1, i⟩ ⟨hle, hval⟩
    dsimp only at hle hval
    unfold word_not_loop.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < a.val.length := by scalar_tac
      have hmilt : i.val
          < (a.val.map (fun l => { l with neg := !l.neg })).length := by
        simp
        omega
      step as ⟨l, hl⟩
      step with (lit_not_spec l) as ⟨l1, hl1⟩
      have hocap : out1.val.length < Usize.max := by
        have h1 := a.length_ineq
        have h2 : out1.val.length ≤ i.val := by
          rw [hval]
          simp
        omega
      step as ⟨out2, hout2⟩
      step as ⟨i1, hi1⟩
      refine ⟨by scalar_tac, ?_, by scalar_tac⟩
      have htake : (a.val.map (fun l => { l with neg := !l.neg })).take
            (i.val + 1)
          = (a.val.map (fun l => { l with neg := !l.neg })).take i.val
            ++ [(a.val.map (fun l => { l with neg := !l.neg }))[i.val]'hmilt]
          := by
        rw [List.take_add_one, List.getElem?_eq_getElem hmilt]
        simp
      rw [hi1, hout2, hval, hl1, hl, htake]
      simp
    · rename_i hge
      have hieq : i.val = a.val.length := by scalar_tac
      have hfin : out1.val
          = a.val.map (fun l => { l with neg := !l.neg }) := by
        rw [hval, hieq]
        exact List.take_of_length_le (by simp)
      exact hfin
  · constructor
    · simp
    · simp

/- ══════════════ BITVEC BRIDGE LEMMAS (core `BitVec.carry`) ══════════════ -/

theorem setWidth_ofBool_true (w : Nat) :
    BitVec.setWidth w (BitVec.ofBool true) = 1#w := by
  apply BitVec.eq_of_toNat_eq
  simp

/-- Two's complement subtraction as add-with-carry-in-one:
    `A - B = A + ~~~B + 1`. -/
theorem sub_eq_add_not_add_bool {w : Nat} (A B : BitVec w) :
    A - B = A + ~~~B + BitVec.setWidth w (BitVec.ofBool true) := by
  rw [setWidth_ofBool_true, BitVec.sub_eq_add_neg, BitVec.neg_eq_not_add,
    ← BitVec.add_assoc]

/-- Bit `j` of `A - B` is the full-adder sum bit of `A`, `~~~B` with
    carry-in `true`. -/
theorem getLsbD_sub_carry {w : Nat} (A B : BitVec w) {j : Nat} (hj : j < w) :
    (A - B).getLsbD j
      = (A.getLsbD j ^^ ((~~~B).getLsbD j ^^ BitVec.carry j A (~~~B) true)) := by
  rw [sub_eq_add_not_add_bool, BitVec.getLsbD_add_add_bool hj]

/- ══════════════ END-TO-END: `blast_add` ══════════════ -/

/-- **Correctness of `blast_add` against the simulator** (issue #68), the
    per-bit monadic headline mirroring `blast_and_correct`: after blasting,
    simulating the extended aig on ANY well-formed input assignment gives, for
    each output bit `j`, exactly the full-adder sum bit
    `a_j ⊕ (b_j ⊕ pCarry … j)` — with the carry chain evaluated under the
    SAME simulation. Requires node 0 to be the constant-FALSE node (this is
    what `lit_false` points at). Unbounded: `a`/`b` have arbitrary length. -/
theorem blast_add_correct (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + 9 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False) :
    blast_add aig a b ⦃ p =>
      p.1.val.length = a.val.length ∧
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          ∀ (j : Nat) (hj1 : j < p.1.val.length) (hj2 : j < a.val.length)
            (hj3 : j < b.val.length),
            pEvalLit vals.val p.1.val[j]
              = (pEvalLit vals.val a.val[j]
                 ^^ (pEvalLit vals.val b.val[j]
                     ^^ pCarry vals.val a.val b.val false j)) ⦄ ⦄ := by
  unfold blast_add
  step with lit_false_spec as ⟨l, hl⟩
  simp only [hl]
  have hcin : ({ node := 0#usize, neg := false } : Lit).node.val
      < aig.nodes.val.length := by
    scalar_tac
  step with (ripple_carry_spec aig a b _ hab hcap ha hb hcin) as
    ⟨sum, carry, aig1, h1, h2, h3, h4, h5, h6, h7, h8⟩
  refine ⟨h1, fun inputs hwf => ?_⟩
  apply WP.spec_mono (simulate_spec aig1 inputs (h4 _ hwf))
  intro vals hv j hj1 hj2 hj3
  rw [hv, h8 inputs.val j hj1 hj2 hj3,
    pEvalLit_node_zero hne h0 inputs.val false,
    pEvalLit_stable h2 _ (ha _ (List.getElem_mem hj2)) inputs.val,
    pEvalLit_stable h2 _ (hb _ (List.getElem_mem hj3)) inputs.val,
    pCarry_stable h2 ha hb false inputs.val j (by omega) (by omega)]

/-- **`blast_add` implements `BitVec` addition, for every width `w`**: if the
    input words denote `A` and `B` under the post-blast simulation, the output
    word denotes `A + B`. -/
theorem blast_add_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + 9 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (A B : BitVec w) :
    blast_add aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          Denotes vals.val p.1.val w (A + B) ⦄ ⦄ := by
  apply WP.spec_mono (blast_add_correct aig a b hab hcap ha hb hne h0)
  rintro ⟨out, aig'⟩ ⟨hlen, hsim⟩
  intro inputs hwf
  apply WP.spec_mono (hsim inputs hwf)
  intro vals hbit hA hB
  obtain ⟨hal, hAj⟩ := hA
  obtain ⟨hbl, hBj⟩ := hB
  refine ⟨by omega, fun j hj => ?_⟩
  have hjw : j < w := by omega
  rw [hbit j hj (by omega) (by omega), hAj j (by omega), hBj j (by omega),
    pCarry_eq_carry ⟨hal, hAj⟩ ⟨hbl, hBj⟩ false j (by omega),
    BitVec.getLsbD_add hjw]

/- ══════════════ END-TO-END: `blast_sub` ══════════════ -/

/-- **`blast_sub` implements `BitVec` subtraction, for every width `w`**:
    two's complement, `A - B = A + ~~~B + 1` (carry-in `true`, negated `b`
    word). -/
theorem blast_sub_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + 9 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (A B : BitVec w) :
    blast_sub aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          Denotes vals.val p.1.val w (A - B) ⦄ ⦄ := by
  unfold blast_sub
  step with (word_not_spec b) as ⟨nb, hnb⟩
  have hderef : (alloc.vec.Vec.deref nb).val = nb.val := rfl
  step with lit_true_spec as ⟨l, hl⟩
  simp only [hl]
  have hnblen : (alloc.vec.Vec.deref nb).val.length = b.val.length := by
    rw [hderef, hnb]
    simp
  have hnbrng : ∀ l ∈ (alloc.vec.Vec.deref nb).val,
      l.node.val < aig.nodes.val.length := by
    rw [hderef, hnb]
    intro l hl
    rw [List.mem_map] at hl
    obtain ⟨l', hl', rfl⟩ := hl
    exact hb l' hl'
  have hcin : ({ node := 0#usize, neg := true } : Lit).node.val
      < aig.nodes.val.length := by
    scalar_tac
  step with (ripple_carry_spec aig a (alloc.vec.Vec.deref nb) _
    (by omega) hcap ha hnbrng hcin) as
    ⟨sum, carry, aig1, h1, h2, h3, h4, h5, h6, h7, h8⟩
  intro inputs hwf
  apply WP.spec_mono (simulate_spec aig1 inputs (h4 _ hwf))
  intro vals hv hA hB
  rw [hv] at hA hB ⊢
  obtain ⟨hbl, hBj⟩ := hB
  -- the negated word denotes `~~~B`
  have hnbD : Denotes (pSim inputs.val aig1.nodes.val)
      (alloc.vec.Vec.deref nb).val w (~~~B) := by
    refine ⟨by omega, fun j hj => ?_⟩
    have hjb : j < b.val.length := by omega
    have hjw : j < w := by omega
    have hgetj : (alloc.vec.Vec.deref nb).val[j]
        = { b.val[j]'hjb with neg := !(b.val[j]'hjb).neg } := by
      simp only [hderef, hnb]
      simp
    rw [hgetj, pEvalLit_not, hBj j hjb, BitVec.getLsbD_not]
    simp [hjw]
  obtain ⟨hal, hAj⟩ := hA
  refine ⟨by omega, fun j hj => ?_⟩
  have hjw : j < w := by omega
  have hja : j < a.val.length := by omega
  have hjnb : j < (alloc.vec.Vec.deref nb).val.length := by omega
  rw [h8 inputs.val j hj hja (by omega),
    pEvalLit_node_zero hne h0 inputs.val true,
    ← pEvalLit_stable h2 _ (ha _ (List.getElem_mem hja)) inputs.val,
    ← pEvalLit_stable h2 _ (hnbrng _ (List.getElem_mem hjnb)) inputs.val,
    ← pCarry_stable h2 ha hnbrng true inputs.val j (by omega) (by omega)]
  rw [hAj j hja, hnbD.2 j hjnb,
    pCarry_eq_carry ⟨hal, hAj⟩ hnbD true j (by omega),
    getLsbD_sub_carry A B hjw]

/- ══════════════ END-TO-END: `blast_ult` ══════════════ -/

/-- **`blast_ult` implements unsigned `<`, for every width `w`**: the returned
    literal evaluates to `decide (A < B)`. The borrow characterization: the
    carry-out of `A + ~~~B + 1` is `true` iff `A ≥ B`, and `blast_ult` negates
    it (`BitVec.ult_eq_not_carry`). -/
theorem blast_ult_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + 9 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (A B : BitVec w) :
    blast_ult aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          pEvalLit vals.val p.1 = decide (A < B) ⦄ ⦄ := by
  unfold blast_ult
  step with (word_not_spec b) as ⟨nb, hnb⟩
  have hderef : (alloc.vec.Vec.deref nb).val = nb.val := rfl
  step with lit_true_spec as ⟨l, hl⟩
  simp only [hl]
  have hnblen : (alloc.vec.Vec.deref nb).val.length = b.val.length := by
    rw [hderef, hnb]
    simp
  have hnbrng : ∀ l ∈ (alloc.vec.Vec.deref nb).val,
      l.node.val < aig.nodes.val.length := by
    rw [hderef, hnb]
    intro l hl
    rw [List.mem_map] at hl
    obtain ⟨l', hl', rfl⟩ := hl
    exact hb l' hl'
  have hcin : ({ node := 0#usize, neg := true } : Lit).node.val
      < aig.nodes.val.length := by
    scalar_tac
  step with (ripple_carry_spec aig a (alloc.vec.Vec.deref nb) _
    (by omega) hcap ha hnbrng hcin) as
    ⟨sum, carry, aig1, h1, h2, h3, h4, h5, h6, h7, h8⟩
  step with (lit_not_spec carry) as ⟨lres, hlres⟩
  intro inputs hwf
  apply WP.spec_mono (simulate_spec aig1 inputs (h4 _ hwf))
  intro vals hv hA hB
  rw [hv] at hA hB ⊢
  obtain ⟨hbl, hBj⟩ := hB
  have hnbD : Denotes (pSim inputs.val aig1.nodes.val)
      (alloc.vec.Vec.deref nb).val w (~~~B) := by
    refine ⟨by omega, fun j hj => ?_⟩
    have hjb : j < b.val.length := by omega
    have hjw : j < w := by omega
    have hgetj : (alloc.vec.Vec.deref nb).val[j]
        = { b.val[j]'hjb with neg := !(b.val[j]'hjb).neg } := by
      simp only [hderef, hnb]
      simp
    rw [hgetj, pEvalLit_not, hBj j hjb, BitVec.getLsbD_not]
    simp [hjw]
  obtain ⟨hal, hAj⟩ := hA
  have haw : a.val.length = w := hal
  rw [hlres, pEvalLit_not, h7 inputs.val,
    pEvalLit_node_zero hne h0 inputs.val true,
    ← pCarry_stable h2 ha hnbrng true inputs.val a.val.length (by omega)
      (by omega),
    haw, pCarry_eq_carry ⟨hal, hAj⟩ hnbD true w (by omega),
    ← BitVec.ult_eq_not_carry, BitVec.ult_eq_decide_lt]

end blast_kernel.spec
