/- Correctness of the bit-blaster's bitwise family (issue #68, v0.15.0).

   This file is HAND-WRITTEN (BlastKernel.lean is generated by regen-blaster.sh
   and must not be edited). It proves that the Aeneas model of the Rust
   bit-blaster rules `blast_and` / `blast_or` / `blast_xor` is correct against
   the formal `BitVec` semantics, for ALL widths.

   Proof architecture (a pure-model layer below the monadic code):
   * `pSim` is a PURE restatement of the AIG simulator: it folds over the node
     list, appending one Boolean per node; `pEvalLit` reads a literal
     (value XOR negation flag). The generated monadic `simulate` is proven to
     refine `pSim` (`simulate_spec`) under the well-formedness `AigWF`.
   * APPEND-MONOTONICITY is the workhorse: computing a node's value only reads
     strictly earlier values, so `pSim` of an extended node list has `pSim` of
     the original as a PREFIX (`pSim_prefix_of_prefix`), hence appending gates
     never changes the value of any pre-existing literal (`pEvalLit_stable`).
     In the pure model this holds unconditionally.
   * Each gate pusher gets a spec (`push_and_gadget` / `push_or_gadget` /
     `push_xor_gadget`): it appends gates, preserves well-formedness, and the
     returned literal evaluates to the AND / OR / XOR of its argument literals'
     values under the ORIGINAL aig.
   * Each blast rule is a loop over bit positions; `BlastInv` is the shared
     loop invariant, `BlastInv.step` its (rule-generic) preservation lemma.
   * `blast_and_correct` etc. compose the loop spec with `simulate_spec`:
     after blasting, simulating the extended aig gives, for every output bit,
     exactly the Boolean operation on the values of the input literals under
     the SAME simulation.
   * `blast_and_bitvec` etc. lift this to `BitVec w` for arbitrary `w`
     via `getLsbD_and` / `getLsbD_or` / `getLsbD_xor`.
-/
import BlastKernel

open Aeneas Aeneas.Std Result

set_option maxHeartbeats 1000000

namespace blast_kernel.spec

/- ══════════════════════════ THE PURE MODEL ══════════════════════════ -/

/-- Boolean value of a literal under a value list: the referenced node's value,
    negated if the literal's `neg` flag is set. Out-of-range reads default to
    `false`; every use below is guarded by an in-range hypothesis. -/
def pEvalLit (vals : List Bool) (l : Lit) : Bool :=
  if l.neg then !(vals.getD l.node.val false) else vals.getD l.node.val false

/-- Value contributed by one node, given the inputs and the values of all
    earlier nodes. -/
def pNodeVal (inp : List Bool) (vals : List Bool) : Node → Bool
  | .False => false
  | .Input k => inp.getD k.val false
  | .And x y => pEvalLit vals x && pEvalLit vals y

/-- Pure simulation, generalized over an accumulator of already-computed
    values. -/
def pSimAux (inp : List Bool) (vals : List Bool) : List Node → List Bool
  | [] => vals
  | nd :: ns => pSimAux inp (vals ++ [pNodeVal inp vals nd]) ns

/-- Pure simulation of an AIG node list: one Boolean per node. -/
def pSim (inp : List Bool) (ns : List Node) : List Bool :=
  pSimAux inp [] ns

theorem pSimAux_length (inp : List Bool) (vals : List Bool) (ns : List Node) :
    (pSimAux inp vals ns).length = vals.length + ns.length := by
  induction ns generalizing vals with
  | nil => simp [pSimAux]
  | cons nd ns ih =>
    simp only [pSimAux, ih, List.length_append, List.length_cons,
      List.length_nil]
    omega

@[simp]
theorem pSim_length (inp : List Bool) (ns : List Node) :
    (pSim inp ns).length = ns.length := by
  unfold pSim
  rw [pSimAux_length]
  simp

theorem pSimAux_prefix (inp : List Bool) (vals : List Bool) (ns : List Node) :
    vals <+: pSimAux inp vals ns := by
  induction ns generalizing vals with
  | nil => simp [pSimAux]
  | cons nd ns ih =>
    exact (List.prefix_append vals _).trans (ih _)

theorem pSimAux_append (inp : List Bool) (vals : List Bool) (ns ms : List Node) :
    pSimAux inp vals (ns ++ ms) = pSimAux inp (pSimAux inp vals ns) ms := by
  induction ns generalizing vals with
  | nil => simp [pSimAux]
  | cons nd ns ih => simp [pSimAux, ih]

/-- Unrolling one appended node: its value is computed from the values of all
    previous nodes. -/
theorem pSim_snoc (inp : List Bool) (ns : List Node) (nd : Node) :
    pSim inp (ns ++ [nd]) = pSim inp ns ++ [pNodeVal inp (pSim inp ns) nd] := by
  unfold pSim
  rw [pSimAux_append]
  rfl

/-- **Append-monotonicity of the pure simulator** (the workhorse): extending
    the node list only APPENDS values — the simulation of a prefix of the AIG
    is a prefix of the simulation. Existing nodes' values never change. -/
theorem pSim_prefix_of_prefix (inp : List Bool) {ns ns' : List Node}
    (h : ns <+: ns') : pSim inp ns <+: pSim inp ns' := by
  obtain ⟨t, rfl⟩ := h
  unfold pSim
  rw [pSimAux_append]
  exact pSimAux_prefix inp _ t

theorem getD_of_prefix {α : Type} {l l' : List α} {d : α} (h : l <+: l')
    {i : Nat} (hi : i < l.length) : l'.getD i d = l.getD i d := by
  obtain ⟨t, rfl⟩ := h
  rw [List.getD_eq_getElem?_getD, List.getD_eq_getElem?_getD,
    List.getElem?_append_left hi]

theorem getD_snoc_length {α : Type} (l : List α) (x d : α) :
    (l ++ [x]).getD l.length d = x := by
  rw [List.getD_eq_getElem?_getD, List.getElem?_concat_length]
  rfl

theorem getD_eq_getElem_of_lt {α : Type} {l : List α} {i : Nat}
    (h : i < l.length) (d : α) : l.getD i d = l[i] := by
  rw [List.getD_eq_getElem?_getD, List.getElem?_eq_getElem h]
  rfl

/-- A literal's value only depends on a prefix of the value list containing
    its node. -/
theorem pEvalLit_of_prefix {vals vals' : List Bool} (h : vals <+: vals')
    (l : Lit) (hl : l.node.val < vals.length) :
    pEvalLit vals' l = pEvalLit vals l := by
  unfold pEvalLit
  rw [getD_of_prefix h hl]

/-- Append-monotonicity at the literal level: appending nodes to the AIG does
    not change the value of a literal referring to an existing node. -/
theorem pEvalLit_stable {ns ns' : List Node} (h : ns <+: ns') (l : Lit)
    (hl : l.node.val < ns.length) (inp : List Bool) :
    pEvalLit (pSim inp ns') l = pEvalLit (pSim inp ns) l :=
  pEvalLit_of_prefix (pSim_prefix_of_prefix inp h) l (by simpa using hl)

/-- Reading a freshly appended node through a literal pointing at it. -/
theorem pEvalLit_fresh (inp : List Bool) (ns : List Node) (nd : Node) (g : Lit)
    (hg : g.node.val = ns.length) :
    pEvalLit (pSim inp (ns ++ [nd])) g
      = if g.neg then !(pNodeVal inp (pSim inp ns) nd)
        else pNodeVal inp (pSim inp ns) nd := by
  have h : (pSim inp (ns ++ [nd])).getD g.node.val false
      = pNodeVal inp (pSim inp ns) nd := by
    rw [pSim_snoc, hg, ← pSim_length inp ns, getD_snoc_length]
  simp only [pEvalLit, h]

/-- Negating the `neg` flag negates the literal's value. -/
theorem pEvalLit_not (vals : List Bool) (l : Lit) :
    pEvalLit vals { l with neg := !l.neg } = !(pEvalLit vals l) := by
  cases hb : l.neg <;> simp [pEvalLit, hb]

/- ══════════════════════════ WELL-FORMEDNESS ══════════════════════════ -/

/-- Well-formedness of one node at index `i`: inputs are within the primary
    input vector, AND-gate children point strictly BELOW the gate. -/
def NodeWF (L i : Nat) : Node → Prop
  | .False => True
  | .Input k => k.val < L
  | .And x y => x.node.val < i ∧ y.node.val < i

/-- Well-formedness of an AIG w.r.t. an input vector of length `L`. This is
    what makes the monadic `simulate` total. -/
def AigWF (ns : List Node) (L : Nat) : Prop :=
  ∀ (i : Nat) (h : i < ns.length), NodeWF L i ns[i]

theorem AigWF_append_and {ns : List Node} {L : Nat} (h : AigWF ns L) {x y : Lit}
    (hx : x.node.val < ns.length) (hy : y.node.val < ns.length) :
    AigWF (ns ++ [Node.And x y]) L := by
  intro i hi
  simp only [List.length_append, List.length_cons, List.length_nil] at hi
  by_cases hlt : i < ns.length
  · rw [List.getElem_append_left hlt]
    exact h i hlt
  · have hieq : i = ns.length := by omega
    have : (ns ++ [Node.And x y])[i] = Node.And x y :=
      List.getElem_concat_length hieq _
    rw [this]
    simp only [NodeWF]
    omega

/- ══════════════════ LEAF SPECS FOR THE MONADIC MODEL ══════════════════ -/

theorem lit_not_spec (l : Lit) :
    lit_not l ⦃ l' => l' = { l with neg := !l.neg } ⦄ := by
  unfold lit_not
  simp

theorem eval_lit_spec (vals : Slice Bool) (l : Lit)
    (h : l.node.val < vals.val.length) :
    eval_lit vals l ⦃ b => b = pEvalLit vals.val l ⦄ := by
  unfold eval_lit
  step as ⟨v, hv⟩
  split
  · rename_i hneg
    simp [pEvalLit, hneg, hv, List.getElem?_eq_getElem h]
  · rename_i hneg
    simp only [Bool.not_eq_true] at hneg
    simp [pEvalLit, hneg, hv, List.getElem?_eq_getElem h]

/-- Structural spec of `push_and`: appends exactly one AND gate and returns a
    positive literal pointing at it. -/
theorem push_and_spec (aig : Aig) (x y : Lit)
    (hcap : aig.nodes.val.length < Usize.max) :
    push_and aig x y ⦃ p =>
      p.2.nodes.val = aig.nodes.val ++ [Node.And x y] ∧
      p.1.node.val = aig.nodes.val.length ∧ p.1.neg = false ⦄ := by
  unfold push_and
  step as ⟨v, hv⟩
  simp [hv]

/-- Gadget spec for `push_and`: one gate, output literal = conjunction of the
    input literals' values (under the ORIGINAL aig — append-monotonicity). -/
theorem push_and_gadget (aig : Aig) (x y : Lit)
    (hcap : aig.nodes.val.length + 1 ≤ Usize.max)
    (hx : x.node.val < aig.nodes.val.length)
    (hy : y.node.val < aig.nodes.val.length) :
    push_and aig x y ⦃ p =>
      p.2.nodes.val.length = aig.nodes.val.length + 1 ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.1.node.val < p.2.nodes.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ inp : List Bool,
        pEvalLit (pSim inp p.2.nodes.val) p.1
          = (pEvalLit (pSim inp aig.nodes.val) x
             && pEvalLit (pSim inp aig.nodes.val) y)) ⦄ := by
  apply WP.spec_mono (push_and_spec aig x y (by omega))
  rintro ⟨g, aig'⟩ ⟨h1, h2, h3⟩
  dsimp only at h1 h2 h3 ⊢
  refine ⟨by simp [h1], ?_, ?_, ?_, ?_⟩
  · rw [h1]; exact List.prefix_append _ _
  · simp [h1, h2]
  · intro L hL
    rw [h1]
    exact AigWF_append_and hL hx hy
  · intro inp
    rw [h1, pEvalLit_fresh inp _ _ g h2, h3]
    simp [pNodeVal]

/-- Gadget spec for `push_or` (De Morgan: `x ∨ y = ¬(¬x ∧ ¬y)`, one gate plus
    a negated output literal). -/
theorem push_or_gadget (aig : Aig) (x y : Lit)
    (hcap : aig.nodes.val.length + 1 ≤ Usize.max)
    (hx : x.node.val < aig.nodes.val.length)
    (hy : y.node.val < aig.nodes.val.length) :
    push_or aig x y ⦃ p =>
      p.2.nodes.val.length = aig.nodes.val.length + 1 ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.1.node.val < p.2.nodes.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ inp : List Bool,
        pEvalLit (pSim inp p.2.nodes.val) p.1
          = (pEvalLit (pSim inp aig.nodes.val) x
             || pEvalLit (pSim inp aig.nodes.val) y)) ⦄ := by
  unfold push_or
  step with (lit_not_spec x) as ⟨nx, hnx⟩
  step with (lit_not_spec y) as ⟨ny, hny⟩
  step with (push_and_spec aig nx ny (by omega)) as ⟨na, aig1, h1, h2, h3⟩
  step with (lit_not_spec na) as ⟨g, hg⟩
  have hgnode : g.node.val = aig.nodes.val.length := by
    rw [hg]; exact h2
  refine ⟨by simp [h1], ?_, ?_, ?_, ?_⟩
  · rw [h1]; exact List.prefix_append _ _
  · simp [h1, hgnode]
  · intro L hL
    rw [h1]
    exact AigWF_append_and hL (by simp [hnx]; exact hx) (by simp [hny]; exact hy)
  · intro inp
    rw [h1, pEvalLit_fresh inp _ _ g hgnode]
    have hgneg : g.neg = true := by rw [hg, h3]; rfl
    rw [hgneg]
    simp only [pNodeVal, hnx, hny, pEvalLit_not]
    cases pEvalLit (pSim inp aig.nodes.val) x <;>
      cases pEvalLit (pSim inp aig.nodes.val) y <;> rfl

/-- Gadget spec for `push_xor` (three gates:
    `x ⊕ y = (x ∨ y) ∧ ¬(x ∧ y)`). -/
theorem push_xor_gadget (aig : Aig) (x y : Lit)
    (hcap : aig.nodes.val.length + 3 ≤ Usize.max)
    (hx : x.node.val < aig.nodes.val.length)
    (hy : y.node.val < aig.nodes.val.length) :
    push_xor aig x y ⦃ p =>
      p.2.nodes.val.length = aig.nodes.val.length + 3 ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.1.node.val < p.2.nodes.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ inp : List Bool,
        pEvalLit (pSim inp p.2.nodes.val) p.1
          = (pEvalLit (pSim inp aig.nodes.val) x
             ^^ pEvalLit (pSim inp aig.nodes.val) y)) ⦄ := by
  unfold push_xor
  step with (push_or_gadget aig x y (by omega) hx hy) as
    ⟨o, aig1, ho1, ho2, ho3, ho4, ho5⟩
  have hx1 : x.node.val < aig1.nodes.val.length := by omega
  have hy1 : y.node.val < aig1.nodes.val.length := by omega
  step with (push_and_gadget aig1 x y (by omega) hx1 hy1) as
    ⟨ga, aig2, ha1, ha2, ha3, ha4, ha5⟩
  step with (lit_not_spec ga) as ⟨l, hl⟩
  have ho3' : o.node.val < aig2.nodes.val.length := by omega
  have hl3 : l.node.val < aig2.nodes.val.length := by
    simp only [hl]; exact ha3
  apply WP.spec_mono (push_and_gadget aig2 o l (by omega) ho3' hl3)
  rintro ⟨g, aig3⟩ ⟨hg1, hg2, hg3, hg4, hg5⟩
  refine ⟨by omega, ho2.trans (ha2.trans hg2), hg3,
    fun L hL => hg4 L (ha4 L (ho4 L hL)), fun inp => ?_⟩
  rw [hg5 inp, pEvalLit_stable ha2 o ho3 inp, ho5 inp, hl, pEvalLit_not,
    ha5 inp, pEvalLit_stable ho2 x hx inp, pEvalLit_stable ho2 y hy inp]
  cases pEvalLit (pSim inp aig.nodes.val) x <;>
    cases pEvalLit (pSim inp aig.nodes.val) y <;> rfl

/- ══════════════ REFINEMENT OF THE MONADIC SIMULATOR ══════════════ -/

/-- The generated monadic `simulate` refines the pure `pSim` on well-formed
    AIGs (in particular, it cannot fail: total correctness). -/
theorem simulate_spec (aig : Aig) (inputs : Slice Bool)
    (hwf : AigWF aig.nodes.val inputs.val.length) :
    simulate aig inputs ⦃ vals => vals.val = pSim inputs.val aig.nodes.val ⦄ := by
  unfold simulate simulate_loop
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec Bool × Std.Usize) =>
      aig.nodes.val.length - s.2.val)
    (inv := fun (s : alloc.vec.Vec Bool × Std.Usize) =>
      s.2.val ≤ aig.nodes.val.length ∧
      s.1.val = pSim inputs.val (aig.nodes.val.take s.2.val))
  · rintro ⟨vals, i⟩ ⟨hle, hv⟩
    dsimp only at hle hv
    unfold simulate_loop.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < aig.nodes.val.length := by scalar_tac
      have hvlen : vals.val.length = i.val := by
        rw [hv, pSim_length, List.length_take]
        omega
      have htake : aig.nodes.val.take (i.val + 1)
          = aig.nodes.val.take i.val ++ [aig.nodes.val[i.val]] := by
        rw [List.take_add_one, List.getElem?_eq_getElem hilt]
        simp
      have hcap : vals.val.length < Usize.max := by
        have := aig.nodes.len_ineq
        omega
      step as ⟨node, hnode⟩
      have hNW := hwf i.val hilt
      cases node with
      | False =>
        dsimp only
        step as ⟨vals1, hvals1⟩
        step as ⟨i1, hi1⟩
        refine ⟨by scalar_tac, ?_, by scalar_tac⟩
        rw [hi1, htake, pSim_snoc, hvals1, hv, ← hnode]
        rfl
      | Input k =>
        rw [← hnode] at hNW
        simp only [NodeWF] at hNW
        step as ⟨bv, hbv⟩
        step as ⟨vals1, hvals1⟩
        step as ⟨i1, hi1⟩
        refine ⟨by scalar_tac, ?_, by scalar_tac⟩
        rw [hi1, htake, pSim_snoc, hvals1, hv, ← hnode]
        simp only [pNodeVal, hbv, getD_eq_getElem_of_lt hNW]
      | And x y =>
        rw [← hnode] at hNW
        simp only [NodeWF] at hNW
        obtain ⟨hxw, hyw⟩ := hNW
        dsimp only
        have hxb : x.node.val < (alloc.vec.Vec.deref vals).val.length := by
          simp only [alloc.vec.Vec.deref]
          omega
        have hyb : y.node.val < (alloc.vec.Vec.deref vals).val.length := by
          simp only [alloc.vec.Vec.deref]
          omega
        step with (eval_lit_spec (alloc.vec.Vec.deref vals) x hxb) as ⟨vx, hvx⟩
        step with (eval_lit_spec (alloc.vec.Vec.deref vals) y hyb) as ⟨vy, hvy⟩
        have hderef : (alloc.vec.Vec.deref vals).val = vals.val := rfl
        rw [hderef] at hvx hvy
        split
        · rename_i hvxt
          step as ⟨vals1, hvals1⟩
          step as ⟨i1, hi1⟩
          refine ⟨by scalar_tac, ?_, by scalar_tac⟩
          rw [hi1, htake, pSim_snoc, hvals1, hv, ← hnode]
          simp only [pNodeVal, ← hv, hvx, hvy] at *
          simp [hvxt]
        · rename_i hvxf
          step as ⟨vals1, hvals1⟩
          step as ⟨i1, hi1⟩
          refine ⟨by scalar_tac, ?_, by scalar_tac⟩
          rw [hi1, htake, pSim_snoc, hvals1, hv, ← hnode]
          have hvxf' : vx = false := by
            cases hvx' : vx
            · rfl
            · exact absurd hvx' hvxf
          simp only [pNodeVal, ← hv, ← hvx, ← hvy, hvxf']
          rfl
    · rename_i hge
      have hik : i.val = aig.nodes.val.length := by scalar_tac
      rw [hik, List.take_length] at hv
      exact hv
  · constructor
    · simp
    · simp [pSim, pSimAux]

/- ══════════════════ THE BLAST LOOPS: SHARED INVARIANT ══════════════════ -/

/-- Loop invariant shared by `blast_and` / `blast_or` / `blast_xor` after `i`
    processed bits: `k` gates per bit were appended, the original AIG is a
    prefix (nothing existing was touched), well-formedness is preserved, and
    every emitted output literal evaluates — under the CURRENT aig — to
    `op` of the values its input literals have under the ORIGINAL aig. -/
def BlastInv (op : Bool → Bool → Bool) (k : Nat) (aig : Aig) (a b : Slice Lit)
    (aig1 : Aig) (out1 : alloc.vec.Vec Lit) (i : Nat) : Prop :=
  i ≤ a.val.length ∧
  aig1.nodes.val.length = aig.nodes.val.length + k * i ∧
  aig.nodes.val <+: aig1.nodes.val ∧
  (∀ L, AigWF aig.nodes.val L → AigWF aig1.nodes.val L) ∧
  out1.val.length = i ∧
  (∀ l ∈ out1.val, l.node.val < aig1.nodes.val.length) ∧
  ∀ (inp : List Bool) (j : Nat) (hj1 : j < out1.val.length)
    (hj2 : j < a.val.length) (hj3 : j < b.val.length),
    pEvalLit (pSim inp aig1.nodes.val) out1.val[j]
      = op (pEvalLit (pSim inp aig.nodes.val) a.val[j])
           (pEvalLit (pSim inp aig.nodes.val) b.val[j])

theorem BlastInv.init (op : Bool → Bool → Bool) (k : Nat) (aig : Aig)
    (a b : Slice Lit) : BlastInv op k aig a b aig (alloc.vec.Vec.new Lit) 0 := by
  unfold BlastInv
  refine ⟨Nat.zero_le _, by simp, List.prefix_refl _, fun _ h => h, by simp,
    by simp, ?_⟩
  intro _ j hj1 _ _
  simp at hj1

/-- Preservation: pushing one gadget for bit `i` and appending its output
    literal re-establishes the invariant at `i + 1`. -/
theorem BlastInv.step {op : Bool → Bool → Bool} {k : Nat} {aig : Aig}
    {a b : Slice Lit} {aig1 aig2 : Aig} {out1 out2 : alloc.vec.Vec Lit}
    {g : Lit} {i : Nat}
    (h : BlastInv op k aig a b aig1 out1 i)
    (hia : i < a.val.length) (hib : i < b.val.length)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hglen : aig2.nodes.val.length = aig1.nodes.val.length + k)
    (hgpre : aig1.nodes.val <+: aig2.nodes.val)
    (hgnode : g.node.val < aig2.nodes.val.length)
    (hgwf : ∀ L, AigWF aig1.nodes.val L → AigWF aig2.nodes.val L)
    (hgsem : ∀ inp : List Bool,
      pEvalLit (pSim inp aig2.nodes.val) g
        = op (pEvalLit (pSim inp aig1.nodes.val) (a.val[i]'hia))
             (pEvalLit (pSim inp aig1.nodes.val) (b.val[i]'hib)))
    (hout2 : out2.val = out1.val ++ [g]) :
    BlastInv op k aig a b aig2 out2 (i + 1) := by
  obtain ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩ := h
  refine ⟨by omega, by rw [hglen, hlen1, Nat.mul_succ, Nat.add_assoc],
    hpre1.trans hgpre, fun L hL => hgwf L (hwf1 L hL),
    by rw [hout2]; simp [holen], ?_, ?_⟩
  · intro l hl
    rw [hout2] at hl
    rcases List.mem_append.mp hl with h' | h'
    · exact Nat.lt_of_lt_of_le (horng l h') hgpre.length_le
    · simp only [List.mem_singleton] at h'
      subst h'
      exact hgnode
  · intro inp j hj1 hj2 hj3
    have hj1' : j < out1.val.length + 1 := by
      rw [hout2] at hj1
      simpa using hj1
    rcases Nat.lt_or_ge j out1.val.length with hji | hji
    · have hgetj : out2.val[j]'hj1 = out1.val[j]'hji := by
        simp only [hout2]
        exact List.getElem_append_left hji
      rw [hgetj, pEvalLit_stable hgpre _ (horng _ (List.getElem_mem _)) inp]
      exact hsem inp j hji hj2 hj3
    · have hjeq : j = i := by omega
      subst hjeq
      have hgetj : out2.val[j]'hj1 = g := by
        simp only [hout2]
        exact List.getElem_concat_length (by omega) _
      rw [hgetj, hgsem inp,
        pEvalLit_stable hpre1 _ (ha _ (List.getElem_mem _)) inp,
        pEvalLit_stable hpre1 _ (hb _ (List.getElem_mem _)) inp]

/- ══════════════════ PER-RULE LOOP SPECS ══════════════════ -/

/-- `blast_and` appends one AND gate per bit; every output literal evaluates
    (under the extended aig) to the conjunction of the corresponding input
    bits' values (under the original aig). Total correctness: no failure. -/
theorem blast_and_spec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length) :
    blast_and aig a b ⦃ p =>
      p.1.val.length = a.val.length ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.2.nodes.val.length = aig.nodes.val.length + a.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ l ∈ p.1.val, l.node.val < p.2.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj1 : j < p.1.val.length)
        (hj2 : j < a.val.length) (hj3 : j < b.val.length),
        pEvalLit (pSim inp p.2.nodes.val) p.1.val[j]
          = (pEvalLit (pSim inp aig.nodes.val) a.val[j]
             && pEvalLit (pSim inp aig.nodes.val) b.val[j]) ⦄ := by
  unfold blast_and blast_and_loop
  apply loop.spec_decr_nat
    (measure := fun (s : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      a.val.length - s.2.2.val)
    (inv := fun (s : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      BlastInv (· && ·) 1 aig a b s.1 s.2.1 s.2.2.val)
  · rintro ⟨aig1, out1, i⟩ hinv
    obtain ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩ := hinv
    dsimp only at hile hlen1 hpre1 hwf1 holen horng hsem
    unfold blast_and_loop.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < a.val.length := by scalar_tac
      have hibt : i.val < b.val.length := by omega
      step as ⟨la, hla⟩
      step as ⟨lb, hlb⟩
      have hla' : la.node.val < aig1.nodes.val.length := by
        have h1 := ha la (by rw [hla]; exact List.getElem_mem _)
        have h2 := hpre1.length_le
        omega
      have hlb' : lb.node.val < aig1.nodes.val.length := by
        have h1 := hb lb (by rw [hlb]; exact List.getElem_mem _)
        have h2 := hpre1.length_le
        omega
      step with (push_and_gadget aig1 la lb (by omega) hla' hlb') as
        ⟨g, aig2, hg1, hg2, hg3, hg4, hg5⟩
      have houtcap : out1.val.length < Usize.max := by
        have := a.length_ineq
        omega
      step as ⟨out2, hout2⟩
      step as ⟨i1, hi1⟩
      refine ⟨?_, by scalar_tac⟩
      rw [hi1]
      subst hla hlb
      exact BlastInv.step ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩
        hilt hibt ha hb hg1 hg2 hg3 hg4 hg5 hout2
    · rename_i hge
      have hieq : i.val = a.val.length := by scalar_tac
      refine ⟨by dsimp only; omega, hpre1, by dsimp only; omega, hwf1, horng, ?_⟩
      intro inp j hj1 hj2 hj3
      exact hsem inp j hj1 hj2 hj3
  · exact BlastInv.init (· && ·) 1 aig a b

/-- `blast_or`: same shape, one De-Morgan gate per bit. -/
theorem blast_or_spec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length) :
    blast_or aig a b ⦃ p =>
      p.1.val.length = a.val.length ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.2.nodes.val.length = aig.nodes.val.length + a.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ l ∈ p.1.val, l.node.val < p.2.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj1 : j < p.1.val.length)
        (hj2 : j < a.val.length) (hj3 : j < b.val.length),
        pEvalLit (pSim inp p.2.nodes.val) p.1.val[j]
          = (pEvalLit (pSim inp aig.nodes.val) a.val[j]
             || pEvalLit (pSim inp aig.nodes.val) b.val[j]) ⦄ := by
  unfold blast_or blast_or_loop
  apply loop.spec_decr_nat
    (measure := fun (s : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      a.val.length - s.2.2.val)
    (inv := fun (s : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      BlastInv (· || ·) 1 aig a b s.1 s.2.1 s.2.2.val)
  · rintro ⟨aig1, out1, i⟩ hinv
    obtain ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩ := hinv
    dsimp only at hile hlen1 hpre1 hwf1 holen horng hsem
    unfold blast_or_loop.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < a.val.length := by scalar_tac
      have hibt : i.val < b.val.length := by omega
      step as ⟨la, hla⟩
      step as ⟨lb, hlb⟩
      have hla' : la.node.val < aig1.nodes.val.length := by
        have h1 := ha la (by rw [hla]; exact List.getElem_mem _)
        have h2 := hpre1.length_le
        omega
      have hlb' : lb.node.val < aig1.nodes.val.length := by
        have h1 := hb lb (by rw [hlb]; exact List.getElem_mem _)
        have h2 := hpre1.length_le
        omega
      step with (push_or_gadget aig1 la lb (by omega) hla' hlb') as
        ⟨g, aig2, hg1, hg2, hg3, hg4, hg5⟩
      have houtcap : out1.val.length < Usize.max := by
        have := a.length_ineq
        omega
      step as ⟨out2, hout2⟩
      step as ⟨i1, hi1⟩
      refine ⟨?_, by scalar_tac⟩
      rw [hi1]
      subst hla hlb
      exact BlastInv.step ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩
        hilt hibt ha hb hg1 hg2 hg3 hg4 hg5 hout2
    · rename_i hge
      have hieq : i.val = a.val.length := by scalar_tac
      refine ⟨by dsimp only; omega, hpre1, by dsimp only; omega, hwf1, horng, ?_⟩
      intro inp j hj1 hj2 hj3
      exact hsem inp j hj1 hj2 hj3
  · exact BlastInv.init (· || ·) 1 aig a b

/-- `blast_xor`: same shape, three gates per bit. -/
theorem blast_xor_spec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + 3 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length) :
    blast_xor aig a b ⦃ p =>
      p.1.val.length = a.val.length ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.2.nodes.val.length = aig.nodes.val.length + 3 * a.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ l ∈ p.1.val, l.node.val < p.2.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj1 : j < p.1.val.length)
        (hj2 : j < a.val.length) (hj3 : j < b.val.length),
        pEvalLit (pSim inp p.2.nodes.val) p.1.val[j]
          = (pEvalLit (pSim inp aig.nodes.val) a.val[j]
             ^^ pEvalLit (pSim inp aig.nodes.val) b.val[j]) ⦄ := by
  unfold blast_xor blast_xor_loop
  apply loop.spec_decr_nat
    (measure := fun (s : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      a.val.length - s.2.2.val)
    (inv := fun (s : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      BlastInv (· ^^ ·) 3 aig a b s.1 s.2.1 s.2.2.val)
  · rintro ⟨aig1, out1, i⟩ hinv
    obtain ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩ := hinv
    dsimp only at hile hlen1 hpre1 hwf1 holen horng hsem
    unfold blast_xor_loop.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < a.val.length := by scalar_tac
      have hibt : i.val < b.val.length := by omega
      step as ⟨la, hla⟩
      step as ⟨lb, hlb⟩
      have hla' : la.node.val < aig1.nodes.val.length := by
        have h1 := ha la (by rw [hla]; exact List.getElem_mem _)
        have h2 := hpre1.length_le
        omega
      have hlb' : lb.node.val < aig1.nodes.val.length := by
        have h1 := hb lb (by rw [hlb]; exact List.getElem_mem _)
        have h2 := hpre1.length_le
        omega
      step with (push_xor_gadget aig1 la lb (by omega) hla' hlb') as
        ⟨g, aig2, hg1, hg2, hg3, hg4, hg5⟩
      have houtcap : out1.val.length < Usize.max := by
        have := a.length_ineq
        omega
      step as ⟨out2, hout2⟩
      step as ⟨i1, hi1⟩
      refine ⟨?_, by scalar_tac⟩
      rw [hi1]
      subst hla hlb
      exact BlastInv.step ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩
        hilt hibt ha hb hg1 hg2 hg3 hg4 hg5 hout2
    · rename_i hge
      have hieq : i.val = a.val.length := by scalar_tac
      refine ⟨by dsimp only; omega, hpre1, by dsimp only; omega, hwf1, horng, ?_⟩
      intro inp j hj1 hj2 hj3
      exact hsem inp j hj1 hj2 hj3
  · exact BlastInv.init (· ^^ ·) 3 aig a b

/- ══════════════ END-TO-END: BLAST THEN SIMULATE ══════════════ -/

/-- **Correctness of `blast_and` against the simulator** (issue #68): after
    blasting, simulating the extended aig on ANY well-formed input assignment
    gives, for each output bit `j`, exactly the conjunction of the values the
    two input literals take under the SAME simulation. `pEvalLit vals.val l`
    is `vals[l.node] XOR l.neg`. Unbounded: `a`/`b` have arbitrary length. -/
theorem blast_and_correct (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length) :
    blast_and aig a b ⦃ p =>
      p.1.val.length = a.val.length ∧
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          ∀ (j : Nat) (hj1 : j < p.1.val.length) (hj2 : j < a.val.length)
            (hj3 : j < b.val.length),
            pEvalLit vals.val p.1.val[j]
              = (pEvalLit vals.val a.val[j] && pEvalLit vals.val b.val[j]) ⦄ ⦄ := by
  apply WP.spec_mono (blast_and_spec aig a b hab hcap ha hb)
  rintro ⟨out, aig'⟩ ⟨h1, h2, h3, h4, h5, h6⟩
  refine ⟨h1, fun inputs hwf => ?_⟩
  apply WP.spec_mono (simulate_spec aig' inputs (h4 _ hwf))
  intro vals hv j hj1 hj2 hj3
  rw [hv, pEvalLit_stable h2 _ (ha _ (List.getElem_mem _)) inputs.val,
    pEvalLit_stable h2 _ (hb _ (List.getElem_mem _)) inputs.val]
  exact h6 inputs.val j hj1 hj2 hj3

/-- **Correctness of `blast_or` against the simulator.** -/
theorem blast_or_correct (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length) :
    blast_or aig a b ⦃ p =>
      p.1.val.length = a.val.length ∧
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          ∀ (j : Nat) (hj1 : j < p.1.val.length) (hj2 : j < a.val.length)
            (hj3 : j < b.val.length),
            pEvalLit vals.val p.1.val[j]
              = (pEvalLit vals.val a.val[j] || pEvalLit vals.val b.val[j]) ⦄ ⦄ := by
  apply WP.spec_mono (blast_or_spec aig a b hab hcap ha hb)
  rintro ⟨out, aig'⟩ ⟨h1, h2, h3, h4, h5, h6⟩
  refine ⟨h1, fun inputs hwf => ?_⟩
  apply WP.spec_mono (simulate_spec aig' inputs (h4 _ hwf))
  intro vals hv j hj1 hj2 hj3
  rw [hv, pEvalLit_stable h2 _ (ha _ (List.getElem_mem _)) inputs.val,
    pEvalLit_stable h2 _ (hb _ (List.getElem_mem _)) inputs.val]
  exact h6 inputs.val j hj1 hj2 hj3

/-- **Correctness of `blast_xor` against the simulator.** -/
theorem blast_xor_correct (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + 3 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length) :
    blast_xor aig a b ⦃ p =>
      p.1.val.length = a.val.length ∧
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          ∀ (j : Nat) (hj1 : j < p.1.val.length) (hj2 : j < a.val.length)
            (hj3 : j < b.val.length),
            pEvalLit vals.val p.1.val[j]
              = (pEvalLit vals.val a.val[j] ^^ pEvalLit vals.val b.val[j]) ⦄ ⦄ := by
  apply WP.spec_mono (blast_xor_spec aig a b hab hcap ha hb)
  rintro ⟨out, aig'⟩ ⟨h1, h2, h3, h4, h5, h6⟩
  refine ⟨h1, fun inputs hwf => ?_⟩
  apply WP.spec_mono (simulate_spec aig' inputs (h4 _ hwf))
  intro vals hv j hj1 hj2 hj3
  rw [hv, pEvalLit_stable h2 _ (ha _ (List.getElem_mem _)) inputs.val,
    pEvalLit_stable h2 _ (hb _ (List.getElem_mem _)) inputs.val]
  exact h6 inputs.val j hj1 hj2 hj3

/- ══════════════ THE BITVEC SEMANTICS (UNBOUNDED WIDTH) ══════════════ -/

/-- A word of literals denotes a `BitVec w` under a value list: bit `j` of the
    bitvector is the value of the `j`-th literal (LSB first). -/
def Denotes (vals : List Bool) (word : List Lit) (w : Nat) (v : BitVec w) : Prop :=
  word.length = w ∧
  ∀ (j : Nat) (hj : j < word.length), pEvalLit vals word[j] = v.getLsbD j

/-- Generic lifting of a per-bit identity to `Denotes`. -/
theorem Denotes.of_bits {vals : List Bool} {a b out : List Lit} {w : Nat}
    {A B C : BitVec w} {op : Bool → Bool → Bool}
    (hA : Denotes vals a w A) (hB : Denotes vals b w B)
    (hC : ∀ j, j < w → C.getLsbD j = op (A.getLsbD j) (B.getLsbD j))
    (hlen : out.length = a.length)
    (hbit : ∀ (j : Nat) (hj1 : j < out.length) (hj2 : j < a.length)
      (hj3 : j < b.length),
      pEvalLit vals out[j] = op (pEvalLit vals a[j]) (pEvalLit vals b[j])) :
    Denotes vals out w C := by
  obtain ⟨hal, hA⟩ := hA
  obtain ⟨hbl, hB⟩ := hB
  refine ⟨by omega, fun j hj => ?_⟩
  rw [hbit j hj (by omega) (by omega), hA j (by omega), hB j (by omega),
    hC j (by omega)]

/-- **`blast_and` implements `BitVec` AND, for every width `w`**: if the input
    words denote `A` and `B` under the post-blast simulation, the output word
    denotes `A &&& B`. -/
theorem blast_and_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    {w : Nat} (A B : BitVec w) :
    blast_and aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          Denotes vals.val p.1.val w (A &&& B) ⦄ ⦄ := by
  apply WP.spec_mono (blast_and_correct aig a b hab hcap ha hb)
  rintro ⟨out, aig'⟩ ⟨hlen, hsim⟩
  intro inputs hwf
  apply WP.spec_mono (hsim inputs hwf)
  intro vals hbit hA hB
  exact Denotes.of_bits hA hB (fun j _ => by simp) hlen hbit

/-- **`blast_or` implements `BitVec` OR, for every width `w`.** -/
theorem blast_or_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    {w : Nat} (A B : BitVec w) :
    blast_or aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          Denotes vals.val p.1.val w (A ||| B) ⦄ ⦄ := by
  apply WP.spec_mono (blast_or_correct aig a b hab hcap ha hb)
  rintro ⟨out, aig'⟩ ⟨hlen, hsim⟩
  intro inputs hwf
  apply WP.spec_mono (hsim inputs hwf)
  intro vals hbit hA hB
  exact Denotes.of_bits hA hB (fun j _ => by simp) hlen hbit

/-- **`blast_xor` implements `BitVec` XOR, for every width `w`.** -/
theorem blast_xor_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + 3 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    {w : Nat} (A B : BitVec w) :
    blast_xor aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          Denotes vals.val p.1.val w (A ^^^ B) ⦄ ⦄ := by
  apply WP.spec_mono (blast_xor_correct aig a b hab hcap ha hb)
  rintro ⟨out, aig'⟩ ⟨hlen, hsim⟩
  intro inputs hwf
  apply WP.spec_mono (hsim inputs hwf)
  intro vals hbit hA hB
  exact Denotes.of_bits hA hB (fun j _ => by simp) hlen hbit

end blast_kernel.spec
