/- Correctness of the remaining light bit-blaster families (issue #68,
   v0.15.0): derived unsigned comparisons (`blast_ule` / `blast_ugt` /
   `blast_uge`), signed comparisons via MSB flip (`flip_sign`, `blast_slt` /
   `blast_sle` / `blast_sgt` / `blast_sge`), equality (`blast_eq` /
   `blast_ne`), multiplexing (`push_mux`, `blast_ite`) and the gate-free
   structural rules (`blast_extract`, `blast_concat`, `blast_zero_ext`,
   `blast_sign_ext`).

   This file is HAND-WRITTEN (BlastKernel.lean is generated by
   regen-blaster.sh and must not be edited). It builds on the pure-model
   infrastructure of BlasterProof.lean (`pSim` / `pEvalLit`,
   append-monotonicity, `AigWF`, the gadget-spec idiom, `simulate_spec`,
   `Denotes`) and BlasterArith.lean (`blast_ult_bitvec`, `lit_true_spec`,
   `pEvalLit_node_zero`).

   Proof architecture:
   * The unsigned wrappers are one `lit_not` (or an argument swap) away from
     the proven `blast_ult`; `BitVec.not_lt` closes the Boolean gap.
   * For the signed family, `flip_sign_spec` shows the output word is the
     input word with the MSB literal complemented, `Denotes.flip_sign` lifts
     that to `A ^^^ intMin w`, and `xor_intMin_lt_eq_slt` is the classic
     order embedding `A <ₛ B ↔ A ⊕ intMin <ᵤ B ⊕ intMin`. Its arithmetic
     core, `toNat_xor_intMin`, is proved WITHOUT bit-fiddling on `Nat.xor`:
     the low bits of `A ^^^ intMin w` agree with `A` (via `setWidth (w-1)`
     and `toNat_setWidth`), the MSB flips, and `omega` does the rest.
   * `blast_eq` is an AND-fold of per-bit XNORs starting from `lit_true`;
     `pEqBits` is the pure fold, `EqInv` the loop invariant, and
     `BitVec.eq_of_getLsbD_eq` bridges to `decide (A = B)`.
   * `push_mux_gadget` mirrors `push_xor_gadget` (three gates,
     `(sel ∧ t) ∨ (¬sel ∧ e)`); `IteInv` mirrors `BlastInv` with the select
     literal threaded through.
   * The structural rules push no gates at all: their loop specs are pure
     list computations (slice / append / replicate), and the `Denotes` lifts
     are `getLsbD` bookkeeping (`getLsbD_extractLsb`, `getLsbD_append`,
     `getLsbD_setWidth`, `getLsbD_signExtend`).
-/
import BlasterArith

open Aeneas Aeneas.Std Result

set_option maxHeartbeats 1000000

namespace blast_kernel.spec

/- ══════════════ DERIVED UNSIGNED COMPARISONS ══════════════ -/

/-- **`blast_ule` implements unsigned `≤`, for every width `w`**: the
    returned literal evaluates to `decide (A ≤ B)` (it is `¬(B <ᵤ A)`). -/
theorem blast_ule_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length = b.val.length)
    (hcap : aig.nodes.val.length + 9 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (A B : BitVec w) :
    blast_ule aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          pEvalLit vals.val p.1 = decide (A ≤ B) ⦄ ⦄ := by
  unfold blast_ule
  step with (blast_ult_bitvec aig b a (by omega) (by omega) hb ha hne h0 B A)
    as ⟨lt, aig1, hsim⟩
  step with (lit_not_spec lt) as ⟨l, hl⟩
  intro inputs hwf
  apply WP.spec_mono (hsim inputs hwf)
  intro vals hval hA hB
  rw [hl, pEvalLit_not, hval hB hA, ← decide_not, decide_eq_decide]
  exact BitVec.not_lt

/-- **`blast_ugt` implements unsigned `>`, for every width `w`**: the
    returned literal evaluates to `decide (B < A)`. -/
theorem blast_ugt_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length = b.val.length)
    (hcap : aig.nodes.val.length + 9 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (A B : BitVec w) :
    blast_ugt aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          pEvalLit vals.val p.1 = decide (B < A) ⦄ ⦄ := by
  unfold blast_ugt
  apply WP.spec_mono
    (blast_ult_bitvec aig b a (by omega) (by omega) hb ha hne h0 B A)
  rintro ⟨lt, aig1⟩ hsim
  intro inputs hwf
  apply WP.spec_mono (hsim inputs hwf)
  intro vals hval hA hB
  exact hval hB hA

/-- **`blast_uge` implements unsigned `≥`, for every width `w`**: the
    returned literal evaluates to `decide (B ≤ A)` (it is `¬(A <ᵤ B)`). -/
theorem blast_uge_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length = b.val.length)
    (hcap : aig.nodes.val.length + 9 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (A B : BitVec w) :
    blast_uge aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          pEvalLit vals.val p.1 = decide (B ≤ A) ⦄ ⦄ := by
  unfold blast_uge
  step with (blast_ult_bitvec aig a b (by omega) hcap ha hb hne h0 A B)
    as ⟨lt, aig1, hsim⟩
  step with (lit_not_spec lt) as ⟨l, hl⟩
  intro inputs hwf
  apply WP.spec_mono (hsim inputs hwf)
  intro vals hval hA hB
  rw [hl, pEvalLit_not, hval hA hB, ← decide_not, decide_eq_decide]
  exact BitVec.not_lt

/- ══════════════════════════ `flip_sign` ══════════════════════════ -/

/-- `flip_sign` copies the word, complementing exactly the MSB literal
    (index `w - 1`). No gates are pushed. Total correctness (on the empty
    word the loop never runs and the output is empty). -/
theorem flip_sign_spec (a : Slice Lit) :
    flip_sign a ⦃ out =>
      out.val.length = a.val.length ∧
      ∀ (j : Nat) (hj1 : j < out.val.length) (hj2 : j < a.val.length),
        out.val[j] = if j + 1 = a.val.length
          then { a.val[j] with neg := !(a.val[j]).neg } else a.val[j] ⦄ := by
  unfold flip_sign flip_sign_loop
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      a.val.length - s.2.val)
    (inv := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      s.2.val ≤ a.val.length ∧ s.1.val.length = s.2.val ∧
      ∀ (j : Nat) (hj1 : j < s.1.val.length) (hj2 : j < a.val.length),
        s.1.val[j] = if j + 1 = a.val.length
          then { a.val[j] with neg := !(a.val[j]).neg } else a.val[j])
  · rintro ⟨out1, i⟩ ⟨hle, hlen, hval⟩
    dsimp only at hle hlen hval
    unfold flip_sign_loop.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < a.val.length := by scalar_tac
      have hocap : out1.val.length < Usize.max := by
        have := a.length_ineq
        omega
      step as ⟨i1, hi1⟩
      split
      · rename_i heq
        have heq' : i.val + 1 = a.val.length := by scalar_tac
        step as ⟨l, hl⟩
        step with (lit_not_spec l) as ⟨l1, hl1⟩
        step as ⟨out2, hout2⟩
        refine ⟨by scalar_tac, ?_, ?_, by scalar_tac⟩
        · rw [hout2]
          simp only [List.length_append, List.length_cons, List.length_nil]
          omega
        · intro j hj1 hj2
          have hj1' : j < out1.val.length + 1 := by
            rw [hout2] at hj1
            simpa using hj1
          rcases Nat.lt_or_ge j out1.val.length with hji | hji
          · have hgetj : out2.val[j]'hj1 = out1.val[j]'hji := by
              simp only [hout2]
              exact List.getElem_append_left hji
            rw [hgetj]
            exact hval j hji hj2
          · have hjeq : j = i.val := by omega
            have hgetj : out2.val[j]'hj1 = l1 := by
              simp only [hout2]
              exact List.getElem_concat_length (by omega) _
            rw [hgetj, hl1, hl]
            simp only [hjeq]
            rw [if_pos heq']
      · rename_i hneq
        have hneq' : ¬(i.val + 1 = a.val.length) := by scalar_tac
        step as ⟨l, hl⟩
        step as ⟨out2, hout2⟩
        refine ⟨by scalar_tac, ?_, ?_, by scalar_tac⟩
        · rw [hout2]
          simp only [List.length_append, List.length_cons, List.length_nil]
          omega
        · intro j hj1 hj2
          have hj1' : j < out1.val.length + 1 := by
            rw [hout2] at hj1
            simpa using hj1
          rcases Nat.lt_or_ge j out1.val.length with hji | hji
          · have hgetj : out2.val[j]'hj1 = out1.val[j]'hji := by
              simp only [hout2]
              exact List.getElem_append_left hji
            rw [hgetj]
            exact hval j hji hj2
          · have hjeq : j = i.val := by omega
            have hgetj : out2.val[j]'hj1 = l := by
              simp only [hout2]
              exact List.getElem_concat_length (by omega) _
            rw [hgetj, hl]
            simp only [hjeq]
            rw [if_neg hneq']
    · rename_i hge
      have hieq : i.val = a.val.length := by scalar_tac
      exact ⟨by omega, fun j hj1 hj2 => hval j hj1 hj2⟩
  · exact ⟨Nat.zero_le _, by simp, fun j hj1 _ => by simp at hj1⟩

/- ══════════════ THE SIGNED ORDER EMBEDDING ══════════════ -/

private theorem two_pow_pred {w : Nat} (hw : 0 < w) :
    2 ^ w = 2 * 2 ^ (w - 1) := by
  conv_lhs => rw [show w = (w - 1) + 1 by omega]
  rw [Nat.pow_succ]
  omega

/-- Arithmetic core of the signed embedding: XOR with `intMin w` adds
    `2^(w-1)` if the MSB was clear, subtracts it if it was set. Proved via
    the low-bits (`setWidth (w-1)`) / MSB decomposition — no `Nat.xor`
    bit-fiddling. -/
theorem toNat_xor_intMin {w : Nat} (hw : 0 < w) (A : BitVec w) :
    (A ^^^ BitVec.intMin w).toNat
      = if 2 ^ (w - 1) ≤ A.toNat then A.toNat - 2 ^ (w - 1)
        else A.toNat + 2 ^ (w - 1) := by
  have h2w := two_pow_pred hw
  have hFlt := (A ^^^ BitVec.intMin w).isLt
  have hAlt := A.isLt
  -- the low `w - 1` bits are untouched
  have hset : (A ^^^ BitVec.intMin w).setWidth (w - 1) = A.setWidth (w - 1) := by
    apply BitVec.eq_of_getLsbD_eq
    intro i hi
    simp [BitVec.getLsbD_intMin, show ¬(i + 1 = w) by omega]
  have hlow : (A ^^^ BitVec.intMin w).toNat % 2 ^ (w - 1)
      = A.toNat % 2 ^ (w - 1) := by
    have := congrArg BitVec.toNat hset
    simp only [BitVec.toNat_setWidth] at this
    exact this
  -- the MSB flips
  have hmsb : (A ^^^ BitVec.intMin w).msb = !A.msb := by
    simp [BitVec.msb_intMin, hw]
  rw [BitVec.msb_eq_decide, BitVec.msb_eq_decide, ← decide_not] at hmsb
  have hmsb' : (2 ^ (w - 1) ≤ (A ^^^ BitVec.intMin w).toNat)
      ↔ ¬(2 ^ (w - 1) ≤ A.toNat) := decide_eq_decide.mp hmsb
  rcases Nat.lt_or_ge A.toNat (2 ^ (w - 1)) with hc | hc
  · have hcF : 2 ^ (w - 1) ≤ (A ^^^ BitVec.intMin w).toNat :=
      hmsb'.mpr (by omega)
    rw [Nat.mod_eq_sub_mod hcF, Nat.mod_eq_of_lt (by omega),
      Nat.mod_eq_of_lt hc] at hlow
    rw [if_neg (by omega)]
    omega
  · have hcF : ¬2 ^ (w - 1) ≤ (A ^^^ BitVec.intMin w).toNat :=
      fun h => (hmsb'.mp h) hc
    rw [Nat.mod_eq_of_lt (by omega), Nat.mod_eq_sub_mod hc,
      Nat.mod_eq_of_lt (by omega)] at hlow
    rw [if_pos hc]
    omega

/-- **The signed order embedding**: flipping both MSBs turns signed
    comparison into unsigned comparison,
    `(A ^^^ intMin) <ᵤ (B ^^^ intMin) = A <ₛ B`. -/
theorem xor_intMin_lt_eq_slt {w : Nat} (hw : 0 < w) (A B : BitVec w) :
    decide ((A ^^^ BitVec.intMin w) < (B ^^^ BitVec.intMin w)) = A.slt B := by
  by_cases hmsb : A.msb = B.msb
  · rw [BitVec.slt_eq_ult_of_msb_eq hmsb, BitVec.ult_eq_decide_lt,
      decide_eq_decide, BitVec.lt_def, BitVec.lt_def,
      toNat_xor_intMin hw A, toNat_xor_intMin hw B]
    rw [BitVec.msb_eq_decide, BitVec.msb_eq_decide] at hmsb
    have hiff : (2 ^ (w - 1) ≤ A.toNat) ↔ (2 ^ (w - 1) ≤ B.toNat) :=
      decide_eq_decide.mp hmsb
    have hA := A.isLt
    have hB := B.isLt
    have h2w := two_pow_pred hw
    by_cases hc : 2 ^ (w - 1) ≤ A.toNat
    · have hc' : 2 ^ (w - 1) ≤ B.toNat := hiff.mp hc
      rw [if_pos hc, if_pos hc']
      omega
    · have hc' : ¬2 ^ (w - 1) ≤ B.toNat := fun h => hc (hiff.mpr h)
      rw [if_neg hc, if_neg hc']
      omega
  · have hFneq : (A ^^^ BitVec.intMin w).msb ≠ (B ^^^ BitVec.intMin w).msb := by
      simp only [BitVec.msb_xor, BitVec.msb_intMin, hw, decide_true,
        Bool.xor_true]
      intro h
      exact hmsb (by cases hA : A.msb <;> cases hB : B.msb <;> simp_all)
    rw [BitVec.slt_eq_not_ult_of_msb_neq hmsb,
      BitVec.ult_eq_msb_of_msb_neq hmsb, ← BitVec.ult_eq_decide_lt,
      BitVec.ult_eq_msb_of_msb_neq hFneq]
    simp [BitVec.msb_intMin, hw]

/-- Lifting `flip_sign`'s output to `Denotes`: if the input word denotes
    `A`, the MSB-complemented word denotes `A ^^^ intMin w`. -/
theorem Denotes.flip_sign {vals : List Bool} {a fa : List Lit} {w : Nat}
    {A : BitVec w} (hA : Denotes vals a w A)
    (hlen : fa.length = a.length)
    (hbits : ∀ (j : Nat) (hj1 : j < fa.length) (hj2 : j < a.length),
      fa[j] = if j + 1 = a.length
        then { a[j] with neg := !(a[j]).neg } else a[j]) :
    Denotes vals fa w (A ^^^ BitVec.intMin w) := by
  obtain ⟨hal, hAj⟩ := hA
  refine ⟨by omega, fun j hj => ?_⟩
  have hja : j < a.length := by omega
  rw [hbits j hj hja, BitVec.getLsbD_xor, BitVec.getLsbD_intMin]
  by_cases hcond : j + 1 = a.length
  · rw [if_pos hcond, pEvalLit_not, hAj j hja]
    simp [show j + 1 = w by omega]
  · rw [if_neg hcond, hAj j hja]
    simp [show ¬(j + 1 = w) by omega]

/- ══════════════ SIGNED COMPARISONS ══════════════ -/

/-- **`blast_slt` implements signed `<`, for every width `w > 0`**: the
    returned literal evaluates to `A.slt B` (MSB-flip order embedding on top
    of the proven `blast_ult`). -/
theorem blast_slt_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length = b.val.length)
    (hcap : aig.nodes.val.length + 9 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (hw : 0 < w) (A B : BitVec w) :
    blast_slt aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          pEvalLit vals.val p.1 = A.slt B ⦄ ⦄ := by
  unfold blast_slt
  step with (flip_sign_spec a) as ⟨fa, hfa1, hfa2⟩
  step with (flip_sign_spec b) as ⟨fb, hfb1, hfb2⟩
  have hda : (alloc.vec.Vec.deref fa).val = fa.val := rfl
  have hdb : (alloc.vec.Vec.deref fb).val = fb.val := rfl
  have hfarng : ∀ l ∈ (alloc.vec.Vec.deref fa).val,
      l.node.val < aig.nodes.val.length := by
    rw [hda]
    intro l hl
    obtain ⟨j, hj, rfl⟩ := List.getElem_of_mem hl
    have hnode : (fa.val[j]'hj).node = (a.val[j]'(by omega)).node := by
      rw [hfa2 j hj (by omega)]
      split <;> rfl
    rw [hnode]
    exact ha _ (List.getElem_mem _)
  have hfbrng : ∀ l ∈ (alloc.vec.Vec.deref fb).val,
      l.node.val < aig.nodes.val.length := by
    rw [hdb]
    intro l hl
    obtain ⟨j, hj, rfl⟩ := List.getElem_of_mem hl
    have hnode : (fb.val[j]'hj).node = (b.val[j]'(by omega)).node := by
      rw [hfb2 j hj (by omega)]
      split <;> rfl
    rw [hnode]
    exact hb _ (List.getElem_mem _)
  apply WP.spec_mono (blast_ult_bitvec aig (alloc.vec.Vec.deref fa)
    (alloc.vec.Vec.deref fb) (by rw [hda, hdb]; omega)
    (by rw [hda]; omega) hfarng hfbrng hne h0
    (A ^^^ BitVec.intMin w) (B ^^^ BitVec.intMin w))
  rintro ⟨lt, aig1⟩ hsim
  intro inputs hwf
  apply WP.spec_mono (hsim inputs hwf)
  intro vals hval hA hB
  rw [hval (by rw [hda]; exact hA.flip_sign hfa1 hfa2)
    (by rw [hdb]; exact hB.flip_sign hfb1 hfb2)]
  exact xor_intMin_lt_eq_slt hw A B

/-- **`blast_sle` implements signed `≤`, for every width `w > 0`**:
    `A ≤ₛ B = ¬(B <ₛ A)`. -/
theorem blast_sle_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length = b.val.length)
    (hcap : aig.nodes.val.length + 9 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (hw : 0 < w) (A B : BitVec w) :
    blast_sle aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          pEvalLit vals.val p.1 = A.sle B ⦄ ⦄ := by
  unfold blast_sle
  step with (blast_slt_bitvec aig b a (by omega) (by omega) hb ha hne h0 hw B A)
    as ⟨lt, aig1, hsim⟩
  step with (lit_not_spec lt) as ⟨l, hl⟩
  intro inputs hwf
  apply WP.spec_mono (hsim inputs hwf)
  intro vals hval hA hB
  rw [hl, pEvalLit_not, hval hB hA, ← BitVec.sle_eq_not_slt]

/-- **`blast_sgt` implements signed `>`, for every width `w > 0`**:
    the returned literal evaluates to `B.slt A`. -/
theorem blast_sgt_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length = b.val.length)
    (hcap : aig.nodes.val.length + 9 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (hw : 0 < w) (A B : BitVec w) :
    blast_sgt aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          pEvalLit vals.val p.1 = B.slt A ⦄ ⦄ := by
  unfold blast_sgt
  apply WP.spec_mono
    (blast_slt_bitvec aig b a (by omega) (by omega) hb ha hne h0 hw B A)
  rintro ⟨lt, aig1⟩ hsim
  intro inputs hwf
  apply WP.spec_mono (hsim inputs hwf)
  intro vals hval hA hB
  exact hval hB hA

/-- **`blast_sge` implements signed `≥`, for every width `w > 0`**:
    `A ≥ₛ B = ¬(A <ₛ B) = B ≤ₛ A`. -/
theorem blast_sge_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length = b.val.length)
    (hcap : aig.nodes.val.length + 9 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (hw : 0 < w) (A B : BitVec w) :
    blast_sge aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          pEvalLit vals.val p.1 = B.sle A ⦄ ⦄ := by
  unfold blast_sge
  step with (blast_slt_bitvec aig a b hab hcap ha hb hne h0 hw A B)
    as ⟨lt, aig1, hsim⟩
  step with (lit_not_spec lt) as ⟨l, hl⟩
  intro inputs hwf
  apply WP.spec_mono (hsim inputs hwf)
  intro vals hval hA hB
  rw [hl, pEvalLit_not, hval hA hB, ← BitVec.sle_eq_not_slt]

/- ══════════════════════════ EQUALITY ══════════════════════════ -/

/-- Pure per-bit equality fold: `true` after 0 bits, then AND of per-bit
    XNORs (mirrors the `blast_eq` accumulator). -/
def pEqBits (vals : List Bool) (a b : List Lit) : Nat → Bool
  | 0 => true
  | i + 1 => pEqBits vals a b i
      && (pEvalLit vals (a.getD i dLit) == pEvalLit vals (b.getD i dLit))

/-- The gate structure `acc ∧ ¬(x ⊕ y)` is the equality fold step. -/
private theorem and_not_xor (c q x y : Bool) :
    ((c && q) && !(x ^^ y)) = (c && (q && (x == y))) := by
  cases c <;> cases q <;> cases x <;> cases y <;> rfl

/-- Append-monotonicity for the equality fold. -/
theorem pEqBits_stable {ns ns' : List Node} (hpre : ns <+: ns')
    {a b : List Lit}
    (ha : ∀ l ∈ a, l.node.val < ns.length)
    (hb : ∀ l ∈ b, l.node.val < ns.length)
    (inp : List Bool) (i : Nat) (hia : i ≤ a.length) (hib : i ≤ b.length) :
    pEqBits (pSim inp ns') a b i = pEqBits (pSim inp ns) a b i := by
  induction i with
  | zero => rfl
  | succ i ih =>
    have hia' : i < a.length := by omega
    have hib' : i < b.length := by omega
    simp only [pEqBits, getD_eq_getElem_of_lt hia', getD_eq_getElem_of_lt hib',
      ih (by omega) (by omega),
      pEvalLit_stable hpre _ (ha _ (List.getElem_mem hia')) inp,
      pEvalLit_stable hpre _ (hb _ (List.getElem_mem hib')) inp]

/-- On denoting words the equality fold decides bitvector equality
    (via `BitVec.eq_of_getLsbD_eq`). -/
theorem pEqBits_eq_decide {vals : List Bool} {a b : List Lit} {w : Nat}
    {A B : BitVec w} (hA : Denotes vals a w A) (hB : Denotes vals b w B) :
    pEqBits vals a b w = decide (A = B) := by
  obtain ⟨hal, hAj⟩ := hA
  obtain ⟨hbl, hBj⟩ := hB
  have key : ∀ i, i ≤ w →
      pEqBits vals a b i
        = decide (∀ j, j < i → A.getLsbD j = B.getLsbD j) := by
    intro i
    induction i with
    | zero => intro _; simp [pEqBits]
    | succ i ih =>
      intro hi
      have hia : i < a.length := by omega
      have hib : i < b.length := by omega
      simp only [pEqBits]
      rw [ih (by omega), getD_eq_getElem_of_lt hia,
        getD_eq_getElem_of_lt hib, hAj i hia, hBj i hib,
        decide_eq_decide.mpr (Nat.forall_lt_succ_right
          (p := fun j => A.getLsbD j = B.getLsbD j)), Bool.decide_and]
      congr 1
  rw [key w (Nat.le_refl w), decide_eq_decide]
  exact ⟨fun h => BitVec.eq_of_getLsbD_eq h, fun h j _ => by rw [h]⟩

/-- Loop invariant of `blast_eq` after `i` processed bits: 4 gates per bit
    (three for the XOR gadget, one for the accumulating AND), the original
    AIG is a prefix (nothing existing was touched), well-formedness is
    preserved, and the accumulator literal evaluates — under the CURRENT
    aig — to the initial literal's value AND-ed with the equality fold of
    the first `i` bits (operand values under the ORIGINAL aig). -/
def EqInv (aig : Aig) (a b : Slice Lit) (cin : Lit)
    (aig1 : Aig) (acc1 : Lit) (i : Nat) : Prop :=
  i ≤ a.val.length ∧
  aig1.nodes.val.length = aig.nodes.val.length + 4 * i ∧
  aig.nodes.val <+: aig1.nodes.val ∧
  (∀ L, AigWF aig.nodes.val L → AigWF aig1.nodes.val L) ∧
  acc1.node.val < aig1.nodes.val.length ∧
  ∀ inp : List Bool,
    pEvalLit (pSim inp aig1.nodes.val) acc1
      = (pEvalLit (pSim inp aig.nodes.val) cin
         && pEqBits (pSim inp aig.nodes.val) a.val b.val i)

theorem blast_eq_loop_spec (aig : Aig) (a b : Slice Lit) (cin : Lit)
    (w : Std.Usize) (hw : w.val = a.val.length)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + 4 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hcin : cin.node.val < aig.nodes.val.length) :
    blast_eq_loop aig a b cin w 0#usize ⦃ q =>
      EqInv aig a b cin q.2 q.1 a.val.length ⦄ := by
  unfold blast_eq_loop
  apply loop.spec_decr_nat
    (measure := fun (s : Aig × Lit × Std.Usize) => a.val.length - s.2.2.val)
    (inv := fun (s : Aig × Lit × Std.Usize) =>
      EqInv aig a b cin s.1 s.2.1 s.2.2.val)
  · rintro ⟨aig1, acc1, i⟩ hinv
    obtain ⟨hile, hlen1, hpre1, hwf1, hacc, hsem⟩ := hinv
    dsimp only at hile hlen1 hpre1 hwf1 hacc hsem
    unfold blast_eq_loop.body
    dsimp only
    split
    · rename_i hlt
      have hia : i.val < a.val.length := by scalar_tac
      have hib : i.val < b.val.length := by omega
      step as ⟨la, hla⟩
      step as ⟨lb, hlb⟩
      have hla' : la.node.val < aig1.nodes.val.length := by
        have h1 := ha la (by rw [hla]; exact List.getElem_mem _)
        have h2 := hpre1.length_le
        omega
      have hlb' : lb.node.val < aig1.nodes.val.length := by
        have h1 := hb lb (by rw [hlb]; exact List.getElem_mem _)
        have h2 := hpre1.length_le
        omega
      step with (push_xor_gadget aig1 la lb (by omega) hla' hlb') as
        ⟨x, aigA, hx1, hx2, hx3, hx4, hx5⟩
      step with (lit_not_spec x) as ⟨beq, hbeq⟩
      have hbeq' : beq.node.val < aigA.nodes.val.length := by
        rw [hbeq]
        exact hx3
      have haccA : acc1.node.val < aigA.nodes.val.length := by omega
      step with (push_and_gadget aigA acc1 beq (by omega) haccA hbeq') as
        ⟨acc2, aigB, hB1, hB2, hB3, hB4, hB5⟩
      step as ⟨i1, hi1⟩
      refine ⟨⟨by scalar_tac, by scalar_tac, hpre1.trans (hx2.trans hB2),
        fun L hL => hB4 L (hx4 L (hwf1 L hL)), hB3, ?_⟩, by scalar_tac⟩
      intro inp
      rw [hi1, hB5 inp, pEvalLit_stable hx2 acc1 hacc inp, hsem inp, hbeq,
        pEvalLit_not, hx5 inp, hla, hlb,
        pEvalLit_stable hpre1 _ (ha _ (List.getElem_mem hia)) inp,
        pEvalLit_stable hpre1 _ (hb _ (List.getElem_mem hib)) inp]
      simp only [pEqBits, getD_eq_getElem_of_lt hia, getD_eq_getElem_of_lt hib]
      exact and_not_xor _ _ _ _
    · rename_i hge
      have hieq : i.val = a.val.length := by scalar_tac
      rw [← hieq]
      exact ⟨hile, hlen1, hpre1, hwf1, hacc, hsem⟩
  · exact ⟨Nat.zero_le _, by simp, List.prefix_refl _, fun _ h => h, hcin,
      fun inp => by simp [pEqBits]⟩

/-- **`blast_eq` implements bitvector equality, for every width `w`**: the
    returned literal evaluates to `decide (A = B)`. -/
theorem blast_eq_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + 4 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (A B : BitVec w) :
    blast_eq aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          pEvalLit vals.val p.1 = decide (A = B) ⦄ ⦄ := by
  unfold blast_eq
  step with lit_true_spec as ⟨acc, hacc⟩
  simp only [hacc]
  have hcin : ({ node := 0#usize, neg := true } : Lit).node.val
      < aig.nodes.val.length := by scalar_tac
  apply WP.spec_mono (blast_eq_loop_spec aig a b _ (Slice.len a)
    (by scalar_tac) hab hcap ha hb hcin)
  rintro ⟨lres, aig1⟩ hinv
  obtain ⟨_, hlen, hpre, hwf, haccr, hsem⟩ := hinv
  intro inputs hwf'
  apply WP.spec_mono (simulate_spec aig1 inputs (hwf _ hwf'))
  intro vals hv hA hB
  rw [hv] at hA hB ⊢
  rw [hsem inputs.val, pEvalLit_node_zero hne h0 inputs.val true,
    Bool.true_and,
    ← pEqBits_stable hpre ha hb inputs.val a.val.length (Nat.le_refl _)
      (by omega),
    show a.val.length = w from hA.1]
  exact pEqBits_eq_decide hA hB

/-- **`blast_ne` implements bitvector disequality, for every width `w`**:
    the returned literal evaluates to `decide (A ≠ B)`. -/
theorem blast_ne_bitvec (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length + 4 * a.val.length ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (A B : BitVec w) :
    blast_ne aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          pEvalLit vals.val p.1 = decide (A ≠ B) ⦄ ⦄ := by
  unfold blast_ne
  step with (blast_eq_bitvec aig a b hab hcap ha hb hne h0 A B) as
    ⟨eq, aig1, hsim⟩
  step with (lit_not_spec eq) as ⟨l, hl⟩
  intro inputs hwf
  apply WP.spec_mono (hsim inputs hwf)
  intro vals hval hA hB
  rw [hl, pEvalLit_not, hval hA hB, ← decide_not]

/- ══════════════════════════ MUX / ITE ══════════════════════════ -/

/-- Gadget spec for `push_mux` (three gates:
    `mux = (sel ∧ t) ∨ (¬sel ∧ e)`): the output literal evaluates to the
    if-then-else of the input literals' values (under the ORIGINAL aig). -/
theorem push_mux_gadget (aig : Aig) (sel t e : Lit)
    (hcap : aig.nodes.val.length + 3 ≤ Usize.max)
    (hs : sel.node.val < aig.nodes.val.length)
    (ht : t.node.val < aig.nodes.val.length)
    (he : e.node.val < aig.nodes.val.length) :
    push_mux aig sel t e ⦃ p =>
      p.2.nodes.val.length = aig.nodes.val.length + 3 ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.1.node.val < p.2.nodes.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ inp : List Bool,
        pEvalLit (pSim inp p.2.nodes.val) p.1
          = if pEvalLit (pSim inp aig.nodes.val) sel
            then pEvalLit (pSim inp aig.nodes.val) t
            else pEvalLit (pSim inp aig.nodes.val) e) ⦄ := by
  unfold push_mux
  step with (push_and_gadget aig sel t (by omega) hs ht) as
    ⟨tb, aig1, h11, h12, h13, h14, h15⟩
  step with (lit_not_spec sel) as ⟨ns, hns⟩
  have hnsnode : ns.node = sel.node := by rw [hns]
  have hns' : ns.node.val < aig1.nodes.val.length := by
    rw [hnsnode]
    omega
  have he1 : e.node.val < aig1.nodes.val.length := by omega
  step with (push_and_gadget aig1 ns e (by omega) hns' he1) as
    ⟨eb, aig2, h21, h22, h23, h24, h25⟩
  have htb2 : tb.node.val < aig2.nodes.val.length := by omega
  apply WP.spec_mono (push_or_gadget aig2 tb eb (by omega) htb2 h23)
  rintro ⟨g, aig3⟩ ⟨h31, h32, h33, h34, h35⟩
  refine ⟨by omega, h12.trans (h22.trans h32), h33,
    fun L hL => h34 L (h24 L (h14 L hL)), fun inp => ?_⟩
  rw [h35 inp, pEvalLit_stable h22 tb h13 inp, h15 inp, h25 inp, hns,
    pEvalLit_not, pEvalLit_stable h12 sel hs inp,
    pEvalLit_stable h12 e he inp]
  cases pEvalLit (pSim inp aig.nodes.val) sel <;> simp

/-- Loop invariant of `blast_ite` after `i` processed bits (mirrors
    `BlastInv`, with the select literal threaded through): 3 gates per bit,
    the original AIG is a prefix, and every emitted output literal evaluates
    — under the CURRENT aig — to the mux of the corresponding operand bits
    (values under the ORIGINAL aig). -/
def IteInv (aig : Aig) (cnd : Lit) (t e : Slice Lit)
    (aig1 : Aig) (out1 : alloc.vec.Vec Lit) (i : Nat) : Prop :=
  i ≤ t.val.length ∧
  aig1.nodes.val.length = aig.nodes.val.length + 3 * i ∧
  aig.nodes.val <+: aig1.nodes.val ∧
  (∀ L, AigWF aig.nodes.val L → AigWF aig1.nodes.val L) ∧
  out1.val.length = i ∧
  (∀ l ∈ out1.val, l.node.val < aig1.nodes.val.length) ∧
  ∀ (inp : List Bool) (j : Nat) (hj1 : j < out1.val.length)
    (hj2 : j < t.val.length) (hj3 : j < e.val.length),
    pEvalLit (pSim inp aig1.nodes.val) out1.val[j]
      = if pEvalLit (pSim inp aig.nodes.val) cnd
        then pEvalLit (pSim inp aig.nodes.val) t.val[j]
        else pEvalLit (pSim inp aig.nodes.val) e.val[j]

/-- Preservation: pushing one mux gadget for bit `i` and appending its
    output literal re-establishes the invariant at `i + 1`. -/
theorem IteInv.step {aig : Aig} {cnd : Lit} {t e : Slice Lit}
    {aig1 aig2 : Aig} {out1 out2 : alloc.vec.Vec Lit} {g : Lit} {i : Nat}
    (h : IteInv aig cnd t e aig1 out1 i)
    (hit : i < t.val.length) (hie : i < e.val.length)
    (hcnd : cnd.node.val < aig.nodes.val.length)
    (ht : ∀ l ∈ t.val, l.node.val < aig.nodes.val.length)
    (he : ∀ l ∈ e.val, l.node.val < aig.nodes.val.length)
    (hglen : aig2.nodes.val.length = aig1.nodes.val.length + 3)
    (hgpre : aig1.nodes.val <+: aig2.nodes.val)
    (hgnode : g.node.val < aig2.nodes.val.length)
    (hgwf : ∀ L, AigWF aig1.nodes.val L → AigWF aig2.nodes.val L)
    (hgsem : ∀ inp : List Bool,
      pEvalLit (pSim inp aig2.nodes.val) g
        = if pEvalLit (pSim inp aig1.nodes.val) cnd
          then pEvalLit (pSim inp aig1.nodes.val) (t.val[i]'hit)
          else pEvalLit (pSim inp aig1.nodes.val) (e.val[i]'hie))
    (hout2 : out2.val = out1.val ++ [g]) :
    IteInv aig cnd t e aig2 out2 (i + 1) := by
  obtain ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩ := h
  refine ⟨by omega, by omega, hpre1.trans hgpre,
    fun L hL => hgwf L (hwf1 L hL), by rw [hout2]; simp [holen], ?_, ?_⟩
  · intro l hl
    rw [hout2] at hl
    rcases List.mem_append.mp hl with h' | h'
    · exact Nat.lt_of_lt_of_le (horng l h') hgpre.length_le
    · simp only [List.mem_singleton] at h'
      subst h'
      exact hgnode
  · intro inp j hj1 hj2 hj3
    have hj1' : j < out1.val.length + 1 := by
      rw [hout2] at hj1
      simpa using hj1
    rcases Nat.lt_or_ge j out1.val.length with hji | hji
    · have hgetj : out2.val[j]'hj1 = out1.val[j]'hji := by
        simp only [hout2]
        exact List.getElem_append_left hji
      rw [hgetj, pEvalLit_stable hgpre _ (horng _ (List.getElem_mem _)) inp]
      exact hsem inp j hji hj2 hj3
    · have hjeq : j = i := by omega
      subst hjeq
      have hgetj : out2.val[j]'hj1 = g := by
        simp only [hout2]
        exact List.getElem_concat_length (by omega) _
      rw [hgetj, hgsem inp, pEvalLit_stable hpre1 _ hcnd inp,
        pEvalLit_stable hpre1 _ (ht _ (List.getElem_mem _)) inp,
        pEvalLit_stable hpre1 _ (he _ (List.getElem_mem _)) inp]

/-- `blast_ite` appends one mux gadget (3 gates) per bit; every output
    literal evaluates (under the extended aig) to the mux of the
    corresponding operand bits' values (under the original aig). Total
    correctness: no failure. -/
theorem blast_ite_spec (aig : Aig) (cnd : Lit) (t e : Slice Lit)
    (hte : t.val.length ≤ e.val.length)
    (hcap : aig.nodes.val.length + 3 * t.val.length ≤ Usize.max)
    (hcnd : cnd.node.val < aig.nodes.val.length)
    (ht : ∀ l ∈ t.val, l.node.val < aig.nodes.val.length)
    (he : ∀ l ∈ e.val, l.node.val < aig.nodes.val.length) :
    blast_ite aig cnd t e ⦃ p =>
      p.1.val.length = t.val.length ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.2.nodes.val.length = aig.nodes.val.length + 3 * t.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ l ∈ p.1.val, l.node.val < p.2.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj1 : j < p.1.val.length)
        (hj2 : j < t.val.length) (hj3 : j < e.val.length),
        pEvalLit (pSim inp p.2.nodes.val) p.1.val[j]
          = if pEvalLit (pSim inp aig.nodes.val) cnd
            then pEvalLit (pSim inp aig.nodes.val) t.val[j]
            else pEvalLit (pSim inp aig.nodes.val) e.val[j] ⦄ := by
  unfold blast_ite blast_ite_loop
  apply loop.spec_decr_nat
    (measure := fun (s : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      t.val.length - s.2.2.val)
    (inv := fun (s : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      IteInv aig cnd t e s.1 s.2.1 s.2.2.val)
  · rintro ⟨aig1, out1, i⟩ hinv
    obtain ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩ := hinv
    dsimp only at hile hlen1 hpre1 hwf1 holen horng hsem
    unfold blast_ite_loop.body
    dsimp only
    split
    · rename_i hlt
      have hit : i.val < t.val.length := by scalar_tac
      have hie : i.val < e.val.length := by omega
      step as ⟨lt', hlt'⟩
      step as ⟨le', hle'⟩
      have hcnd1 : cnd.node.val < aig1.nodes.val.length := by
        have := hpre1.length_le
        omega
      have hlt'' : lt'.node.val < aig1.nodes.val.length := by
        have h1 := ht lt' (by rw [hlt']; exact List.getElem_mem _)
        have h2 := hpre1.length_le
        omega
      have hle'' : le'.node.val < aig1.nodes.val.length := by
        have h1 := he le' (by rw [hle']; exact List.getElem_mem _)
        have h2 := hpre1.length_le
        omega
      step with (push_mux_gadget aig1 cnd lt' le' (by omega) hcnd1 hlt''
        hle'') as ⟨g, aig2, hg1, hg2, hg3, hg4, hg5⟩
      have houtcap : out1.val.length < Usize.max := by
        have := t.length_ineq
        omega
      step as ⟨out2, hout2⟩
      step as ⟨i1, hi1⟩
      refine ⟨?_, by scalar_tac⟩
      rw [hi1]
      subst hlt' hle'
      exact IteInv.step ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩
        hit hie hcnd ht he hg1 hg2 hg3 hg4 hg5 hout2
    · rename_i hge
      have hieq : i.val = t.val.length := by scalar_tac
      refine ⟨by dsimp only; omega, hpre1, by dsimp only; omega, hwf1,
        horng, ?_⟩
      intro inp j hj1 hj2 hj3
      exact hsem inp j hj1 hj2 hj3
  · exact ⟨Nat.zero_le _, by simp, List.prefix_refl _, fun _ h => h, by simp,
      by simp, fun _ j hj1 _ _ => by simp at hj1⟩

/-- **`blast_ite` implements the bitvector multiplexer, for every width
    `w`**: if the operand words denote `A` and `B` under the post-blast
    simulation and the select literal evaluates to `c`, the output word
    denotes `if c then A else B`. -/
theorem blast_ite_bitvec (aig : Aig) (cnd : Lit) (t e : Slice Lit)
    (hte : t.val.length ≤ e.val.length)
    (hcap : aig.nodes.val.length + 3 * t.val.length ≤ Usize.max)
    (hcnd : cnd.node.val < aig.nodes.val.length)
    (ht : ∀ l ∈ t.val, l.node.val < aig.nodes.val.length)
    (he : ∀ l ∈ e.val, l.node.val < aig.nodes.val.length)
    {w : Nat} (A B : BitVec w) :
    blast_ite aig cnd t e ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val t.val w A → Denotes vals.val e.val w B →
          Denotes vals.val p.1.val w
            (if pEvalLit vals.val cnd then A else B) ⦄ ⦄ := by
  apply WP.spec_mono (blast_ite_spec aig cnd t e hte hcap hcnd ht he)
  rintro ⟨out, aig'⟩ ⟨h1, h2, h3, h4, h5, h6⟩
  intro inputs hwf
  apply WP.spec_mono (simulate_spec aig' inputs (h4 _ hwf))
  intro vals hv hA hB
  rw [hv] at hA hB ⊢
  obtain ⟨hal, hAj⟩ := hA
  obtain ⟨hbl, hBj⟩ := hB
  refine ⟨by omega, fun j hj => ?_⟩
  have hja : j < t.val.length := by omega
  have hjb : j < e.val.length := by omega
  rw [h6 inputs.val j hj hja hjb,
    ← pEvalLit_stable h2 _ (ht _ (List.getElem_mem hja)) inputs.val,
    ← pEvalLit_stable h2 _ (he _ (List.getElem_mem hjb)) inputs.val,
    hAj j hja, hBj j hjb, pEvalLit_stable h2 cnd hcnd inputs.val]
  cases pEvalLit (pSim inputs.val aig.nodes.val) cnd <;> simp

/- ══════════════ STRUCTURAL RULES (GATE-FREE) ══════════════ -/

/-- `blast_extract` copies the literal slice `[lo, hi]`: pure list slicing,
    no gates. -/
theorem blast_extract_spec (a : Slice Lit) (hi lo : Std.Usize)
    (hlo : lo.val ≤ hi.val) (hhi : hi.val < a.val.length) :
    blast_extract a hi lo ⦃ out =>
      out.val = (a.val.drop lo.val).take (hi.val + 1 - lo.val) ⦄ := by
  unfold blast_extract blast_extract_loop
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      hi.val + 1 - s.2.val)
    (inv := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      lo.val ≤ s.2.val ∧ s.2.val ≤ hi.val + 1 ∧
      s.1.val = (a.val.drop lo.val).take (s.2.val - lo.val))
  · rintro ⟨out1, i⟩ ⟨hloi, hile, hval⟩
    dsimp only at hloi hile hval
    unfold blast_extract_loop.body
    dsimp only
    split
    · rename_i hle
      have hile' : i.val ≤ hi.val := by scalar_tac
      have hia : i.val < a.val.length := by omega
      step as ⟨l, hl⟩
      have hocap : out1.val.length < Usize.max := by
        have := a.length_ineq
        rw [hval]
        simp only [List.length_take, List.length_drop]
        omega
      step as ⟨out2, hout2⟩
      step as ⟨i1, hi1⟩
      refine ⟨by scalar_tac, by scalar_tac, ?_, by scalar_tac⟩
      have hidx : i.val - lo.val < (a.val.drop lo.val).length := by
        simp only [List.length_drop]
        omega
      rw [hi1, hout2, hval, hl,
        show i.val + 1 - lo.val = (i.val - lo.val) + 1 by omega,
        List.take_add_one, List.getElem?_eq_getElem hidx]
      simp [List.getElem_drop, show lo.val + (i.val - lo.val) = i.val by omega]
    · rename_i hgt
      have hieq : i.val = hi.val + 1 := by scalar_tac
      have hfin : out1.val = (a.val.drop lo.val).take (hi.val + 1 - lo.val) := by
        rw [hval, hieq]
      exact hfin
  · exact ⟨Nat.le_refl _, by show lo.val ≤ hi.val + 1; omega, by simp⟩

/-- **`blast_extract` implements `BitVec.extractLsb`, for every width `w`**:
    if the input word denotes `A`, the output word (width `hi - lo + 1`)
    denotes `A.extractLsb hi lo`. -/
theorem blast_extract_bitvec (a : Slice Lit) (hi lo : Std.Usize)
    (hlo : lo.val ≤ hi.val) (hhi : hi.val < a.val.length)
    {w : Nat} (A : BitVec w) :
    blast_extract a hi lo ⦃ out =>
      ∀ vals : List Bool, Denotes vals a.val w A →
        Denotes vals out.val (hi.val - lo.val + 1)
          (A.extractLsb hi.val lo.val) ⦄ := by
  apply WP.spec_mono (blast_extract_spec a hi lo hlo hhi)
  intro out hout vals hA
  obtain ⟨hal, hAj⟩ := hA
  have holen : out.val.length = hi.val - lo.val + 1 := by
    rw [hout]
    simp only [List.length_take, List.length_drop]
    omega
  refine ⟨holen, fun j hj => ?_⟩
  have hjlt : j < hi.val - lo.val + 1 := by omega
  have hidx : lo.val + j < a.val.length := by omega
  have hgetj : out.val[j]'hj = a.val[lo.val + j]'hidx := by
    simp only [hout]
    simp [List.getElem_take, List.getElem_drop]
  rw [hgetj, hAj _ hidx, BitVec.getLsbD_extractLsb]
  simp [hjlt]

/-- First `blast_concat` loop: appends the whole low word to `out`. -/
theorem blast_concat_loop0_spec (lo_part : Slice Lit)
    (out : alloc.vec.Vec Lit) (w : Std.Usize)
    (hw : w.val = lo_part.val.length)
    (hcap : out.val.length + lo_part.val.length ≤ Usize.max) :
    blast_concat_loop0 lo_part out w 0#usize ⦃ r =>
      r.val = out.val ++ lo_part.val ⦄ := by
  unfold blast_concat_loop0
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      lo_part.val.length - s.2.val)
    (inv := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      s.2.val ≤ lo_part.val.length ∧
      s.1.val = out.val ++ lo_part.val.take s.2.val)
  · rintro ⟨out1, i⟩ ⟨hle, hval⟩
    dsimp only at hle hval
    unfold blast_concat_loop0.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < lo_part.val.length := by scalar_tac
      step as ⟨l, hl⟩
      have hocap : out1.val.length < Usize.max := by
        rw [hval]
        simp only [List.length_append, List.length_take]
        omega
      step as ⟨out2, hout2⟩
      step as ⟨i1, hi1⟩
      refine ⟨by scalar_tac, ?_, by scalar_tac⟩
      rw [hi1, hout2, hval, hl, List.take_add_one,
        List.getElem?_eq_getElem hilt]
      simp
    · rename_i hge
      have hieq : i.val = lo_part.val.length := by scalar_tac
      have hfin : out1.val = out.val ++ lo_part.val := by
        rw [hval, hieq, List.take_of_length_le (by simp)]
      exact hfin
  · exact ⟨Nat.zero_le _, by simp⟩

/-- Second `blast_concat` loop: appends the whole high word to `out`. -/
theorem blast_concat_loop1_spec (hi_part : Slice Lit)
    (out : alloc.vec.Vec Lit) (w : Std.Usize)
    (hw : w.val = hi_part.val.length)
    (hcap : out.val.length + hi_part.val.length ≤ Usize.max) :
    blast_concat_loop1 hi_part out w 0#usize ⦃ r =>
      r.val = out.val ++ hi_part.val ⦄ := by
  unfold blast_concat_loop1
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      hi_part.val.length - s.2.val)
    (inv := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      s.2.val ≤ hi_part.val.length ∧
      s.1.val = out.val ++ hi_part.val.take s.2.val)
  · rintro ⟨out1, j⟩ ⟨hle, hval⟩
    dsimp only at hle hval
    unfold blast_concat_loop1.body
    dsimp only
    split
    · rename_i hlt
      have hjlt : j.val < hi_part.val.length := by scalar_tac
      step as ⟨l, hl⟩
      have hocap : out1.val.length < Usize.max := by
        rw [hval]
        simp only [List.length_append, List.length_take]
        omega
      step as ⟨out2, hout2⟩
      step as ⟨j1, hj1⟩
      refine ⟨by scalar_tac, ?_, by scalar_tac⟩
      rw [hj1, hout2, hval, hl, List.take_add_one,
        List.getElem?_eq_getElem hjlt]
      simp
    · rename_i hge
      have hjeq : j.val = hi_part.val.length := by scalar_tac
      have hfin : out1.val = out.val ++ hi_part.val := by
        rw [hval, hjeq, List.take_of_length_le (by simp)]
      exact hfin
  · exact ⟨Nat.zero_le _, by simp⟩

/-- `blast_concat` is LSB-first concatenation: low word first, then the
    high word. Pure list append, no gates. -/
theorem blast_concat_spec (hi_part lo_part : Slice Lit)
    (hcap : lo_part.val.length + hi_part.val.length ≤ Usize.max) :
    blast_concat hi_part lo_part ⦃ out =>
      out.val = lo_part.val ++ hi_part.val ⦄ := by
  unfold blast_concat
  step with (blast_concat_loop0_spec lo_part (alloc.vec.Vec.new Lit)
    (Slice.len lo_part) (by scalar_tac) (by simp; omega)) as ⟨o1, ho1⟩
  apply WP.spec_mono (blast_concat_loop1_spec hi_part o1
    (Slice.len hi_part) (by scalar_tac) (by rw [ho1]; simp; omega))
  intro r hr
  rw [hr, ho1]
  simp

/-- **`blast_concat` implements `BitVec.append` (SMT-LIB `concat`), for all
    widths**: if the high word denotes `A : BitVec wh` and the low word
    denotes `B : BitVec wl`, the output word (LSB-first: low part first)
    denotes `A ++ B : BitVec (wh + wl)`. -/
theorem blast_concat_bitvec (hi_part lo_part : Slice Lit)
    (hcap : lo_part.val.length + hi_part.val.length ≤ Usize.max)
    {wh wl : Nat} (A : BitVec wh) (B : BitVec wl) :
    blast_concat hi_part lo_part ⦃ out =>
      ∀ vals : List Bool,
        Denotes vals hi_part.val wh A → Denotes vals lo_part.val wl B →
        Denotes vals out.val (wh + wl) (A ++ B) ⦄ := by
  apply WP.spec_mono (blast_concat_spec hi_part lo_part hcap)
  intro out hout vals hA hB
  obtain ⟨hhl, hHj⟩ := hA
  obtain ⟨hll, hLj⟩ := hB
  have holen : out.val.length = wh + wl := by
    rw [hout]
    simp only [List.length_append]
    omega
  refine ⟨holen, fun j hj => ?_⟩
  rw [BitVec.getLsbD_append]
  rcases Nat.lt_or_ge j wl with hjl | hjl
  · have hgetj : out.val[j]'hj = lo_part.val[j]'(by omega) := by
      simp only [hout]
      exact List.getElem_append_left (by omega)
    rw [hgetj, hLj j (by omega), if_pos hjl]
  · have hgetj : out.val[j]'hj
        = hi_part.val[j - lo_part.val.length]'(by omega) := by
      simp only [hout]
      exact List.getElem_append_right (by omega)
    rw [hgetj, hHj _ (by omega), if_neg (by omega), hll]

/-- First `blast_zero_ext` loop: appends the whole input word to `out`. -/
theorem blast_zero_ext_loop0_spec (a : Slice Lit) (out : alloc.vec.Vec Lit)
    (w : Std.Usize) (hw : w.val = a.val.length)
    (hcap : out.val.length + a.val.length ≤ Usize.max) :
    blast_zero_ext_loop0 a out w 0#usize ⦃ r =>
      r.val = out.val ++ a.val ⦄ := by
  unfold blast_zero_ext_loop0
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      a.val.length - s.2.val)
    (inv := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      s.2.val ≤ a.val.length ∧
      s.1.val = out.val ++ a.val.take s.2.val)
  · rintro ⟨out1, i⟩ ⟨hle, hval⟩
    dsimp only at hle hval
    unfold blast_zero_ext_loop0.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < a.val.length := by scalar_tac
      step as ⟨l, hl⟩
      have hocap : out1.val.length < Usize.max := by
        rw [hval]
        simp only [List.length_append, List.length_take]
        omega
      step as ⟨out2, hout2⟩
      step as ⟨i1, hi1⟩
      refine ⟨by scalar_tac, ?_, by scalar_tac⟩
      rw [hi1, hout2, hval, hl, List.take_add_one,
        List.getElem?_eq_getElem hilt]
      simp
    · rename_i hge
      have hieq : i.val = a.val.length := by scalar_tac
      have hfin : out1.val = out.val ++ a.val := by
        rw [hval, hieq, List.take_of_length_le (by simp)]
      exact hfin
  · exact ⟨Nat.zero_le _, by simp⟩

/-- Second `blast_zero_ext` loop: appends `by1` constant-FALSE literals. -/
theorem blast_zero_ext_loop1_spec (by1 : Std.Usize) (out : alloc.vec.Vec Lit)
    (hcap : out.val.length + by1.val ≤ Usize.max) :
    blast_zero_ext_loop1 by1 out 0#usize ⦃ r =>
      r.val = out.val
        ++ List.replicate by1.val { node := 0#usize, neg := false } ⦄ := by
  unfold blast_zero_ext_loop1
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      by1.val - s.2.val)
    (inv := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      s.2.val ≤ by1.val ∧
      s.1.val = out.val
        ++ List.replicate s.2.val { node := 0#usize, neg := false })
  · rintro ⟨out1, j⟩ ⟨hle, hval⟩
    dsimp only at hle hval
    unfold blast_zero_ext_loop1.body
    dsimp only
    split
    · rename_i hlt
      have hjlt : j.val < by1.val := by scalar_tac
      step with lit_false_spec as ⟨l, hl⟩
      have hocap : out1.val.length < Usize.max := by
        rw [hval]
        simp only [List.length_append, List.length_replicate]
        omega
      step as ⟨out2, hout2⟩
      step as ⟨j1, hj1⟩
      refine ⟨by scalar_tac, ?_, by scalar_tac⟩
      rw [hj1, hout2, hval, hl, List.replicate_succ']
      simp
    · rename_i hge
      have hjeq : j.val = by1.val := by scalar_tac
      have hfin : out1.val = out.val
          ++ List.replicate by1.val { node := 0#usize, neg := false } := by
        rw [hval, hjeq]
      exact hfin
  · exact ⟨Nat.zero_le _, by simp⟩

/-- `blast_zero_ext` appends `by1` constant-FALSE literals to the word. -/
theorem blast_zero_ext_spec (a : Slice Lit) (by1 : Std.Usize)
    (hcap : a.val.length + by1.val ≤ Usize.max) :
    blast_zero_ext a by1 ⦃ out =>
      out.val = a.val
        ++ List.replicate by1.val { node := 0#usize, neg := false } ⦄ := by
  unfold blast_zero_ext
  step with (blast_zero_ext_loop0_spec a (alloc.vec.Vec.new Lit)
    (Slice.len a) (by scalar_tac) (by simp; scalar_tac)) as ⟨o1, ho1⟩
  apply WP.spec_mono (blast_zero_ext_loop1_spec by1 o1
    (by rw [ho1]; simp; omega))
  intro r hr
  rw [hr, ho1]
  simp

/-- **`blast_zero_ext` implements `BitVec.setWidth` (zero extension), for
    every width `w`**: requires node 0 to be the constant-FALSE node (via
    the `pEvalLit vals lit_false = false` hypothesis, which
    `pEvalLit_node_zero` provides under any simulation of a well-formed
    aig). -/
theorem blast_zero_ext_bitvec (a : Slice Lit) (by1 : Std.Usize)
    (hcap : a.val.length + by1.val ≤ Usize.max)
    {w : Nat} (A : BitVec w) :
    blast_zero_ext a by1 ⦃ out =>
      ∀ vals : List Bool,
        pEvalLit vals { node := 0#usize, neg := false } = false →
        Denotes vals a.val w A →
        Denotes vals out.val (w + by1.val) (A.setWidth (w + by1.val)) ⦄ := by
  apply WP.spec_mono (blast_zero_ext_spec a by1 hcap)
  intro out hout vals h0 hA
  obtain ⟨hal, hAj⟩ := hA
  have holen : out.val.length = w + by1.val := by
    rw [hout]
    simp only [List.length_append, List.length_replicate]
    omega
  refine ⟨holen, fun j hj => ?_⟩
  rw [BitVec.getLsbD_setWidth]
  rcases Nat.lt_or_ge j a.val.length with hja | hja
  · have hgetj : out.val[j]'hj = a.val[j]'hja := by
      simp only [hout]
      exact List.getElem_append_left hja
    rw [hgetj, hAj j hja]
    simp [show j < w + by1.val by omega]
  · have hgetj : out.val[j]'hj = { node := 0#usize, neg := false } := by
      simp only [hout]
      rw [List.getElem_append_right hja]
      simp
    rw [hgetj, h0, BitVec.getLsbD_of_ge A j (by omega)]
    simp

/-- First `blast_sign_ext` loop: appends the whole input word to `out`. -/
theorem blast_sign_ext_loop0_spec (a : Slice Lit) (out : alloc.vec.Vec Lit)
    (w : Std.Usize) (hw : w.val = a.val.length)
    (hcap : out.val.length + a.val.length ≤ Usize.max) :
    blast_sign_ext_loop0 a out w 0#usize ⦃ r =>
      r.val = out.val ++ a.val ⦄ := by
  unfold blast_sign_ext_loop0
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      a.val.length - s.2.val)
    (inv := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      s.2.val ≤ a.val.length ∧
      s.1.val = out.val ++ a.val.take s.2.val)
  · rintro ⟨out1, i⟩ ⟨hle, hval⟩
    dsimp only at hle hval
    unfold blast_sign_ext_loop0.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < a.val.length := by scalar_tac
      step as ⟨l, hl⟩
      have hocap : out1.val.length < Usize.max := by
        rw [hval]
        simp only [List.length_append, List.length_take]
        omega
      step as ⟨out2, hout2⟩
      step as ⟨i1, hi1⟩
      refine ⟨by scalar_tac, ?_, by scalar_tac⟩
      rw [hi1, hout2, hval, hl, List.take_add_one,
        List.getElem?_eq_getElem hilt]
      simp
    · rename_i hge
      have hieq : i.val = a.val.length := by scalar_tac
      have hfin : out1.val = out.val ++ a.val := by
        rw [hval, hieq, List.take_of_length_le (by simp)]
      exact hfin
  · exact ⟨Nat.zero_le _, by simp⟩

/-- Second `blast_sign_ext` loop: appends `by1` copies of the sign
    literal. -/
theorem blast_sign_ext_loop1_spec (by1 : Std.Usize) (out : alloc.vec.Vec Lit)
    (sign : Lit) (hcap : out.val.length + by1.val ≤ Usize.max) :
    blast_sign_ext_loop1 by1 out sign 0#usize ⦃ r =>
      r.val = out.val ++ List.replicate by1.val sign ⦄ := by
  unfold blast_sign_ext_loop1
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      by1.val - s.2.val)
    (inv := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      s.2.val ≤ by1.val ∧
      s.1.val = out.val ++ List.replicate s.2.val sign)
  · rintro ⟨out1, j⟩ ⟨hle, hval⟩
    dsimp only at hle hval
    unfold blast_sign_ext_loop1.body
    dsimp only
    split
    · rename_i hlt
      have hjlt : j.val < by1.val := by scalar_tac
      have hocap : out1.val.length < Usize.max := by
        rw [hval]
        simp only [List.length_append, List.length_replicate]
        omega
      step as ⟨out2, hout2⟩
      step as ⟨j1, hj1⟩
      refine ⟨by scalar_tac, ?_, by scalar_tac⟩
      rw [hj1, hout2, hval, List.replicate_succ']
      simp
    · rename_i hge
      have hjeq : j.val = by1.val := by scalar_tac
      have hfin : out1.val = out.val ++ List.replicate by1.val sign := by
        rw [hval, hjeq]
      exact hfin
  · exact ⟨Nat.zero_le _, by simp⟩

/-- `blast_sign_ext` appends `by1` copies of the MSB literal to the word
    (requires a non-empty word, mirroring the blaster's `debug_assert`). -/
theorem blast_sign_ext_spec (a : Slice Lit) (by1 : Std.Usize)
    (hne : 0 < a.val.length)
    (hcap : a.val.length + by1.val ≤ Usize.max) :
    blast_sign_ext a by1 ⦃ out =>
      out.val = a.val
        ++ List.replicate by1.val (a.val[a.val.length - 1]'(by omega)) ⦄ := by
  unfold blast_sign_ext
  step with (blast_sign_ext_loop0_spec a (alloc.vec.Vec.new Lit)
    (Slice.len a) (by scalar_tac) (by simp; scalar_tac)) as ⟨o1, ho1⟩
  step as ⟨i, hi⟩
  have hival : i.val = a.val.length - 1 := by scalar_tac
  have hilt : i.val < a.val.length := by omega
  step as ⟨sign, hsign⟩
  apply WP.spec_mono (blast_sign_ext_loop1_spec by1 o1 sign
    (by rw [ho1]; simp; omega))
  intro r hr
  rw [hr, ho1, hsign]
  simp only [List.nil_append, hival]

/-- **`blast_sign_ext` implements `BitVec.signExtend`, for every width
    `w`** (non-empty input word): below `w` the bits are `A`'s, at and above
    `w` they are `A`'s MSB (`msb_eq_getLsbD_last`). -/
theorem blast_sign_ext_bitvec (a : Slice Lit) (by1 : Std.Usize)
    (hne : 0 < a.val.length)
    (hcap : a.val.length + by1.val ≤ Usize.max)
    {w : Nat} (A : BitVec w) :
    blast_sign_ext a by1 ⦃ out =>
      ∀ vals : List Bool, Denotes vals a.val w A →
        Denotes vals out.val (w + by1.val)
          (A.signExtend (w + by1.val)) ⦄ := by
  apply WP.spec_mono (blast_sign_ext_spec a by1 hne hcap)
  intro out hout vals hA
  obtain ⟨hal, hAj⟩ := hA
  have hw : 0 < w := by omega
  have holen : out.val.length = w + by1.val := by
    rw [hout]
    simp only [List.length_append, List.length_replicate]
    omega
  refine ⟨holen, fun j hj => ?_⟩
  rw [BitVec.getLsbD_signExtend]
  rcases Nat.lt_or_ge j a.val.length with hja | hja
  · have hgetj : out.val[j]'hj = a.val[j]'hja := by
      simp only [hout]
      exact List.getElem_append_left hja
    rw [hgetj, hAj j hja]
    simp [show j < w + by1.val by omega, show j < w by omega]
  · have hgetj : out.val[j]'hj = a.val[a.val.length - 1]'(by omega) := by
      simp only [hout]
      rw [List.getElem_append_right hja]
      simp
    rw [hgetj, hAj _ (by omega), BitVec.msb_eq_getLsbD_last,
      show a.val.length - 1 = w - 1 by omega]
    simp [show j < w + by1.val by omega, show ¬(j < w) by omega]

end blast_kernel.spec
