-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [blast_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace blast_kernel

/-- [blast_kernel::Lit]
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 21:0-24:1
    Visibility: public -/
structure Lit where
  node : Std.Usize
  neg : Bool

/-- [blast_kernel::{impl core::clone::Clone for blast_kernel::Lit}::clone]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 20:9-20:14
    Visibility: public -/
def Lit.Insts.CoreCloneClone.clone (self : Lit) : Result Lit := do
  ok self

/-- Trait implementation: [blast_kernel::{impl core::clone::Clone for blast_kernel::Lit}]
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 20:9-20:14 -/
@[reducible]
def Lit.Insts.CoreCloneClone : core.clone.Clone Lit := {
  clone := Lit.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [blast_kernel::{impl core::marker::Copy for blast_kernel::Lit}]
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 20:16-20:20 -/
@[reducible]
def Lit.Insts.CoreMarkerCopy : core.marker.Copy Lit := {
  cloneInst := Lit.Insts.CoreCloneClone
}

/-- [blast_kernel::Node]
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 29:0-33:1
    Visibility: public -/
@[discriminant isize]
inductive Node where
| False : Node
| Input : Std.Usize → Node
| And : Lit → Lit → Node

/-- [blast_kernel::{impl core::clone::Clone for blast_kernel::Node}::clone]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 28:9-28:14
    Visibility: public -/
def Node.Insts.CoreCloneClone.clone (self : Node) : Result Node := do
  ok self

/-- Trait implementation: [blast_kernel::{impl core::clone::Clone for blast_kernel::Node}]
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 28:9-28:14 -/
@[reducible]
def Node.Insts.CoreCloneClone : core.clone.Clone Node := {
  clone := Node.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [blast_kernel::{impl core::marker::Copy for blast_kernel::Node}]
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 28:16-28:20 -/
@[reducible]
def Node.Insts.CoreMarkerCopy : core.marker.Copy Node := {
  cloneInst := Node.Insts.CoreCloneClone
}

/-- [blast_kernel::Aig]
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 37:0-39:1
    Visibility: public -/
structure Aig where
  nodes : alloc.vec.Vec Node

/-- [blast_kernel::lit_false]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 42:0-47:1
    Visibility: public -/
def lit_false : Result Lit := do
  ok { node := 0#usize, neg := false }

/-- [blast_kernel::lit_true]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 50:0-52:1
    Visibility: public -/
def lit_true : Result Lit := do
  ok { node := 0#usize, neg := true }

/-- [blast_kernel::lit_not]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 55:0-60:1
    Visibility: public -/
def lit_not (l : Lit) : Result Lit := do
  ok { l with neg := (¬ l.neg) }

/-- [blast_kernel::aig_new]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 68:0-72:1
    Visibility: public -/
def aig_new : Result Aig := do
  let nodes ← alloc.vec.Vec.push (alloc.vec.Vec.new Node) Node.False
  ok { nodes }

/-- [blast_kernel::push_input]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 75:0-82:1
    Visibility: public -/
def push_input (aig : Aig) (k : Std.Usize) : Result (Lit × Aig) := do
  let idx := alloc.vec.Vec.len aig.nodes
  let v ← alloc.vec.Vec.push aig.nodes (Node.Input k)
  ok ({ node := idx, neg := false }, { nodes := v })

/-- [blast_kernel::push_and]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 86:0-93:1
    Visibility: public -/
def push_and (aig : Aig) (x : Lit) (y : Lit) : Result (Lit × Aig) := do
  let idx := alloc.vec.Vec.len aig.nodes
  let v ← alloc.vec.Vec.push aig.nodes (Node.And x y)
  ok ({ node := idx, neg := false }, { nodes := v })

/-- [blast_kernel::push_or]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 96:0-99:1
    Visibility: public -/
def push_or (aig : Aig) (x : Lit) (y : Lit) : Result (Lit × Aig) := do
  let l ← lit_not x
  let l1 ← lit_not y
  let (na, aig1) ← push_and aig l l1
  let l2 ← lit_not na
  ok (l2, aig1)

/-- [blast_kernel::push_xor]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 102:0-106:1
    Visibility: public -/
def push_xor (aig : Aig) (x : Lit) (y : Lit) : Result (Lit × Aig) := do
  let (o, aig1) ← push_or aig x y
  let (a, aig2) ← push_and aig1 x y
  let l ← lit_not a
  push_and aig2 o l

/-- [blast_kernel::eval_lit]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 110:0-113:1
    Visibility: public -/
def eval_lit (vals : Slice Bool) (l : Lit) : Result Bool := do
  let v ← Slice.index_usize vals l.node
  if l.neg
  then ok (¬ v)
  else ok v

/-- [blast_kernel::simulate]: loop body 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 122:4-135:5
    Visibility: public -/
@[rust_loop_body]
def simulate_loop.body
  (v : alloc.vec.Vec Node) (inputs : Slice Bool) (n : Std.Usize)
  (vals : alloc.vec.Vec Bool) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Bool) × Std.Usize) (alloc.vec.Vec Bool))
  := do
  if i < n
  then
    let node ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Node) v i
    let v1 ←
      match node with
      | Node.False => ok false
      | Node.Input k => Slice.index_usize inputs k
      | Node.And x y =>
        do
        let s := alloc.vec.Vec.deref vals
        let vx ← eval_lit s x
        let s1 := alloc.vec.Vec.deref vals
        let vy ← eval_lit s1 y
        if vx
        then ok vy
        else ok false
    let vals1 ← alloc.vec.Vec.push vals v1
    let i1 ← i + 1#usize
    ok (cont (vals1, i1))
  else ok (done vals)

/-- [blast_kernel::simulate]: loop 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 122:4-135:5
    Visibility: public -/
@[rust_loop]
def simulate_loop
  (v : alloc.vec.Vec Node) (inputs : Slice Bool) (vals : alloc.vec.Vec Bool)
  (n : Std.Usize) (i : Std.Usize) :
  Result (alloc.vec.Vec Bool)
  := do
  loop
    (fun (vals1, i1) => simulate_loop.body v inputs n vals1 i1)
    (vals, i)

/-- [blast_kernel::simulate]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 118:0-137:1
    Visibility: public -/
def simulate
  (aig : Aig) (inputs : Slice Bool) : Result (alloc.vec.Vec Bool) := do
  let n := alloc.vec.Vec.len aig.nodes
  simulate_loop aig.nodes inputs (alloc.vec.Vec.new Bool) n 0#usize

/-- [blast_kernel::blast_and]: loop body 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 145:4-149:5
    Visibility: public -/
@[rust_loop_body]
def blast_and_loop.body
  (a : Slice Lit) (b : Slice Lit) (w : Std.Usize) (aig : Aig)
  (out : alloc.vec.Vec Lit) (i : Std.Usize) :
  Result (ControlFlow (Aig × (alloc.vec.Vec Lit) × Std.Usize) ((alloc.vec.Vec
    Lit) × Aig))
  := do
  if i < w
  then
    let l ← Slice.index_usize a i
    let l1 ← Slice.index_usize b i
    let (g, aig1) ← push_and aig l l1
    let out1 ← alloc.vec.Vec.push out g
    let i1 ← i + 1#usize
    ok (cont (aig1, out1, i1))
  else ok (done (out, aig))

/-- [blast_kernel::blast_and]: loop 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 145:4-149:5
    Visibility: public -/
@[rust_loop]
def blast_and_loop
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) (out : alloc.vec.Vec Lit)
  (w : Std.Usize) (i : Std.Usize) :
  Result ((alloc.vec.Vec Lit) × Aig)
  := do
  loop
    (fun (aig1, out1, i1) => blast_and_loop.body a b w aig1 out1 i1)
    (aig, out, i)

/-- [blast_kernel::blast_and]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 141:0-151:1
    Visibility: public -/
def blast_and
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) :
  Result ((alloc.vec.Vec Lit) × Aig)
  := do
  let w := Slice.len a
  blast_and_loop aig a b (alloc.vec.Vec.new Lit) w 0#usize

/-- [blast_kernel::blast_or]: loop body 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 158:4-162:5
    Visibility: public -/
@[rust_loop_body]
def blast_or_loop.body
  (a : Slice Lit) (b : Slice Lit) (w : Std.Usize) (aig : Aig)
  (out : alloc.vec.Vec Lit) (i : Std.Usize) :
  Result (ControlFlow (Aig × (alloc.vec.Vec Lit) × Std.Usize) ((alloc.vec.Vec
    Lit) × Aig))
  := do
  if i < w
  then
    let l ← Slice.index_usize a i
    let l1 ← Slice.index_usize b i
    let (g, aig1) ← push_or aig l l1
    let out1 ← alloc.vec.Vec.push out g
    let i1 ← i + 1#usize
    ok (cont (aig1, out1, i1))
  else ok (done (out, aig))

/-- [blast_kernel::blast_or]: loop 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 158:4-162:5
    Visibility: public -/
@[rust_loop]
def blast_or_loop
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) (out : alloc.vec.Vec Lit)
  (w : Std.Usize) (i : Std.Usize) :
  Result ((alloc.vec.Vec Lit) × Aig)
  := do
  loop
    (fun (aig1, out1, i1) => blast_or_loop.body a b w aig1 out1 i1)
    (aig, out, i)

/-- [blast_kernel::blast_or]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 154:0-164:1
    Visibility: public -/
def blast_or
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) :
  Result ((alloc.vec.Vec Lit) × Aig)
  := do
  let w := Slice.len a
  blast_or_loop aig a b (alloc.vec.Vec.new Lit) w 0#usize

/-- [blast_kernel::blast_xor]: loop body 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 171:4-175:5
    Visibility: public -/
@[rust_loop_body]
def blast_xor_loop.body
  (a : Slice Lit) (b : Slice Lit) (w : Std.Usize) (aig : Aig)
  (out : alloc.vec.Vec Lit) (i : Std.Usize) :
  Result (ControlFlow (Aig × (alloc.vec.Vec Lit) × Std.Usize) ((alloc.vec.Vec
    Lit) × Aig))
  := do
  if i < w
  then
    let l ← Slice.index_usize a i
    let l1 ← Slice.index_usize b i
    let (g, aig1) ← push_xor aig l l1
    let out1 ← alloc.vec.Vec.push out g
    let i1 ← i + 1#usize
    ok (cont (aig1, out1, i1))
  else ok (done (out, aig))

/-- [blast_kernel::blast_xor]: loop 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 171:4-175:5
    Visibility: public -/
@[rust_loop]
def blast_xor_loop
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) (out : alloc.vec.Vec Lit)
  (w : Std.Usize) (i : Std.Usize) :
  Result ((alloc.vec.Vec Lit) × Aig)
  := do
  loop
    (fun (aig1, out1, i1) => blast_xor_loop.body a b w aig1 out1 i1)
    (aig, out, i)

/-- [blast_kernel::blast_xor]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 167:0-177:1
    Visibility: public -/
def blast_xor
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) :
  Result ((alloc.vec.Vec Lit) × Aig)
  := do
  let w := Slice.len a
  blast_xor_loop aig a b (alloc.vec.Vec.new Lit) w 0#usize

/-- [blast_kernel::ripple_carry]: loop body 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 187:4-195:5
    Visibility: public -/
@[rust_loop_body]
def ripple_carry_loop.body
  (a : Slice Lit) (b : Slice Lit) (w : Std.Usize) (aig : Aig) (carry : Lit)
  (sum : alloc.vec.Vec Lit) (i : Std.Usize) :
  Result (ControlFlow (Aig × Lit × (alloc.vec.Vec Lit) × Std.Usize) (Aig ×
    Lit × (alloc.vec.Vec Lit)))
  := do
  if i < w
  then
    let l ← Slice.index_usize a i
    let l1 ← Slice.index_usize b i
    let (p, aig1) ← push_xor aig l l1
    let (s, aig2) ← push_xor aig1 p carry
    let sum1 ← alloc.vec.Vec.push sum s
    let (g, aig3) ← push_and aig2 l l1
    let (t, aig4) ← push_and aig3 p carry
    let (carry1, aig5) ← push_or aig4 g t
    let i1 ← i + 1#usize
    ok (cont (aig5, carry1, sum1, i1))
  else ok (done (aig, carry, sum))

/-- [blast_kernel::ripple_carry]: loop 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 187:4-195:5
    Visibility: public -/
@[rust_loop]
def ripple_carry_loop
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) (carry : Lit)
  (sum : alloc.vec.Vec Lit) (w : Std.Usize) (i : Std.Usize) :
  Result (Aig × Lit × (alloc.vec.Vec Lit))
  := do
  loop
    (fun (aig1, carry1, sum1, i1) => ripple_carry_loop.body a b w aig1 carry1
      sum1 i1)
    (aig, carry, sum, i)

/-- [blast_kernel::ripple_carry]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 182:0-197:1
    Visibility: public -/
def ripple_carry
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) (carry_in : Lit) :
  Result (((alloc.vec.Vec Lit) × Lit) × Aig)
  := do
  let w := Slice.len a
  let (aig1, carry, sum) ←
    ripple_carry_loop aig a b carry_in (alloc.vec.Vec.new Lit) w 0#usize
  ok ((sum, carry), aig1)

/-- [blast_kernel::blast_add]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 200:0-203:1
    Visibility: public -/
def blast_add
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) :
  Result ((alloc.vec.Vec Lit) × Aig)
  := do
  let l ← lit_false
  let ((sum, _), aig1) ← ripple_carry aig a b l
  ok (sum, aig1)

/-- [blast_kernel::word_not]: loop body 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 210:4-213:5
    Visibility: public -/
@[rust_loop_body]
def word_not_loop.body
  (a : Slice Lit) (w : Std.Usize) (out : alloc.vec.Vec Lit) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Lit) × Std.Usize) (alloc.vec.Vec Lit))
  := do
  if i < w
  then
    let l ← Slice.index_usize a i
    let l1 ← lit_not l
    let out1 ← alloc.vec.Vec.push out l1
    let i1 ← i + 1#usize
    ok (cont (out1, i1))
  else ok (done out)

/-- [blast_kernel::word_not]: loop 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 210:4-213:5
    Visibility: public -/
@[rust_loop]
def word_not_loop
  (a : Slice Lit) (out : alloc.vec.Vec Lit) (w : Std.Usize) (i : Std.Usize) :
  Result (alloc.vec.Vec Lit)
  := do
  loop
    (fun (out1, i1) => word_not_loop.body a w out1 i1)
    (out, i)

/-- [blast_kernel::word_not]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 206:0-215:1
    Visibility: public -/
def word_not (a : Slice Lit) : Result (alloc.vec.Vec Lit) := do
  let w := Slice.len a
  word_not_loop a (alloc.vec.Vec.new Lit) w 0#usize

/-- [blast_kernel::blast_sub]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 218:0-222:1
    Visibility: public -/
def blast_sub
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) :
  Result ((alloc.vec.Vec Lit) × Aig)
  := do
  let not_b ← word_not b
  let s := alloc.vec.Vec.deref not_b
  let l ← lit_true
  let ((sum, _), aig1) ← ripple_carry aig a s l
  ok (sum, aig1)

/-- [blast_kernel::blast_ult]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 226:0-230:1
    Visibility: public -/
def blast_ult
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) : Result (Lit × Aig) := do
  let not_b ← word_not b
  let s := alloc.vec.Vec.deref not_b
  let l ← lit_true
  let ((_, carry), aig1) ← ripple_carry aig a s l
  let l1 ← lit_not carry
  ok (l1, aig1)

/-- [blast_kernel::blast_ule]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 233:0-236:1
    Visibility: public -/
def blast_ule
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) : Result (Lit × Aig) := do
  let (lt, aig1) ← blast_ult aig b a
  let l ← lit_not lt
  ok (l, aig1)

/-- [blast_kernel::blast_ugt]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 239:0-241:1
    Visibility: public -/
def blast_ugt
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) : Result (Lit × Aig) := do
  blast_ult aig b a

/-- [blast_kernel::blast_uge]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 244:0-247:1
    Visibility: public -/
def blast_uge
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) : Result (Lit × Aig) := do
  let (lt, aig1) ← blast_ult aig a b
  let l ← lit_not lt
  ok (l, aig1)

/-- [blast_kernel::flip_sign]: loop body 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 255:4-262:5
    Visibility: public -/
@[rust_loop_body]
def flip_sign_loop.body
  (a : Slice Lit) (w : Std.Usize) (out : alloc.vec.Vec Lit) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Lit) × Std.Usize) (alloc.vec.Vec Lit))
  := do
  if i < w
  then
    let i1 ← i + 1#usize
    let out1 ←
      if i1 = w
      then
        do
        let l ← Slice.index_usize a i
        let l1 ← lit_not l
        alloc.vec.Vec.push out l1
      else do
           let l ← Slice.index_usize a i
           alloc.vec.Vec.push out l
    ok (cont (out1, i1))
  else ok (done out)

/-- [blast_kernel::flip_sign]: loop 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 255:4-262:5
    Visibility: public -/
@[rust_loop]
def flip_sign_loop
  (a : Slice Lit) (out : alloc.vec.Vec Lit) (w : Std.Usize) (i : Std.Usize) :
  Result (alloc.vec.Vec Lit)
  := do
  loop
    (fun (out1, i1) => flip_sign_loop.body a w out1 i1)
    (out, i)

/-- [blast_kernel::flip_sign]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 251:0-264:1
    Visibility: public -/
def flip_sign (a : Slice Lit) : Result (alloc.vec.Vec Lit) := do
  let w := Slice.len a
  flip_sign_loop a (alloc.vec.Vec.new Lit) w 0#usize

/-- [blast_kernel::blast_slt]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 268:0-272:1
    Visibility: public -/
def blast_slt
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) : Result (Lit × Aig) := do
  let fa ← flip_sign a
  let fb ← flip_sign b
  let s := alloc.vec.Vec.deref fa
  let s1 := alloc.vec.Vec.deref fb
  blast_ult aig s s1

/-- [blast_kernel::blast_sle]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 275:0-278:1
    Visibility: public -/
def blast_sle
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) : Result (Lit × Aig) := do
  let (lt, aig1) ← blast_slt aig b a
  let l ← lit_not lt
  ok (l, aig1)

/-- [blast_kernel::blast_sgt]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 281:0-283:1
    Visibility: public -/
def blast_sgt
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) : Result (Lit × Aig) := do
  blast_slt aig b a

/-- [blast_kernel::blast_sge]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 286:0-289:1
    Visibility: public -/
def blast_sge
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) : Result (Lit × Aig) := do
  let (lt, aig1) ← blast_slt aig a b
  let l ← lit_not lt
  ok (l, aig1)

/-- [blast_kernel::blast_eq]: loop body 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 296:4-301:5
    Visibility: public -/
@[rust_loop_body]
def blast_eq_loop.body
  (a : Slice Lit) (b : Slice Lit) (w : Std.Usize) (aig : Aig) (acc : Lit)
  (i : Std.Usize) :
  Result (ControlFlow (Aig × Lit × Std.Usize) (Lit × Aig))
  := do
  if i < w
  then
    let l ← Slice.index_usize a i
    let l1 ← Slice.index_usize b i
    let (x, aig1) ← push_xor aig l l1
    let bit_eq ← lit_not x
    let (acc1, aig2) ← push_and aig1 acc bit_eq
    let i1 ← i + 1#usize
    ok (cont (aig2, acc1, i1))
  else ok (done (acc, aig))

/-- [blast_kernel::blast_eq]: loop 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 296:4-301:5
    Visibility: public -/
@[rust_loop]
def blast_eq_loop
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) (acc : Lit) (w : Std.Usize)
  (i : Std.Usize) :
  Result (Lit × Aig)
  := do
  loop
    (fun (aig1, acc1, i1) => blast_eq_loop.body a b w aig1 acc1 i1)
    (aig, acc, i)

/-- [blast_kernel::blast_eq]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 292:0-303:1
    Visibility: public -/
def blast_eq
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) : Result (Lit × Aig) := do
  let acc ← lit_true
  let w := Slice.len a
  blast_eq_loop aig a b acc w 0#usize

/-- [blast_kernel::blast_ne]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 306:0-309:1
    Visibility: public -/
def blast_ne
  (aig : Aig) (a : Slice Lit) (b : Slice Lit) : Result (Lit × Aig) := do
  let (eq, aig1) ← blast_eq aig a b
  let l ← lit_not eq
  ok (l, aig1)

/-- [blast_kernel::push_mux]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 312:0-316:1
    Visibility: public -/
def push_mux
  (aig : Aig) (sel : Lit) (t : Lit) (e : Lit) : Result (Lit × Aig) := do
  let (then_b, aig1) ← push_and aig sel t
  let l ← lit_not sel
  let (else_b, aig2) ← push_and aig1 l e
  push_or aig2 then_b else_b

/-- [blast_kernel::blast_ite]: loop body 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 323:4-327:5
    Visibility: public -/
@[rust_loop_body]
def blast_ite_loop.body
  (cond : Lit) (then_ : Slice Lit) (else_ : Slice Lit) (w : Std.Usize)
  (aig : Aig) (out : alloc.vec.Vec Lit) (i : Std.Usize) :
  Result (ControlFlow (Aig × (alloc.vec.Vec Lit) × Std.Usize) ((alloc.vec.Vec
    Lit) × Aig))
  := do
  if i < w
  then
    let l ← Slice.index_usize then_ i
    let l1 ← Slice.index_usize else_ i
    let (m, aig1) ← push_mux aig cond l l1
    let out1 ← alloc.vec.Vec.push out m
    let i1 ← i + 1#usize
    ok (cont (aig1, out1, i1))
  else ok (done (out, aig))

/-- [blast_kernel::blast_ite]: loop 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 323:4-327:5
    Visibility: public -/
@[rust_loop]
def blast_ite_loop
  (aig : Aig) (cond : Lit) (then_ : Slice Lit) (else_ : Slice Lit)
  (out : alloc.vec.Vec Lit) (w : Std.Usize) (i : Std.Usize) :
  Result ((alloc.vec.Vec Lit) × Aig)
  := do
  loop
    (fun (aig1, out1, i1) => blast_ite_loop.body cond then_ else_ w aig1 out1
      i1)
    (aig, out, i)

/-- [blast_kernel::blast_ite]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 319:0-329:1
    Visibility: public -/
def blast_ite
  (aig : Aig) (cond : Lit) (then_ : Slice Lit) (else_ : Slice Lit) :
  Result ((alloc.vec.Vec Lit) × Aig)
  := do
  let w := Slice.len then_
  blast_ite_loop aig cond then_ else_ (alloc.vec.Vec.new Lit) w 0#usize

/-- [blast_kernel::blast_extract]: loop body 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 335:4-338:5
    Visibility: public -/
@[rust_loop_body]
def blast_extract_loop.body
  (a : Slice Lit) (hi : Std.Usize) (out : alloc.vec.Vec Lit) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Lit) × Std.Usize) (alloc.vec.Vec Lit))
  := do
  if i <= hi
  then
    let l ← Slice.index_usize a i
    let out1 ← alloc.vec.Vec.push out l
    let i1 ← i + 1#usize
    ok (cont (out1, i1))
  else ok (done out)

/-- [blast_kernel::blast_extract]: loop 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 335:4-338:5
    Visibility: public -/
@[rust_loop]
def blast_extract_loop
  (a : Slice Lit) (hi : Std.Usize) (out : alloc.vec.Vec Lit) (i : Std.Usize) :
  Result (alloc.vec.Vec Lit)
  := do
  loop
    (fun (out1, i1) => blast_extract_loop.body a hi out1 i1)
    (out, i)

/-- [blast_kernel::blast_extract]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 332:0-340:1
    Visibility: public -/
@[reducible]
def blast_extract
  (a : Slice Lit) (hi : Std.Usize) (lo : Std.Usize) :
  Result (alloc.vec.Vec Lit)
  := do
  blast_extract_loop a hi (alloc.vec.Vec.new Lit) lo

/-- [blast_kernel::blast_concat]: loop body 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 348:4-351:5
    Visibility: public -/
@[rust_loop_body]
def blast_concat_loop0.body
  (lo_part : Slice Lit) (wl : Std.Usize) (out : alloc.vec.Vec Lit)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Lit) × Std.Usize) (alloc.vec.Vec Lit))
  := do
  if i < wl
  then
    let l ← Slice.index_usize lo_part i
    let out1 ← alloc.vec.Vec.push out l
    let i1 ← i + 1#usize
    ok (cont (out1, i1))
  else ok (done out)

/-- [blast_kernel::blast_concat]: loop 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 348:4-351:5
    Visibility: public -/
@[rust_loop]
def blast_concat_loop0
  (lo_part : Slice Lit) (out : alloc.vec.Vec Lit) (wl : Std.Usize)
  (i : Std.Usize) :
  Result (alloc.vec.Vec Lit)
  := do
  loop
    (fun (out1, i1) => blast_concat_loop0.body lo_part wl out1 i1)
    (out, i)

/-- [blast_kernel::blast_concat]: loop body 1:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 354:4-357:5
    Visibility: public -/
@[rust_loop_body]
def blast_concat_loop1.body
  (hi_part : Slice Lit) (wh : Std.Usize) (out : alloc.vec.Vec Lit)
  (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Lit) × Std.Usize) (alloc.vec.Vec Lit))
  := do
  if j < wh
  then
    let l ← Slice.index_usize hi_part j
    let out1 ← alloc.vec.Vec.push out l
    let j1 ← j + 1#usize
    ok (cont (out1, j1))
  else ok (done out)

/-- [blast_kernel::blast_concat]: loop 1:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 354:4-357:5
    Visibility: public -/
@[rust_loop]
def blast_concat_loop1
  (hi_part : Slice Lit) (out : alloc.vec.Vec Lit) (wh : Std.Usize)
  (j : Std.Usize) :
  Result (alloc.vec.Vec Lit)
  := do
  loop
    (fun (out1, j1) => blast_concat_loop1.body hi_part wh out1 j1)
    (out, j)

/-- [blast_kernel::blast_concat]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 344:0-359:1
    Visibility: public -/
def blast_concat
  (hi_part : Slice Lit) (lo_part : Slice Lit) :
  Result (alloc.vec.Vec Lit)
  := do
  let wl := Slice.len lo_part
  let out ← blast_concat_loop0 lo_part (alloc.vec.Vec.new Lit) wl 0#usize
  let wh := Slice.len hi_part
  blast_concat_loop1 hi_part out wh 0#usize

/-- [blast_kernel::blast_zero_ext]: loop body 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 366:4-369:5
    Visibility: public -/
@[rust_loop_body]
def blast_zero_ext_loop0.body
  (a : Slice Lit) (w : Std.Usize) (out : alloc.vec.Vec Lit) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Lit) × Std.Usize) (alloc.vec.Vec Lit))
  := do
  if i < w
  then
    let l ← Slice.index_usize a i
    let out1 ← alloc.vec.Vec.push out l
    let i1 ← i + 1#usize
    ok (cont (out1, i1))
  else ok (done out)

/-- [blast_kernel::blast_zero_ext]: loop 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 366:4-369:5
    Visibility: public -/
@[rust_loop]
def blast_zero_ext_loop0
  (a : Slice Lit) (out : alloc.vec.Vec Lit) (w : Std.Usize) (i : Std.Usize) :
  Result (alloc.vec.Vec Lit)
  := do
  loop
    (fun (out1, i1) => blast_zero_ext_loop0.body a w out1 i1)
    (out, i)

/-- [blast_kernel::blast_zero_ext]: loop body 1:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 371:4-374:5
    Visibility: public -/
@[rust_loop_body]
def blast_zero_ext_loop1.body
  (by1 : Std.Usize) (out : alloc.vec.Vec Lit) (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Lit) × Std.Usize) (alloc.vec.Vec Lit))
  := do
  if j < by1
  then
    let l ← lit_false
    let out1 ← alloc.vec.Vec.push out l
    let j1 ← j + 1#usize
    ok (cont (out1, j1))
  else ok (done out)

/-- [blast_kernel::blast_zero_ext]: loop 1:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 371:4-374:5
    Visibility: public -/
@[rust_loop]
def blast_zero_ext_loop1
  (by1 : Std.Usize) (out : alloc.vec.Vec Lit) (j : Std.Usize) :
  Result (alloc.vec.Vec Lit)
  := do
  loop
    (fun (out1, j1) => blast_zero_ext_loop1.body by1 out1 j1)
    (out, j)

/-- [blast_kernel::blast_zero_ext]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 362:0-376:1
    Visibility: public -/
def blast_zero_ext
  (a : Slice Lit) (by1 : Std.Usize) : Result (alloc.vec.Vec Lit) := do
  let w := Slice.len a
  let out ← blast_zero_ext_loop0 a (alloc.vec.Vec.new Lit) w 0#usize
  blast_zero_ext_loop1 by1 out 0#usize

/-- [blast_kernel::blast_sign_ext]: loop body 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 383:4-386:5
    Visibility: public -/
@[rust_loop_body]
def blast_sign_ext_loop0.body
  (a : Slice Lit) (w : Std.Usize) (out : alloc.vec.Vec Lit) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Lit) × Std.Usize) (alloc.vec.Vec Lit))
  := do
  if i < w
  then
    let l ← Slice.index_usize a i
    let out1 ← alloc.vec.Vec.push out l
    let i1 ← i + 1#usize
    ok (cont (out1, i1))
  else ok (done out)

/-- [blast_kernel::blast_sign_ext]: loop 0:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 383:4-386:5
    Visibility: public -/
@[rust_loop]
def blast_sign_ext_loop0
  (a : Slice Lit) (out : alloc.vec.Vec Lit) (w : Std.Usize) (i : Std.Usize) :
  Result (alloc.vec.Vec Lit)
  := do
  loop
    (fun (out1, i1) => blast_sign_ext_loop0.body a w out1 i1)
    (out, i)

/-- [blast_kernel::blast_sign_ext]: loop body 1:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 389:4-392:5
    Visibility: public -/
@[rust_loop_body]
def blast_sign_ext_loop1.body
  (by1 : Std.Usize) (sign : Lit) (out : alloc.vec.Vec Lit) (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Lit) × Std.Usize) (alloc.vec.Vec Lit))
  := do
  if j < by1
  then
    let out1 ← alloc.vec.Vec.push out sign
    let j1 ← j + 1#usize
    ok (cont (out1, j1))
  else ok (done out)

/-- [blast_kernel::blast_sign_ext]: loop 1:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 389:4-392:5
    Visibility: public -/
@[rust_loop]
def blast_sign_ext_loop1
  (by1 : Std.Usize) (out : alloc.vec.Vec Lit) (sign : Lit) (j : Std.Usize) :
  Result (alloc.vec.Vec Lit)
  := do
  loop
    (fun (out1, j1) => blast_sign_ext_loop1.body by1 sign out1 j1)
    (out, j)

/-- [blast_kernel::blast_sign_ext]:
    Source: 'crates/ordeal/src/blast_kernel.rs', lines 379:0-394:1
    Visibility: public -/
def blast_sign_ext
  (a : Slice Lit) (by1 : Std.Usize) : Result (alloc.vec.Vec Lit) := do
  let w := Slice.len a
  let out ← blast_sign_ext_loop0 a (alloc.vec.Vec.new Lit) w 0#usize
  let i ← w - 1#usize
  let sign ← Slice.index_usize a i
  blast_sign_ext_loop1 by1 out sign 0#usize

end blast_kernel
