/- Correctness of the barrel-shifter blaster family (issue #68, v0.15.0):
   `out_of_range`, `barrel_right_stage` / `barrel_left_stage` / `rotr_stage`,
   `barrel_right`, and the four headline rules `blast_shl` / `blast_lshr` /
   `blast_ashr` / `blast_rotr`.

   This file is HAND-WRITTEN (BlastKernel.lean is generated by
   regen-blaster.sh and must not be edited). It builds on the pure-model
   infrastructure of BlasterProof.lean (`pSim` / `pEvalLit`,
   append-monotonicity, `AigWF`, the gadget-spec idiom, `simulate_spec`,
   `Denotes`), BlasterArith.lean (`dLit`, `lit_false_spec`,
   `pEvalLit_node_zero`) and BlasterCmp.lean (`push_mux_gadget`).

   Proof architecture:
   * `pAmt` is the PURE partial shift amount: the value of the low `k` bits
     of the amount word `b`. Stage `k` of a barrel shifter muxes a shift by
     `2^k` gated on amount bit `b[k]`, so after `k` stages the word is
     shifted by exactly `pAmt … k`; `pAmt_eq_mod` identifies the final
     amount with `B.toNat % 2^stages` on denoting words (via
     `Nat.testBit_eq_decide_div_mod_eq` and `Nat.mod_mul`).
   * `pHigh` is the PURE out-of-range detector: the OR of the amount bits
     `b[stages..]`. `pHigh_eq_decide` identifies it with
     `decide (2^stages ≤ B.toNat)` — a high bit is set iff the amount value
     reaches `2^stages` (`exists_high_bit_iff`, proved by a
     `setWidth`-truncation argument, no `Nat.xor` bit-fiddling).
   * `MuxMapInv` is the loop invariant shared by ALL five per-bit mux loops
     (the three stage loops and the two final fill muxes): 3 gates per bit,
     the original AIG is a prefix, and emitted literal `j` evaluates — under
     the CURRENT aig — to a rule-specific function `φ inp j` of the input
     assignment (operand values under the ORIGINAL aig).
   * The stage-fold loops (`barrel_right_loop1` / `blast_shl_loop1` /
     `blast_rotr_loop1`) maintain the barrel invariant: after `k` rounds,
     bit `i` of the current word equals bit `i + pAmt … k` (right;
     `i - pAmt … k` left, `(i + pAmt … k) % w` rotate) of the ORIGINAL word,
     with the fill / FALSE past the end.
   * The headline theorems compose with `simulate_spec` and lift to
     `BitVec w`:
     - `blast_shl_bitvec`  : output denotes `A <<< B.toNat`
       (core's `<<<` on `Nat` amounts already yields `0` past the width —
       `getLsbD_shiftLeft`'s `decide (i < n)` guard — matching SMT-LIB).
     - `blast_lshr_bitvec` : output denotes `A >>> B.toNat`
       (`getLsbD_ushiftRight` reads bit `n + i`, false past the width).
     - `blast_ashr_bitvec` : output denotes `A.sshiftRight B.toNat`
       (`getLsbD_sshiftRight` saturates to the sign bit).
     - `blast_rotr_bitvec` : output denotes `A.rotateRight (B.toNat % w)`
       (`getLsbD_rotateRight`; only the low `stages` bits of `B` matter
       because `B.toNat % w = B.toNat % 2^stages` when `2^stages = w`).
-/
import BlasterCmp

open Aeneas Aeneas.Std Result

set_option maxHeartbeats 1000000

namespace blast_kernel.spec

/- ══════════════════ THE PURE SHIFT AMOUNT ══════════════════ -/

/-- Value of the low `k` bits of the shift-amount word `b`: the partial
    barrel-shift amount after `k` stages. -/
def pAmt (vals : List Bool) (b : List Lit) : Nat → Nat
  | 0 => 0
  | k + 1 =>
    pAmt vals b k + (if pEvalLit vals (b.getD k dLit) then 2 ^ k else 0)

theorem pAmt_lt (vals : List Bool) (b : List Lit) (k : Nat) :
    pAmt vals b k < 2 ^ k := by
  induction k with
  | zero => simp [pAmt]
  | succ k ih =>
    have h2 : (2 : Nat) ^ (k + 1) = 2 ^ k + 2 ^ k := by
      rw [Nat.pow_succ]; omega
    simp only [pAmt]
    split <;> omega

/-- Append-monotonicity for the partial amount: appending nodes to the AIG
    does not change it. -/
theorem pAmt_stable {ns ns' : List Node} (hpre : ns <+: ns') {b : List Lit}
    (hb : ∀ l ∈ b, l.node.val < ns.length) (inp : List Bool) (k : Nat)
    (hk : k ≤ b.length) :
    pAmt (pSim inp ns') b k = pAmt (pSim inp ns) b k := by
  induction k with
  | zero => rfl
  | succ k ih =>
    have hk' : k < b.length := by omega
    simp only [pAmt, getD_eq_getElem_of_lt hk',
      pEvalLit_stable hpre _ (hb _ (List.getElem_mem hk')) inp,
      ih (by omega)]

/-- On denoting words the partial amount is the amount value modulo `2^k`
    (bit decomposition of `Nat.mod`). -/
theorem pAmt_eq_mod {vals : List Bool} {b : List Lit} {w : Nat}
    {B : BitVec w} (hB : Denotes vals b w B) (k : Nat) (hk : k ≤ w) :
    pAmt vals b k = B.toNat % 2 ^ k := by
  obtain ⟨hbl, hBj⟩ := hB
  induction k with
  | zero => simp [pAmt, Nat.mod_one]
  | succ k ih =>
    have hkb : k < b.length := by omega
    have hdecomp : B.toNat % 2 ^ (k + 1)
        = B.toNat % 2 ^ k + 2 ^ k * (B.toNat / 2 ^ k % 2) := by
      rw [Nat.pow_succ]
      exact Nat.mod_mul
    have htb : B.getLsbD k = decide (B.toNat / 2 ^ k % 2 = 1) := by
      rw [show B.getLsbD k = B.toNat.testBit k from rfl,
        Nat.testBit_eq_decide_div_mod_eq]
    simp only [pAmt, getD_eq_getElem_of_lt hkb, hBj k hkb, ih (by omega),
      hdecomp, htb]
    rcases Nat.mod_two_eq_zero_or_one (B.toNat / 2 ^ k) with hm | hm <;>
      simp [hm]

/- ══════════════════ THE PURE OUT-OF-RANGE DETECTOR ══════════════════ -/

/-- OR of the amount bits `b[s..i)`: the out-of-range detector's fold. -/
def pHigh (vals : List Bool) (b : List Lit) (s : Nat) : Nat → Bool
  | 0 => false
  | i + 1 =>
    pHigh vals b s i || (decide (s ≤ i) && pEvalLit vals (b.getD i dLit))

theorem pHigh_of_le (vals : List Bool) (b : List Lit) {s i : Nat}
    (hi : i ≤ s) : pHigh vals b s i = false := by
  induction i with
  | zero => rfl
  | succ i ih =>
    simp only [pHigh, ih (by omega), Bool.false_or,
      show ¬(s ≤ i) by omega, decide_false, Bool.false_and]

/-- Append-monotonicity for the out-of-range fold. -/
theorem pHigh_stable {ns ns' : List Node} (hpre : ns <+: ns') {b : List Lit}
    (hb : ∀ l ∈ b, l.node.val < ns.length) (inp : List Bool) (s i : Nat)
    (hi : i ≤ b.length) :
    pHigh (pSim inp ns') b s i = pHigh (pSim inp ns) b s i := by
  induction i with
  | zero => rfl
  | succ i ih =>
    have hi' : i < b.length := by omega
    simp only [pHigh, getD_eq_getElem_of_lt hi',
      pEvalLit_stable hpre _ (hb _ (List.getElem_mem hi')) inp,
      ih (by omega)]

/-- A bitvector has a set bit at or above position `s` iff its value
    reaches `2^s` (given `s ≤ w`; proved by truncation to `s` bits). -/
theorem exists_high_bit_iff {w : Nat} (B : BitVec w) {s : Nat} (hs : s ≤ w) :
    (∃ j, s ≤ j ∧ j < w ∧ B.getLsbD j = true) ↔ 2 ^ s ≤ B.toNat := by
  constructor
  · rintro ⟨j, hsj, hjw, hbit⟩
    have h1 : 2 ^ j ≤ B.toNat :=
      Nat.ge_two_pow_of_testBit
        (by rwa [show B.getLsbD j = B.toNat.testBit j from rfl] at hbit)
    have h2 : (2 : Nat) ^ s ≤ 2 ^ j := Nat.pow_le_pow_right (by omega) hsj
    omega
  · intro hge
    by_contra hno
    have hbits : ∀ j, s ≤ j → j < w → B.getLsbD j = false := by
      intro j h1 h2
      by_contra hbit
      exact hno ⟨j, h1, h2, by simpa using hbit⟩
    have hBeq : B = BitVec.setWidth w (BitVec.setWidth s B) := by
      apply BitVec.eq_of_getLsbD_eq
      intro i hi
      rw [BitVec.getLsbD_setWidth, BitVec.getLsbD_setWidth]
      by_cases his : i < s
      · rw [decide_eq_true his, decide_eq_true hi]
        simp only [Bool.true_and]
      · rw [decide_eq_false his, hbits i (by omega) hi]
        simp only [Bool.and_false]
    have htn := congrArg BitVec.toNat hBeq
    rw [BitVec.toNat_setWidth, BitVec.toNat_setWidth] at htn
    have hlt : B.toNat % 2 ^ s < 2 ^ s :=
      Nat.mod_lt _ (Nat.two_pow_pos s)
    have hpw : (2 : Nat) ^ s ≤ 2 ^ w := Nat.pow_le_pow_right (by omega) hs
    have hmod : B.toNat % 2 ^ s % 2 ^ w = B.toNat % 2 ^ s :=
      Nat.mod_eq_of_lt (by omega)
    omega

/-- On denoting words the out-of-range fold decides `2^s ≤ B.toNat`. -/
theorem pHigh_eq_decide {vals : List Bool} {b : List Lit} {w : Nat}
    {B : BitVec w} (hB : Denotes vals b w B) {s : Nat} (hs : s ≤ w) :
    pHigh vals b s w = decide (2 ^ s ≤ B.toNat) := by
  obtain ⟨hbl, hBj⟩ := hB
  have key : ∀ i, i ≤ w →
      (pHigh vals b s i = true
        ↔ ∃ j, s ≤ j ∧ j < i ∧ B.getLsbD j = true) := by
    intro i
    induction i with
    | zero =>
      intro _
      simp only [pHigh, Bool.false_eq_true, false_iff]
      rintro ⟨j, _, hj, _⟩
      omega
    | succ i ih =>
      intro hi
      have hib : i < b.length := by omega
      simp only [pHigh, Bool.or_eq_true, Bool.and_eq_true,
        decide_eq_true_eq, ih (by omega), getD_eq_getElem_of_lt hib,
        hBj i hib]
      constructor
      · rintro (⟨j, h1, h2, h3⟩ | ⟨h1, h2⟩)
        · exact ⟨j, h1, by omega, h3⟩
        · exact ⟨i, h1, by omega, h2⟩
      · rintro ⟨j, h1, h2, h3⟩
        rcases Nat.lt_or_ge j i with h | h
        · exact Or.inl ⟨j, h1, h, h3⟩
        · have : j = i := by omega
          subst this
          exact Or.inr ⟨h1, h3⟩
  apply Bool.eq_iff_iff.mpr
  rw [decide_eq_true_eq]
  exact (key w (Nat.le_refl w)).trans (exists_high_bit_iff B hs)

/- ══════════════════ USIZE / PLATFORM HELPERS ══════════════════ -/

private theorem usize_max_eq_pow :
    Usize.max = 2 ^ System.Platform.numBits - 1 := by
  rw [Usize.max_def, Usize.numBits_def, UScalarTy.Usize_numBits_eq]

private theorem lt_numBits_of_pow_le {k : Nat} (h : 2 ^ k ≤ Usize.max) :
    k < System.Platform.numBits := by
  rw [usize_max_eq_pow] at h
  have hpos := Nat.two_pow_pos System.Platform.numBits
  have h2 : (2 : Nat) ^ k < 2 ^ System.Platform.numBits := by omega
  exact (Nat.pow_lt_pow_iff_right (by omega)).mp h2

private theorem shl_one_val {k : Nat} (hk : k < System.Platform.numBits) :
    (1 <<< k) % Usize.size = 2 ^ k := by
  rw [Nat.shiftLeft_eq, one_mul, Usize.size_def, Usize.numBits_def,
    UScalarTy.Usize_numBits_eq]
  exact Nat.mod_eq_of_lt ((Nat.pow_lt_pow_iff_right (by omega)).mpr hk)

/-- Node 0 stays the constant-FALSE node under any extension of the AIG. -/
theorem node0_of_prefix {ns ns' : List Node} (hpre : ns <+: ns')
    (hne : 0 < ns.length) (h0 : ns[0]'hne = Node.False)
    (hne' : 0 < ns'.length) : ns'[0]'hne' = Node.False := by
  obtain ⟨t, rfl⟩ := hpre
  rw [List.getElem_append_left hne]
  exact h0

/- ══════════════════ THE SHARED PER-BIT MUX LOOP INVARIANT ══════════════════ -/

/-- Loop invariant shared by ALL five per-bit mux loops of the barrel
    shifters (the three stage loops and the two final fill muxes): after `i`
    processed bits, 3 gates per bit were appended, the original AIG is a
    prefix (nothing existing was touched), well-formedness is preserved, and
    emitted output literal `j` evaluates — under the CURRENT aig — to the
    rule-specific value `φ inp j` (whose operand values are read under the
    ORIGINAL aig). -/
def MuxMapInv (aig : Aig) (wlen : Nat) (φ : List Bool → Nat → Bool)
    (aig1 : Aig) (out1 : alloc.vec.Vec Lit) (i : Nat) : Prop :=
  i ≤ wlen ∧
  aig1.nodes.val.length = aig.nodes.val.length + 3 * i ∧
  aig.nodes.val <+: aig1.nodes.val ∧
  (∀ L, AigWF aig.nodes.val L → AigWF aig1.nodes.val L) ∧
  out1.val.length = i ∧
  (∀ l ∈ out1.val, l.node.val < aig1.nodes.val.length) ∧
  ∀ (inp : List Bool) (j : Nat) (hj : j < out1.val.length),
    pEvalLit (pSim inp aig1.nodes.val) out1.val[j] = φ inp j

theorem MuxMapInv.init (aig : Aig) (wlen : Nat)
    (φ : List Bool → Nat → Bool) :
    MuxMapInv aig wlen φ aig (alloc.vec.Vec.new Lit) 0 := by
  refine ⟨Nat.zero_le _, by simp, List.prefix_refl _, fun _ h => h, by simp,
    by simp, ?_⟩
  intro _ j hj
  simp at hj

/-- Preservation: pushing one 3-gate gadget valued `φ inp i` for bit `i` and
    appending its output literal re-establishes the invariant at `i + 1`. -/
theorem MuxMapInv.step {aig : Aig} {wlen : Nat} {φ : List Bool → Nat → Bool}
    {aig1 aig2 : Aig} {out1 out2 : alloc.vec.Vec Lit} {g : Lit} {i : Nat}
    (h : MuxMapInv aig wlen φ aig1 out1 i) (hiw : i < wlen)
    (hglen : aig2.nodes.val.length = aig1.nodes.val.length + 3)
    (hgpre : aig1.nodes.val <+: aig2.nodes.val)
    (hgnode : g.node.val < aig2.nodes.val.length)
    (hgwf : ∀ L, AigWF aig1.nodes.val L → AigWF aig2.nodes.val L)
    (hgsem : ∀ inp : List Bool,
      pEvalLit (pSim inp aig2.nodes.val) g = φ inp i)
    (hout2 : out2.val = out1.val ++ [g]) :
    MuxMapInv aig wlen φ aig2 out2 (i + 1) := by
  obtain ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩ := h
  refine ⟨by omega, by omega, hpre1.trans hgpre,
    fun L hL => hgwf L (hwf1 L hL), by rw [hout2]; simp [holen], ?_, ?_⟩
  · intro l hl
    rw [hout2] at hl
    rcases List.mem_append.mp hl with h' | h'
    · exact Nat.lt_of_lt_of_le (horng l h') hgpre.length_le
    · simp only [List.mem_singleton] at h'
      subst h'
      exact hgnode
  · intro inp j hj
    have hj' : j < out1.val.length + 1 := by
      rw [hout2] at hj
      simpa using hj
    rcases Nat.lt_or_ge j out1.val.length with hji | hji
    · have hgetj : out2.val[j]'hj = out1.val[j]'hji := by
        simp only [hout2]
        exact List.getElem_append_left hji
      rw [hgetj, pEvalLit_stable hgpre _ (horng _ (List.getElem_mem _)) inp]
      exact hsem inp j hji
    · have hjeq : j = i := by omega
      subst hjeq
      have hgetj : out2.val[j]'hj = g := by
        simp only [hout2]
        exact List.getElem_concat_length (by omega) _
      rw [hgetj]
      exact hgsem inp

/- ══════════════════ `out_of_range` ══════════════════ -/

/-- **Spec of `out_of_range`**: appends `|b| - stages` OR gates, preserves
    everything existing, and the returned literal evaluates — under the
    extended aig — to the OR of the amount bits `b[stages..]` (values under
    the ORIGINAL aig). Requires node 0 to be the constant-FALSE node (the
    fold starts from `lit_false`). -/
theorem out_of_range_spec (aig : Aig) (b : Slice Lit) (stages : Std.Usize)
    (hstages : stages.val ≤ b.val.length)
    (hcap : aig.nodes.val.length + (b.val.length - stages.val) ≤ Usize.max)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False) :
    out_of_range aig b stages ⦃ p =>
      p.2.nodes.val.length
        = aig.nodes.val.length + (b.val.length - stages.val) ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      p.1.node.val < p.2.nodes.val.length ∧
      ∀ inp : List Bool,
        pEvalLit (pSim inp p.2.nodes.val) p.1
          = pHigh (pSim inp aig.nodes.val) b.val stages.val b.val.length ⦄ := by
  unfold out_of_range
  step with lit_false_spec as ⟨acc, hacc⟩
  unfold out_of_range_loop
  apply loop.spec_decr_nat
    (measure := fun (s : Aig × Lit × Std.Usize) =>
      b.val.length - s.2.2.val)
    (inv := fun (s : Aig × Lit × Std.Usize) =>
      stages.val ≤ s.2.2.val ∧ s.2.2.val ≤ b.val.length ∧
      s.1.nodes.val.length
        = aig.nodes.val.length + (s.2.2.val - stages.val) ∧
      aig.nodes.val <+: s.1.nodes.val ∧
      (∀ L, AigWF aig.nodes.val L → AigWF s.1.nodes.val L) ∧
      s.2.1.node.val < s.1.nodes.val.length ∧
      ∀ inp : List Bool,
        pEvalLit (pSim inp s.1.nodes.val) s.2.1
          = pHigh (pSim inp aig.nodes.val) b.val stages.val s.2.2.val)
  · rintro ⟨aig1, acc1, i⟩ hinv
    obtain ⟨hsle, hile, hlen1, hpre1, hwf1, harng, hsem⟩ := hinv
    dsimp only at hsle hile hlen1 hpre1 hwf1 harng hsem
    unfold out_of_range_loop.body
    dsimp only
    split
    · rename_i hlt
      have hib : i.val < b.val.length := by scalar_tac
      step as ⟨l, hl⟩
      have hl' : l.node.val < aig1.nodes.val.length := by
        have h1 := hb l (by rw [hl]; exact List.getElem_mem _)
        have h2 := hpre1.length_le
        omega
      step with (push_or_gadget aig1 acc1 l (by omega) harng hl') as
        ⟨acc2, aig2, hg1, hg2, hg3, hg4, hg5⟩
      step as ⟨i1, hi1⟩
      refine ⟨by scalar_tac, by scalar_tac, by scalar_tac,
        hpre1.trans hg2, fun L hL => hg4 L (hwf1 L hL), hg3, ?_,
        by scalar_tac⟩
      intro inp
      rw [hi1, hg5 inp, hsem inp, hl,
        pEvalLit_stable hpre1 _ (hb _ (List.getElem_mem hib)) inp]
      simp only [pHigh, getD_eq_getElem_of_lt hib,
        decide_eq_true hsle, Bool.true_and]
    · rename_i hge
      have hieq : i.val = b.val.length := by scalar_tac
      rw [hieq] at hlen1 hsem
      exact ⟨hlen1, hpre1, hwf1, harng, hsem⟩
  · dsimp only
    refine ⟨by scalar_tac, by scalar_tac, by scalar_tac, List.prefix_refl _,
      fun _ h => h, by rw [hacc]; scalar_tac, ?_⟩
    intro inp
    rw [hacc, pEvalLit_node_zero hne h0 inp false,
      pHigh_of_le _ _ (Nat.le_refl _)]

/- ══════════════════ THE THREE BARREL STAGES ══════════════════ -/

/-- **Spec of `barrel_right_stage`** (one barrel round, shift by `s`,
    gated on `sel`): appends exactly 3 gates per bit; output bit `j` is
    `sel ? (j + s < w ? cur[j + s] : fill) : cur[j]`, operand values under
    the ORIGINAL aig. -/
theorem barrel_right_stage_spec (aig : Aig) (cur : Slice Lit) (sel : Lit)
    (s : Std.Usize) (fill : Lit)
    (hcap : aig.nodes.val.length + 3 * cur.val.length ≤ Usize.max)
    (hadd : cur.val.length + s.val ≤ Usize.max)
    (hcur : ∀ l ∈ cur.val, l.node.val < aig.nodes.val.length)
    (hsel : sel.node.val < aig.nodes.val.length)
    (hfill : fill.node.val < aig.nodes.val.length) :
    barrel_right_stage aig cur sel s fill ⦃ p =>
      p.1.val.length = cur.val.length ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.2.nodes.val.length = aig.nodes.val.length + 3 * cur.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ l ∈ p.1.val, l.node.val < p.2.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj : j < p.1.val.length),
        pEvalLit (pSim inp p.2.nodes.val) p.1.val[j]
          = if pEvalLit (pSim inp aig.nodes.val) sel
            then (if j + s.val < cur.val.length
              then pEvalLit (pSim inp aig.nodes.val)
                (cur.val.getD (j + s.val) dLit)
              else pEvalLit (pSim inp aig.nodes.val) fill)
            else pEvalLit (pSim inp aig.nodes.val)
              (cur.val.getD j dLit) ⦄ := by
  unfold barrel_right_stage barrel_right_stage_loop
  apply loop.spec_decr_nat
    (measure := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      cur.val.length - st.2.2.val)
    (inv := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      MuxMapInv aig cur.val.length
        (fun inp j =>
          if pEvalLit (pSim inp aig.nodes.val) sel
          then (if j + s.val < cur.val.length
            then pEvalLit (pSim inp aig.nodes.val)
              (cur.val.getD (j + s.val) dLit)
            else pEvalLit (pSim inp aig.nodes.val) fill)
          else pEvalLit (pSim inp aig.nodes.val) (cur.val.getD j dLit))
        st.1 st.2.1 st.2.2.val)
  · rintro ⟨aig1, next1, i⟩ hinv
    obtain ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩ := hinv
    dsimp only at hile hlen1 hpre1 hwf1 holen horng hsem
    unfold barrel_right_stage_loop.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < cur.val.length := by scalar_tac
      have hiadd : i.val + s.val ≤ Usize.max := by omega
      step as ⟨i1, hi1⟩
      have hsel1 : sel.node.val < aig1.nodes.val.length := by
        have := hpre1.length_le
        omega
      have hcap1 : aig1.nodes.val.length + 3 ≤ Usize.max := by omega
      have hncap : next1.val.length < Usize.max := by
        have := cur.length_ineq
        omega
      split
      · rename_i hi1w
        have hi1lt : i1.val < cur.val.length := by scalar_tac
        step as ⟨shifted, hshifted⟩
        step as ⟨l, hl⟩
        have hsh1 : shifted.node.val < aig1.nodes.val.length := by
          have h1 := hcur shifted (by rw [hshifted]; exact List.getElem_mem _)
          have := hpre1.length_le
          omega
        have hl1 : l.node.val < aig1.nodes.val.length := by
          have h1 := hcur l (by rw [hl]; exact List.getElem_mem _)
          have := hpre1.length_le
          omega
        step with (push_mux_gadget aig1 sel shifted l hcap1 hsel1 hsh1 hl1)
          as ⟨m, aig2, hm1, hm2, hm3, hm4, hm5⟩
        step as ⟨next2, hnext2⟩
        step as ⟨i2, hi2⟩
        refine ⟨?_, by scalar_tac⟩
        rw [hi2]
        apply MuxMapInv.step ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩
          hilt hm1 hm2 hm3 hm4 ?_ hnext2
        intro inp
        simp only [hi1] at hshifted
        have hcond : i.val + s.val < cur.val.length := by scalar_tac
        rw [hm5 inp, pEvalLit_stable hpre1 sel hsel inp, hshifted, hl,
          pEvalLit_stable hpre1 _ (hcur _ (List.getElem_mem
            (show i.val + s.val < cur.val.length from hcond))) inp,
          pEvalLit_stable hpre1 _ (hcur _ (List.getElem_mem hilt)) inp,
          if_pos hcond, getD_eq_getElem_of_lt hcond,
          getD_eq_getElem_of_lt hilt]
      · rename_i hi1w
        step as ⟨l, hl⟩
        have hfl1 : fill.node.val < aig1.nodes.val.length := by
          have := hpre1.length_le
          omega
        have hl1 : l.node.val < aig1.nodes.val.length := by
          have h1 := hcur l (by rw [hl]; exact List.getElem_mem _)
          have := hpre1.length_le
          omega
        step with (push_mux_gadget aig1 sel fill l hcap1 hsel1 hfl1 hl1)
          as ⟨m, aig2, hm1, hm2, hm3, hm4, hm5⟩
        step as ⟨next2, hnext2⟩
        step as ⟨i2, hi2⟩
        refine ⟨?_, by scalar_tac⟩
        rw [hi2]
        apply MuxMapInv.step ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩
          hilt hm1 hm2 hm3 hm4 ?_ hnext2
        intro inp
        have hcond : ¬(i.val + s.val < cur.val.length) := by scalar_tac
        rw [hm5 inp, pEvalLit_stable hpre1 sel hsel inp, hl,
          pEvalLit_stable hpre1 fill hfill inp,
          pEvalLit_stable hpre1 _ (hcur _ (List.getElem_mem hilt)) inp,
          if_neg hcond, getD_eq_getElem_of_lt hilt]
    · rename_i hge
      have hieq : i.val = cur.val.length := by scalar_tac
      refine ⟨by dsimp only; omega, hpre1, by dsimp only; omega, hwf1,
        horng, ?_⟩
      intro inp j hj
      exact hsem inp j hj
  · exact MuxMapInv.init aig cur.val.length _

/-- **Spec of `barrel_left_stage`** (one left barrel round, shift by `s`,
    gated on `sel`): appends exactly 3 gates per bit; output bit `j` is
    `sel ? (s ≤ j ? cur[j - s] : FALSE) : cur[j]`. Requires node 0 to be the
    constant-FALSE node (the vacated low bits read `lit_false`). -/
theorem barrel_left_stage_spec (aig : Aig) (cur : Slice Lit) (sel : Lit)
    (s : Std.Usize)
    (hcap : aig.nodes.val.length + 3 * cur.val.length ≤ Usize.max)
    (hcur : ∀ l ∈ cur.val, l.node.val < aig.nodes.val.length)
    (hsel : sel.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False) :
    barrel_left_stage aig cur sel s ⦃ p =>
      p.1.val.length = cur.val.length ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.2.nodes.val.length = aig.nodes.val.length + 3 * cur.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ l ∈ p.1.val, l.node.val < p.2.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj : j < p.1.val.length),
        pEvalLit (pSim inp p.2.nodes.val) p.1.val[j]
          = if pEvalLit (pSim inp aig.nodes.val) sel
            then (if s.val ≤ j
              then pEvalLit (pSim inp aig.nodes.val)
                (cur.val.getD (j - s.val) dLit)
              else false)
            else pEvalLit (pSim inp aig.nodes.val)
              (cur.val.getD j dLit) ⦄ := by
  unfold barrel_left_stage barrel_left_stage_loop
  apply loop.spec_decr_nat
    (measure := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      cur.val.length - st.2.2.val)
    (inv := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      MuxMapInv aig cur.val.length
        (fun inp j =>
          if pEvalLit (pSim inp aig.nodes.val) sel
          then (if s.val ≤ j
            then pEvalLit (pSim inp aig.nodes.val)
              (cur.val.getD (j - s.val) dLit)
            else false)
          else pEvalLit (pSim inp aig.nodes.val) (cur.val.getD j dLit))
        st.1 st.2.1 st.2.2.val)
  · rintro ⟨aig1, next1, i⟩ hinv
    obtain ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩ := hinv
    dsimp only at hile hlen1 hpre1 hwf1 holen horng hsem
    unfold barrel_left_stage_loop.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < cur.val.length := by scalar_tac
      have hsel1 : sel.node.val < aig1.nodes.val.length := by
        have := hpre1.length_le
        omega
      have hcap1 : aig1.nodes.val.length + 3 ≤ Usize.max := by omega
      have hncap : next1.val.length < Usize.max := by
        have := cur.length_ineq
        omega
      split
      · rename_i hsi
        step as ⟨i1, hi1⟩
        have hi1lt : i1.val < cur.val.length := by scalar_tac
        step as ⟨shifted, hshifted⟩
        step as ⟨l, hl⟩
        have hsh1 : shifted.node.val < aig1.nodes.val.length := by
          have h1 := hcur shifted (by rw [hshifted]; exact List.getElem_mem _)
          have := hpre1.length_le
          omega
        have hl1 : l.node.val < aig1.nodes.val.length := by
          have h1 := hcur l (by rw [hl]; exact List.getElem_mem _)
          have := hpre1.length_le
          omega
        step with (push_mux_gadget aig1 sel shifted l hcap1 hsel1 hsh1 hl1)
          as ⟨m, aig2, hm1, hm2, hm3, hm4, hm5⟩
        step as ⟨next2, hnext2⟩
        step as ⟨i2, hi2⟩
        refine ⟨?_, by scalar_tac⟩
        rw [hi2]
        apply MuxMapInv.step ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩
          hilt hm1 hm2 hm3 hm4 ?_ hnext2
        intro inp
        simp only [hi1] at hshifted
        have hcond : s.val ≤ i.val := by scalar_tac
        have hsub : i.val - s.val < cur.val.length := by omega
        rw [hm5 inp, pEvalLit_stable hpre1 sel hsel inp, hshifted, hl,
          pEvalLit_stable hpre1 _ (hcur _ (List.getElem_mem hsub)) inp,
          pEvalLit_stable hpre1 _ (hcur _ (List.getElem_mem hilt)) inp,
          if_pos hcond, getD_eq_getElem_of_lt hsub,
          getD_eq_getElem_of_lt hilt]
      · rename_i hsi
        step with lit_false_spec as ⟨shifted, hshifted⟩
        step as ⟨l, hl⟩
        have hne1 : 0 < aig1.nodes.val.length := by
          have := hpre1.length_le
          omega
        have hsh1 : shifted.node.val < aig1.nodes.val.length := by
          rw [hshifted]
          scalar_tac
        have hl1 : l.node.val < aig1.nodes.val.length := by
          have h1 := hcur l (by rw [hl]; exact List.getElem_mem _)
          have := hpre1.length_le
          omega
        step with (push_mux_gadget aig1 sel shifted l hcap1 hsel1 hsh1 hl1)
          as ⟨m, aig2, hm1, hm2, hm3, hm4, hm5⟩
        step as ⟨next2, hnext2⟩
        step as ⟨i2, hi2⟩
        refine ⟨?_, by scalar_tac⟩
        rw [hi2]
        apply MuxMapInv.step ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩
          hilt hm1 hm2 hm3 hm4 ?_ hnext2
        intro inp
        have hcond : ¬(s.val ≤ i.val) := by scalar_tac
        have h01 : aig1.nodes.val[0]'hne1 = Node.False :=
          node0_of_prefix hpre1 hne h0 hne1
        rw [hm5 inp, pEvalLit_stable hpre1 sel hsel inp, hshifted,
          pEvalLit_node_zero hne1 h01 inp false, hl,
          pEvalLit_stable hpre1 _ (hcur _ (List.getElem_mem hilt)) inp,
          if_neg hcond, getD_eq_getElem_of_lt hilt]
    · rename_i hge
      have hieq : i.val = cur.val.length := by scalar_tac
      refine ⟨by dsimp only; omega, hpre1, by dsimp only; omega, hwf1,
        horng, ?_⟩
      intro inp j hj
      exact hsem inp j hj
  · exact MuxMapInv.init aig cur.val.length _

/-- **Spec of `rotr_stage`** (one rotate-right barrel round, rotate by `s`,
    gated on `sel`): appends exactly 3 gates per bit; output bit `j` is
    `sel ? cur[(j + s) % w] : cur[j]` — mod-width, no fill. -/
theorem rotr_stage_spec (aig : Aig) (cur : Slice Lit) (sel : Lit)
    (s : Std.Usize)
    (hcap : aig.nodes.val.length + 3 * cur.val.length ≤ Usize.max)
    (hadd : cur.val.length + s.val ≤ Usize.max)
    (hcur : ∀ l ∈ cur.val, l.node.val < aig.nodes.val.length)
    (hsel : sel.node.val < aig.nodes.val.length) :
    rotr_stage aig cur sel s ⦃ p =>
      p.1.val.length = cur.val.length ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.2.nodes.val.length = aig.nodes.val.length + 3 * cur.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ l ∈ p.1.val, l.node.val < p.2.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj : j < p.1.val.length),
        pEvalLit (pSim inp p.2.nodes.val) p.1.val[j]
          = if pEvalLit (pSim inp aig.nodes.val) sel
            then pEvalLit (pSim inp aig.nodes.val)
              (cur.val.getD ((j + s.val) % cur.val.length) dLit)
            else pEvalLit (pSim inp aig.nodes.val)
              (cur.val.getD j dLit) ⦄ := by
  unfold rotr_stage rotr_stage_loop
  apply loop.spec_decr_nat
    (measure := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      cur.val.length - st.2.2.val)
    (inv := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      MuxMapInv aig cur.val.length
        (fun inp j =>
          if pEvalLit (pSim inp aig.nodes.val) sel
          then pEvalLit (pSim inp aig.nodes.val)
            (cur.val.getD ((j + s.val) % cur.val.length) dLit)
          else pEvalLit (pSim inp aig.nodes.val) (cur.val.getD j dLit))
        st.1 st.2.1 st.2.2.val)
  · rintro ⟨aig1, next1, i⟩ hinv
    obtain ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩ := hinv
    dsimp only at hile hlen1 hpre1 hwf1 holen horng hsem
    unfold rotr_stage_loop.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < cur.val.length := by scalar_tac
      have hiadd : i.val + s.val ≤ Usize.max := by omega
      step as ⟨i1, hi1⟩
      step as ⟨src, hsrc⟩
      have hsrclt : src.val < cur.val.length := by
        rw [hsrc, hi1]
        exact Nat.mod_lt _ (by scalar_tac)
      step as ⟨l, hl⟩
      step as ⟨l1, hl1⟩
      have hsel1 : sel.node.val < aig1.nodes.val.length := by
        have := hpre1.length_le
        omega
      have hcap1 : aig1.nodes.val.length + 3 ≤ Usize.max := by omega
      have hncap : next1.val.length < Usize.max := by
        have := cur.length_ineq
        omega
      have hla : l.node.val < aig1.nodes.val.length := by
        have h1 := hcur l (by rw [hl]; exact List.getElem_mem _)
        have := hpre1.length_le
        omega
      have hlb : l1.node.val < aig1.nodes.val.length := by
        have h1 := hcur l1 (by rw [hl1]; exact List.getElem_mem _)
        have := hpre1.length_le
        omega
      step with (push_mux_gadget aig1 sel l l1 hcap1 hsel1 hla hlb)
        as ⟨m, aig2, hm1, hm2, hm3, hm4, hm5⟩
      step as ⟨next2, hnext2⟩
      step as ⟨i2, hi2⟩
      refine ⟨?_, by scalar_tac⟩
      rw [hi2]
      apply MuxMapInv.step ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩
        hilt hm1 hm2 hm3 hm4 ?_ hnext2
      intro inp
      have hsrcval : src.val = (i.val + s.val) % cur.val.length := by
        rw [hsrc, hi1]
        scalar_tac
      simp only [hsrcval] at hl
      rw [hm5 inp, pEvalLit_stable hpre1 sel hsel inp, hl, hl1,
        pEvalLit_stable hpre1 _ (hcur _ (List.getElem_mem
          (show (i.val + s.val) % cur.val.length < cur.val.length from
            Nat.mod_lt _ (by omega)))) inp,
        pEvalLit_stable hpre1 _ (hcur _ (List.getElem_mem hilt)) inp,
        getD_eq_getElem_of_lt (Nat.mod_lt _ (by omega)),
        getD_eq_getElem_of_lt hilt]
    · rename_i hge
      have hieq : i.val = cur.val.length := by scalar_tac
      refine ⟨by dsimp only; omega, hpre1, by dsimp only; omega, hwf1,
        horng, ?_⟩
      intro inp j hj
      exact hsem inp j hj
  · exact MuxMapInv.init aig cur.val.length _

/- ══════════════════ THE COPY LOOPS ══════════════════ -/

/-- First `barrel_right` loop: copies the whole input word (no gates). -/
theorem barrel_right_loop0_spec (a : Slice Lit) (out : alloc.vec.Vec Lit)
    (w : Std.Usize) (hw : w.val = a.val.length)
    (hcap : out.val.length + a.val.length ≤ Usize.max) :
    barrel_right_loop0 a out w 0#usize ⦃ r => r.val = out.val ++ a.val ⦄ := by
  unfold barrel_right_loop0
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      a.val.length - s.2.val)
    (inv := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      s.2.val ≤ a.val.length ∧
      s.1.val = out.val ++ a.val.take s.2.val)
  · rintro ⟨out1, i⟩ ⟨hle, hval⟩
    dsimp only at hle hval
    unfold barrel_right_loop0.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < a.val.length := by scalar_tac
      step as ⟨l, hl⟩
      have hocap : out1.val.length < Usize.max := by
        rw [hval]
        simp only [List.length_append, List.length_take]
        omega
      step as ⟨out2, hout2⟩
      step as ⟨i1, hi1⟩
      refine ⟨by scalar_tac, ?_, by scalar_tac⟩
      rw [hi1, hout2, hval, hl, List.take_add_one,
        List.getElem?_eq_getElem hilt]
      simp
    · rename_i hge
      have hieq : i.val = a.val.length := by scalar_tac
      have hfin : out1.val = out.val ++ a.val := by
        rw [hval, hieq, List.take_of_length_le (by simp)]
      exact hfin
  · exact ⟨Nat.zero_le _, by simp⟩

/-- First `blast_shl` loop: copies the whole input word (no gates). -/
theorem blast_shl_loop0_spec (a : Slice Lit) (out : alloc.vec.Vec Lit)
    (w : Std.Usize) (hw : w.val = a.val.length)
    (hcap : out.val.length + a.val.length ≤ Usize.max) :
    blast_shl_loop0 a out w 0#usize ⦃ r => r.val = out.val ++ a.val ⦄ := by
  unfold blast_shl_loop0
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      a.val.length - s.2.val)
    (inv := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      s.2.val ≤ a.val.length ∧
      s.1.val = out.val ++ a.val.take s.2.val)
  · rintro ⟨out1, i⟩ ⟨hle, hval⟩
    dsimp only at hle hval
    unfold blast_shl_loop0.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < a.val.length := by scalar_tac
      step as ⟨l, hl⟩
      have hocap : out1.val.length < Usize.max := by
        rw [hval]
        simp only [List.length_append, List.length_take]
        omega
      step as ⟨out2, hout2⟩
      step as ⟨i1, hi1⟩
      refine ⟨by scalar_tac, ?_, by scalar_tac⟩
      rw [hi1, hout2, hval, hl, List.take_add_one,
        List.getElem?_eq_getElem hilt]
      simp
    · rename_i hge
      have hieq : i.val = a.val.length := by scalar_tac
      have hfin : out1.val = out.val ++ a.val := by
        rw [hval, hieq, List.take_of_length_le (by simp)]
      exact hfin
  · exact ⟨Nat.zero_le _, by simp⟩

/-- First `blast_rotr` loop: copies the whole input word (no gates). -/
theorem blast_rotr_loop0_spec (a : Slice Lit) (out : alloc.vec.Vec Lit)
    (w : Std.Usize) (hw : w.val = a.val.length)
    (hcap : out.val.length + a.val.length ≤ Usize.max) :
    blast_rotr_loop0 a out w 0#usize ⦃ r => r.val = out.val ++ a.val ⦄ := by
  unfold blast_rotr_loop0
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      a.val.length - s.2.val)
    (inv := fun (s : alloc.vec.Vec Lit × Std.Usize) =>
      s.2.val ≤ a.val.length ∧
      s.1.val = out.val ++ a.val.take s.2.val)
  · rintro ⟨out1, i⟩ ⟨hle, hval⟩
    dsimp only at hle hval
    unfold blast_rotr_loop0.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < a.val.length := by scalar_tac
      step as ⟨l, hl⟩
      have hocap : out1.val.length < Usize.max := by
        rw [hval]
        simp only [List.length_append, List.length_take]
        omega
      step as ⟨out2, hout2⟩
      step as ⟨i1, hi1⟩
      refine ⟨by scalar_tac, ?_, by scalar_tac⟩
      rw [hi1, hout2, hval, hl, List.take_add_one,
        List.getElem?_eq_getElem hilt]
      simp
    · rename_i hge
      have hieq : i.val = a.val.length := by scalar_tac
      have hfin : out1.val = out.val ++ a.val := by
        rw [hval, hieq, List.take_of_length_le (by simp)]
      exact hfin
  · exact ⟨Nat.zero_le _, by simp⟩

/- ══════════════════ THE STAGE FOLDS (BARREL INVARIANT) ══════════════════ -/

/-- **The right-shift barrel invariant** (`barrel_right` stage fold): after
    all `stages` rounds, bit `j` of the current word equals bit
    `j + pAmt … stages` of the ORIGINAL word — the fill once past the
    end. Gate count: 3 gates per bit per round. -/
theorem barrel_right_loop1_spec (aig : Aig) (a b : Slice Lit)
    (stages : Std.Usize) (fill : Lit) (cur : alloc.vec.Vec Lit)
    (hcur : cur.val = a.val)
    (hstages : stages.val ≤ b.val.length)
    (hpow : 2 ^ stages.val = a.val.length)
    (hcap : aig.nodes.val.length + 3 * a.val.length * stages.val ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hfill : fill.node.val < aig.nodes.val.length) :
    barrel_right_loop1 aig b stages fill cur 0#usize ⦃ q =>
      q.1.nodes.val.length
        = aig.nodes.val.length + 3 * a.val.length * stages.val ∧
      aig.nodes.val <+: q.1.nodes.val ∧
      (∀ L, AigWF aig.nodes.val L → AigWF q.1.nodes.val L) ∧
      q.2.val.length = a.val.length ∧
      (∀ l ∈ q.2.val, l.node.val < q.1.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj : j < q.2.val.length),
        pEvalLit (pSim inp q.1.nodes.val) q.2.val[j]
          = if j + pAmt (pSim inp aig.nodes.val) b.val stages.val
              < a.val.length
            then pEvalLit (pSim inp aig.nodes.val)
              (a.val.getD
                (j + pAmt (pSim inp aig.nodes.val) b.val stages.val) dLit)
            else pEvalLit (pSim inp aig.nodes.val) fill ⦄ := by
  unfold barrel_right_loop1
  apply loop.spec_decr_nat
    (measure := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      stages.val - st.2.2.val)
    (inv := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      st.2.2.val ≤ stages.val ∧
      st.1.nodes.val.length
        = aig.nodes.val.length + 3 * a.val.length * st.2.2.val ∧
      aig.nodes.val <+: st.1.nodes.val ∧
      (∀ L, AigWF aig.nodes.val L → AigWF st.1.nodes.val L) ∧
      st.2.1.val.length = a.val.length ∧
      (∀ l ∈ st.2.1.val, l.node.val < st.1.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj : j < st.2.1.val.length),
        pEvalLit (pSim inp st.1.nodes.val) st.2.1.val[j]
          = if j + pAmt (pSim inp aig.nodes.val) b.val st.2.2.val
              < a.val.length
            then pEvalLit (pSim inp aig.nodes.val)
              (a.val.getD
                (j + pAmt (pSim inp aig.nodes.val) b.val st.2.2.val) dLit)
            else pEvalLit (pSim inp aig.nodes.val) fill)
  · rintro ⟨aig1, cur1, k⟩ hinv
    obtain ⟨hkle, hlen1, hpre1, hwf1, hclen, hcrng, hsem⟩ := hinv
    dsimp only at hkle hlen1 hpre1 hwf1 hclen hcrng hsem
    unfold barrel_right_loop1.body
    dsimp only
    split
    · rename_i hklt
      have hks : k.val < stages.val := by scalar_tac
      have hwle : 2 ^ stages.val ≤ Usize.max := by
        have := a.length_ineq
        omega
      have hkb : k.val < System.Platform.numBits := by
        have := lt_numBits_of_pow_le hwle
        omega
      step with (Usize.ShiftLeft_spec 1#usize k hkb) as ⟨s, hs, _⟩
      have hsval : s.val = 2 ^ k.val := by
        rw [hs]
        exact shl_one_val hkb
      have hderef : (alloc.vec.Vec.deref cur1).val = cur1.val := rfl
      have hbk : k.val < b.val.length := by omega
      step as ⟨selk, hselk⟩
      -- capacity for one stage
      have hstepc : 3 * a.val.length * (k.val + 1)
          = 3 * a.val.length * k.val + 3 * a.val.length := Nat.mul_succ _ _
      have hmul1 : 3 * a.val.length * (k.val + 1)
          ≤ 3 * a.val.length * stages.val :=
        Nat.mul_le_mul_left _ (by omega)
      have hcap1 : aig1.nodes.val.length
          + 3 * (alloc.vec.Vec.deref cur1).val.length ≤ Usize.max := by
        rw [hderef, hclen]
        omega
      -- the shift distance fits: 2^(k+1) ≤ 2^stages = |a|
      have hpowk : 2 ^ (k.val + 1) ≤ 2 ^ stages.val :=
        Nat.pow_le_pow_right (by omega) (by omega)
      have h2s : 2 ^ (k.val + 1) = 2 ^ k.val + 2 ^ k.val := by
        rw [Nat.pow_succ]; omega
      have hmul2 : 3 * a.val.length * 1 ≤ 3 * a.val.length * stages.val :=
        Nat.mul_le_mul_left _ (by omega)
      have hadd1 : (alloc.vec.Vec.deref cur1).val.length + s.val
          ≤ Usize.max := by
        rw [hderef, hclen, hsval]
        omega
      have hcur1 : ∀ l ∈ (alloc.vec.Vec.deref cur1).val,
          l.node.val < aig1.nodes.val.length := by
        rw [hderef]
        exact hcrng
      have hsel1 : selk.node.val < aig1.nodes.val.length := by
        have h1 := hb selk (by rw [hselk]; exact List.getElem_mem _)
        have := hpre1.length_le
        omega
      have hfill1 : fill.node.val < aig1.nodes.val.length := by
        have := hpre1.length_le
        omega
      step with (barrel_right_stage_spec aig1 (alloc.vec.Vec.deref cur1)
        selk s fill hcap1 hadd1 hcur1 hsel1 hfill1) as
        ⟨cur2, aig2, hs1, hs2, hs3, hs4, hs5, hs6⟩
      step as ⟨k1, hk1⟩
      simp only [hderef] at hs1 hs3 hs6
      refine ⟨by scalar_tac, ?_, hpre1.trans hs2,
        fun L hL => hs4 L (hwf1 L hL), by omega, hs5, ?_, by scalar_tac⟩
      · rw [hk1, hstepc]
        omega
      · intro inp j hj
        have hja : j < a.val.length := by omega
        have hjc : j < cur1.val.length := by omega
        rw [hs6 inp j hj, hk1]
        have hselval : pEvalLit (pSim inp aig1.nodes.val) selk
            = pEvalLit (pSim inp aig.nodes.val) (b.val[k.val]'hbk) := by
          rw [hselk]
          exact pEvalLit_stable hpre1 _ (hb _ (List.getElem_mem hbk)) inp
        have hfillval : pEvalLit (pSim inp aig1.nodes.val) fill
            = pEvalLit (pSim inp aig.nodes.val) fill :=
          pEvalLit_stable hpre1 fill hfill inp
        simp only [pAmt, getD_eq_getElem_of_lt hbk, hselval, hfillval,
          hsval, hclen]
        cases hbit : pEvalLit (pSim inp aig.nodes.val) (b.val[k.val]'hbk)
        · simp only [Bool.false_eq_true, if_false, Nat.add_zero]
          rw [getD_eq_getElem_of_lt hjc, hsem inp j hjc]
        · simp only [if_true]
          by_cases hjs : j + 2 ^ k.val < a.val.length
          · rw [if_pos hjs, getD_eq_getElem_of_lt (by omega),
              hsem inp _ (by omega)]
            have hidx : j + 2 ^ k.val
                  + pAmt (pSim inp aig.nodes.val) b.val k.val
                = j + (pAmt (pSim inp aig.nodes.val) b.val k.val
                  + 2 ^ k.val) := by omega
            rw [hidx]
          · rw [if_neg hjs, if_neg (by omega)]
    · rename_i hge
      have hkeq : k.val = stages.val := by scalar_tac
      rw [hkeq] at hlen1 hsem
      exact ⟨hlen1, hpre1, hwf1, hclen, hcrng, hsem⟩
  · refine ⟨by scalar_tac, by simp, List.prefix_refl _, fun _ h => h,
      by rw [hcur], ?_, ?_⟩
    · rw [hcur]
      exact ha
    · intro inp j hj
      rw [hcur] at hj
      have h00 : (0#usize).val = 0 := by scalar_tac
      simp only [hcur, h00, pAmt, Nat.add_zero]
      rw [if_pos (by scalar_tac), getD_eq_getElem_of_lt (by scalar_tac)]

/-- **The left-shift barrel invariant** (`blast_shl` stage fold): after all
    `stages` rounds, bit `j` of the current word equals bit
    `j - pAmt … stages` of the ORIGINAL word — FALSE below the amount. -/
theorem blast_shl_loop1_spec (aig : Aig) (a b : Slice Lit)
    (stages : Std.Usize) (cur : alloc.vec.Vec Lit)
    (hcur : cur.val = a.val)
    (hstages : stages.val ≤ b.val.length)
    (hpow : 2 ^ stages.val = a.val.length)
    (hcap : aig.nodes.val.length + 3 * a.val.length * stages.val ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False) :
    blast_shl_loop1 aig b stages cur 0#usize ⦃ q =>
      q.1.nodes.val.length
        = aig.nodes.val.length + 3 * a.val.length * stages.val ∧
      aig.nodes.val <+: q.1.nodes.val ∧
      (∀ L, AigWF aig.nodes.val L → AigWF q.1.nodes.val L) ∧
      q.2.val.length = a.val.length ∧
      (∀ l ∈ q.2.val, l.node.val < q.1.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj : j < q.2.val.length),
        pEvalLit (pSim inp q.1.nodes.val) q.2.val[j]
          = if pAmt (pSim inp aig.nodes.val) b.val stages.val ≤ j
            then pEvalLit (pSim inp aig.nodes.val)
              (a.val.getD
                (j - pAmt (pSim inp aig.nodes.val) b.val stages.val) dLit)
            else false ⦄ := by
  unfold blast_shl_loop1
  apply loop.spec_decr_nat
    (measure := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      stages.val - st.2.2.val)
    (inv := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      st.2.2.val ≤ stages.val ∧
      st.1.nodes.val.length
        = aig.nodes.val.length + 3 * a.val.length * st.2.2.val ∧
      aig.nodes.val <+: st.1.nodes.val ∧
      (∀ L, AigWF aig.nodes.val L → AigWF st.1.nodes.val L) ∧
      st.2.1.val.length = a.val.length ∧
      (∀ l ∈ st.2.1.val, l.node.val < st.1.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj : j < st.2.1.val.length),
        pEvalLit (pSim inp st.1.nodes.val) st.2.1.val[j]
          = if pAmt (pSim inp aig.nodes.val) b.val st.2.2.val ≤ j
            then pEvalLit (pSim inp aig.nodes.val)
              (a.val.getD
                (j - pAmt (pSim inp aig.nodes.val) b.val st.2.2.val) dLit)
            else false)
  · rintro ⟨aig1, cur1, k⟩ hinv
    obtain ⟨hkle, hlen1, hpre1, hwf1, hclen, hcrng, hsem⟩ := hinv
    dsimp only at hkle hlen1 hpre1 hwf1 hclen hcrng hsem
    unfold blast_shl_loop1.body
    dsimp only
    split
    · rename_i hklt
      have hks : k.val < stages.val := by scalar_tac
      have hwle : 2 ^ stages.val ≤ Usize.max := by
        have := a.length_ineq
        omega
      have hkb : k.val < System.Platform.numBits := by
        have := lt_numBits_of_pow_le hwle
        omega
      step with (Usize.ShiftLeft_spec 1#usize k hkb) as ⟨s, hs, _⟩
      have hsval : s.val = 2 ^ k.val := by
        rw [hs]
        exact shl_one_val hkb
      have hderef : (alloc.vec.Vec.deref cur1).val = cur1.val := rfl
      have hbk : k.val < b.val.length := by omega
      step as ⟨selk, hselk⟩
      have hstepc : 3 * a.val.length * (k.val + 1)
          = 3 * a.val.length * k.val + 3 * a.val.length := Nat.mul_succ _ _
      have hmul1 : 3 * a.val.length * (k.val + 1)
          ≤ 3 * a.val.length * stages.val :=
        Nat.mul_le_mul_left _ (by omega)
      have hcap1 : aig1.nodes.val.length
          + 3 * (alloc.vec.Vec.deref cur1).val.length ≤ Usize.max := by
        rw [hderef, hclen]
        omega
      have hcur1 : ∀ l ∈ (alloc.vec.Vec.deref cur1).val,
          l.node.val < aig1.nodes.val.length := by
        rw [hderef]
        exact hcrng
      have hsel1 : selk.node.val < aig1.nodes.val.length := by
        have h1 := hb selk (by rw [hselk]; exact List.getElem_mem _)
        have := hpre1.length_le
        omega
      have hne1 : 0 < aig1.nodes.val.length := by
        have := hpre1.length_le
        omega
      have h01 : aig1.nodes.val[0]'hne1 = Node.False :=
        node0_of_prefix hpre1 hne h0 hne1
      step with (barrel_left_stage_spec aig1 (alloc.vec.Vec.deref cur1)
        selk s hcap1 hcur1 hsel1 hne1 h01) as
        ⟨cur2, aig2, hs1, hs2, hs3, hs4, hs5, hs6⟩
      step as ⟨k1, hk1⟩
      simp only [hderef] at hs1 hs3 hs6
      refine ⟨by scalar_tac, ?_, hpre1.trans hs2,
        fun L hL => hs4 L (hwf1 L hL), by omega, hs5, ?_, by scalar_tac⟩
      · rw [hk1, hstepc]
        omega
      · intro inp j hj
        have hja : j < a.val.length := by omega
        have hjc : j < cur1.val.length := by omega
        rw [hs6 inp j hj, hk1]
        have hselval : pEvalLit (pSim inp aig1.nodes.val) selk
            = pEvalLit (pSim inp aig.nodes.val) (b.val[k.val]'hbk) := by
          rw [hselk]
          exact pEvalLit_stable hpre1 _ (hb _ (List.getElem_mem hbk)) inp
        simp only [pAmt, getD_eq_getElem_of_lt hbk, hselval, hsval]
        cases hbit : pEvalLit (pSim inp aig.nodes.val) (b.val[k.val]'hbk)
        · simp only [Bool.false_eq_true, if_false, Nat.add_zero]
          rw [getD_eq_getElem_of_lt hjc, hsem inp j hjc]
        · simp only [if_true]
          by_cases hjs : 2 ^ k.val ≤ j
          · have hsub : j - 2 ^ k.val < cur1.val.length := by omega
            rw [if_pos hjs, getD_eq_getElem_of_lt hsub,
              hsem inp _ hsub]
            by_cases hn : pAmt (pSim inp aig.nodes.val) b.val k.val
                ≤ j - 2 ^ k.val
            · rw [if_pos hn, if_pos (by omega)]
              have hidx : j - 2 ^ k.val
                    - pAmt (pSim inp aig.nodes.val) b.val k.val
                  = j - (pAmt (pSim inp aig.nodes.val) b.val k.val
                    + 2 ^ k.val) := by omega
              rw [hidx]
            · rw [if_neg hn, if_neg (by omega)]
          · rw [if_neg hjs, if_neg (by omega)]
    · rename_i hge
      have hkeq : k.val = stages.val := by scalar_tac
      rw [hkeq] at hlen1 hsem
      exact ⟨hlen1, hpre1, hwf1, hclen, hcrng, hsem⟩
  · refine ⟨by scalar_tac, by simp, List.prefix_refl _, fun _ h => h,
      by rw [hcur], ?_, ?_⟩
    · rw [hcur]
      exact ha
    · intro inp j hj
      rw [hcur] at hj
      have h00 : (0#usize).val = 0 := by scalar_tac
      simp only [hcur, h00, pAmt, Nat.sub_zero]
      rw [if_pos (Nat.zero_le _), getD_eq_getElem_of_lt (by scalar_tac)]

/-- **The rotate-right barrel invariant** (`blast_rotr` stage fold): after
    all `stages` rounds, bit `j` of the current word equals bit
    `(j + pAmt … stages) % w` of the ORIGINAL word — mod-width, no fill. -/
theorem blast_rotr_loop1_spec (aig : Aig) (a b : Slice Lit)
    (stages : Std.Usize) (cur : alloc.vec.Vec Lit)
    (hcur : cur.val = a.val)
    (hstages : stages.val ≤ b.val.length)
    (hpow : 2 ^ stages.val = a.val.length)
    (hcap : aig.nodes.val.length + 3 * a.val.length * stages.val ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length) :
    blast_rotr_loop1 aig b stages cur 0#usize ⦃ q =>
      q.2.nodes.val.length
        = aig.nodes.val.length + 3 * a.val.length * stages.val ∧
      aig.nodes.val <+: q.2.nodes.val ∧
      (∀ L, AigWF aig.nodes.val L → AigWF q.2.nodes.val L) ∧
      q.1.val.length = a.val.length ∧
      (∀ l ∈ q.1.val, l.node.val < q.2.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj : j < q.1.val.length),
        pEvalLit (pSim inp q.2.nodes.val) q.1.val[j]
          = pEvalLit (pSim inp aig.nodes.val)
              (a.val.getD
                ((j + pAmt (pSim inp aig.nodes.val) b.val stages.val)
                  % a.val.length) dLit) ⦄ := by
  unfold blast_rotr_loop1
  apply loop.spec_decr_nat
    (measure := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      stages.val - st.2.2.val)
    (inv := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      st.2.2.val ≤ stages.val ∧
      st.1.nodes.val.length
        = aig.nodes.val.length + 3 * a.val.length * st.2.2.val ∧
      aig.nodes.val <+: st.1.nodes.val ∧
      (∀ L, AigWF aig.nodes.val L → AigWF st.1.nodes.val L) ∧
      st.2.1.val.length = a.val.length ∧
      (∀ l ∈ st.2.1.val, l.node.val < st.1.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj : j < st.2.1.val.length),
        pEvalLit (pSim inp st.1.nodes.val) st.2.1.val[j]
          = pEvalLit (pSim inp aig.nodes.val)
              (a.val.getD
                ((j + pAmt (pSim inp aig.nodes.val) b.val st.2.2.val)
                  % a.val.length) dLit))
  · rintro ⟨aig1, cur1, k⟩ hinv
    obtain ⟨hkle, hlen1, hpre1, hwf1, hclen, hcrng, hsem⟩ := hinv
    dsimp only at hkle hlen1 hpre1 hwf1 hclen hcrng hsem
    unfold blast_rotr_loop1.body
    dsimp only
    split
    · rename_i hklt
      have hks : k.val < stages.val := by scalar_tac
      have haw : 0 < a.val.length := by
        have := Nat.two_pow_pos stages.val
        omega
      have hwle : 2 ^ stages.val ≤ Usize.max := by
        have := a.length_ineq
        omega
      have hkb : k.val < System.Platform.numBits := by
        have := lt_numBits_of_pow_le hwle
        omega
      step with (Usize.ShiftLeft_spec 1#usize k hkb) as ⟨s, hs, _⟩
      have hsval : s.val = 2 ^ k.val := by
        rw [hs]
        exact shl_one_val hkb
      have hderef : (alloc.vec.Vec.deref cur1).val = cur1.val := rfl
      have hbk : k.val < b.val.length := by omega
      step as ⟨selk, hselk⟩
      have hstepc : 3 * a.val.length * (k.val + 1)
          = 3 * a.val.length * k.val + 3 * a.val.length := Nat.mul_succ _ _
      have hmul1 : 3 * a.val.length * (k.val + 1)
          ≤ 3 * a.val.length * stages.val :=
        Nat.mul_le_mul_left _ (by omega)
      have hcap1 : aig1.nodes.val.length
          + 3 * (alloc.vec.Vec.deref cur1).val.length ≤ Usize.max := by
        rw [hderef, hclen]
        omega
      have hpowk : 2 ^ (k.val + 1) ≤ 2 ^ stages.val :=
        Nat.pow_le_pow_right (by omega) (by omega)
      have h2s : 2 ^ (k.val + 1) = 2 ^ k.val + 2 ^ k.val := by
        rw [Nat.pow_succ]; omega
      have hmul2 : 3 * a.val.length * 1 ≤ 3 * a.val.length * stages.val :=
        Nat.mul_le_mul_left _ (by omega)
      have hadd1 : (alloc.vec.Vec.deref cur1).val.length + s.val
          ≤ Usize.max := by
        rw [hderef, hclen, hsval]
        omega
      have hcur1 : ∀ l ∈ (alloc.vec.Vec.deref cur1).val,
          l.node.val < aig1.nodes.val.length := by
        rw [hderef]
        exact hcrng
      have hsel1 : selk.node.val < aig1.nodes.val.length := by
        have h1 := hb selk (by rw [hselk]; exact List.getElem_mem _)
        have := hpre1.length_le
        omega
      step with (rotr_stage_spec aig1 (alloc.vec.Vec.deref cur1)
        selk s hcap1 hadd1 hcur1 hsel1) as
        ⟨cur2, aig2, hs1, hs2, hs3, hs4, hs5, hs6⟩
      step as ⟨k1, hk1⟩
      simp only [hderef] at hs1 hs3 hs6
      refine ⟨by scalar_tac, ?_, hpre1.trans hs2,
        fun L hL => hs4 L (hwf1 L hL), by omega, hs5, ?_, by scalar_tac⟩
      · rw [hk1, hstepc]
        omega
      · intro inp j hj
        have hja : j < a.val.length := by omega
        have hjc : j < cur1.val.length := by omega
        rw [hs6 inp j hj, hk1]
        have hselval : pEvalLit (pSim inp aig1.nodes.val) selk
            = pEvalLit (pSim inp aig.nodes.val) (b.val[k.val]'hbk) := by
          rw [hselk]
          exact pEvalLit_stable hpre1 _ (hb _ (List.getElem_mem hbk)) inp
        simp only [pAmt, getD_eq_getElem_of_lt hbk, hselval, hsval, hclen]
        cases hbit : pEvalLit (pSim inp aig.nodes.val) (b.val[k.val]'hbk)
        · simp only [Bool.false_eq_true, if_false, Nat.add_zero]
          rw [getD_eq_getElem_of_lt hjc, hsem inp j hjc]
        · simp only [if_true]
          have hmlt : (j + 2 ^ k.val) % a.val.length < cur1.val.length := by
            have := Nat.mod_lt (j + 2 ^ k.val) haw
            omega
          rw [getD_eq_getElem_of_lt hmlt, hsem inp _ hmlt]
          have hmm : ((j + 2 ^ k.val) % a.val.length
                + pAmt (pSim inp aig.nodes.val) b.val k.val) % a.val.length
              = (j + (pAmt (pSim inp aig.nodes.val) b.val k.val
                + 2 ^ k.val)) % a.val.length := by
            rw [Nat.mod_add_mod]
            congr 1
            omega
          rw [hmm]
    · rename_i hge
      have hkeq : k.val = stages.val := by scalar_tac
      rw [hkeq] at hlen1 hsem
      exact ⟨hlen1, hpre1, hwf1, hclen, hcrng, hsem⟩
  · refine ⟨by scalar_tac, by simp, List.prefix_refl _, fun _ h => h,
      by rw [hcur], ?_, ?_⟩
    · rw [hcur]
      exact ha
    · intro inp j hj
      rw [hcur] at hj
      have h00 : (0#usize).val = 0 := by scalar_tac
      simp only [hcur, h00, pAmt, Nat.add_zero]
      rw [Nat.mod_eq_of_lt (by scalar_tac),
        getD_eq_getElem_of_lt (by scalar_tac)]

/- ══════════════════ THE FINAL FILL MUXES ══════════════════ -/

/-- Final `barrel_right` loop: muxes the fill over every bit, gated on the
    out-of-range literal (3 gates per bit). -/
theorem barrel_right_loop2_spec (aig : Aig) (fill : Lit)
    (cur : alloc.vec.Vec Lit) (w : Std.Usize) (oor : Lit)
    (hw : w.val = cur.val.length)
    (hcap : aig.nodes.val.length + 3 * cur.val.length ≤ Usize.max)
    (hcur : ∀ l ∈ cur.val, l.node.val < aig.nodes.val.length)
    (hoor : oor.node.val < aig.nodes.val.length)
    (hfill : fill.node.val < aig.nodes.val.length) :
    barrel_right_loop2 aig fill cur w oor (alloc.vec.Vec.new Lit) 0#usize ⦃ p =>
      p.1.val.length = cur.val.length ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.2.nodes.val.length = aig.nodes.val.length + 3 * cur.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ l ∈ p.1.val, l.node.val < p.2.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj : j < p.1.val.length),
        pEvalLit (pSim inp p.2.nodes.val) p.1.val[j]
          = if pEvalLit (pSim inp aig.nodes.val) oor
            then pEvalLit (pSim inp aig.nodes.val) fill
            else pEvalLit (pSim inp aig.nodes.val)
              (cur.val.getD j dLit) ⦄ := by
  unfold barrel_right_loop2
  apply loop.spec_decr_nat
    (measure := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      cur.val.length - st.2.2.val)
    (inv := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      MuxMapInv aig cur.val.length
        (fun inp j =>
          if pEvalLit (pSim inp aig.nodes.val) oor
          then pEvalLit (pSim inp aig.nodes.val) fill
          else pEvalLit (pSim inp aig.nodes.val) (cur.val.getD j dLit))
        st.1 st.2.1 st.2.2.val)
  · rintro ⟨aig1, out1, j⟩ hinv
    obtain ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩ := hinv
    dsimp only at hile hlen1 hpre1 hwf1 holen horng hsem
    unfold barrel_right_loop2.body
    dsimp only
    split
    · rename_i hlt
      have hjlt : j.val < cur.val.length := by scalar_tac
      step as ⟨l, hl⟩
      have hoor1 : oor.node.val < aig1.nodes.val.length := by
        have := hpre1.length_le
        omega
      have hfill1 : fill.node.val < aig1.nodes.val.length := by
        have := hpre1.length_le
        omega
      have hl1 : l.node.val < aig1.nodes.val.length := by
        have h1 := hcur l (by rw [hl]; exact List.getElem_mem _)
        have := hpre1.length_le
        omega
      have hcap1 : aig1.nodes.val.length + 3 ≤ Usize.max := by omega
      step with (push_mux_gadget aig1 oor fill l hcap1 hoor1 hfill1 hl1)
        as ⟨m, aig2, hm1, hm2, hm3, hm4, hm5⟩
      have hocap : out1.val.length < Usize.max := by
        have := cur.len_ineq
        omega
      step as ⟨out2, hout2⟩
      step as ⟨j1, hj1⟩
      refine ⟨?_, by scalar_tac⟩
      rw [hj1]
      apply MuxMapInv.step ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩
        hjlt hm1 hm2 hm3 hm4 ?_ hout2
      intro inp
      rw [hm5 inp, pEvalLit_stable hpre1 oor hoor inp,
        pEvalLit_stable hpre1 fill hfill inp, hl,
        pEvalLit_stable hpre1 _ (hcur _ (List.getElem_mem hjlt)) inp,
        getD_eq_getElem_of_lt hjlt]
    · rename_i hge
      have hjeq : j.val = cur.val.length := by scalar_tac
      refine ⟨by dsimp only; omega, hpre1, by dsimp only; omega, hwf1,
        horng, ?_⟩
      intro inp j' hj'
      exact hsem inp j' hj'
  · exact MuxMapInv.init aig cur.val.length _

/-- Final `blast_shl` loop: muxes the FALSE fill over every bit, gated on
    the out-of-range literal (3 gates per bit). -/
theorem blast_shl_loop2_spec (aig : Aig) (cur : alloc.vec.Vec Lit)
    (w : Std.Usize) (oor : Lit) (f : Lit)
    (hw : w.val = cur.val.length)
    (hcap : aig.nodes.val.length + 3 * cur.val.length ≤ Usize.max)
    (hcur : ∀ l ∈ cur.val, l.node.val < aig.nodes.val.length)
    (hoor : oor.node.val < aig.nodes.val.length)
    (hf : f.node.val < aig.nodes.val.length) :
    blast_shl_loop2 aig cur w oor f (alloc.vec.Vec.new Lit) 0#usize ⦃ p =>
      p.1.val.length = cur.val.length ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.2.nodes.val.length = aig.nodes.val.length + 3 * cur.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ l ∈ p.1.val, l.node.val < p.2.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj : j < p.1.val.length),
        pEvalLit (pSim inp p.2.nodes.val) p.1.val[j]
          = if pEvalLit (pSim inp aig.nodes.val) oor
            then pEvalLit (pSim inp aig.nodes.val) f
            else pEvalLit (pSim inp aig.nodes.val)
              (cur.val.getD j dLit) ⦄ := by
  unfold blast_shl_loop2
  apply loop.spec_decr_nat
    (measure := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      cur.val.length - st.2.2.val)
    (inv := fun (st : Aig × alloc.vec.Vec Lit × Std.Usize) =>
      MuxMapInv aig cur.val.length
        (fun inp j =>
          if pEvalLit (pSim inp aig.nodes.val) oor
          then pEvalLit (pSim inp aig.nodes.val) f
          else pEvalLit (pSim inp aig.nodes.val) (cur.val.getD j dLit))
        st.1 st.2.1 st.2.2.val)
  · rintro ⟨aig1, out1, j⟩ hinv
    obtain ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩ := hinv
    dsimp only at hile hlen1 hpre1 hwf1 holen horng hsem
    unfold blast_shl_loop2.body
    dsimp only
    split
    · rename_i hlt
      have hjlt : j.val < cur.val.length := by scalar_tac
      step as ⟨l, hl⟩
      have hoor1 : oor.node.val < aig1.nodes.val.length := by
        have := hpre1.length_le
        omega
      have hf1 : f.node.val < aig1.nodes.val.length := by
        have := hpre1.length_le
        omega
      have hl1 : l.node.val < aig1.nodes.val.length := by
        have h1 := hcur l (by rw [hl]; exact List.getElem_mem _)
        have := hpre1.length_le
        omega
      have hcap1 : aig1.nodes.val.length + 3 ≤ Usize.max := by omega
      step with (push_mux_gadget aig1 oor f l hcap1 hoor1 hf1 hl1)
        as ⟨m, aig2, hm1, hm2, hm3, hm4, hm5⟩
      have hocap : out1.val.length < Usize.max := by
        have := cur.len_ineq
        omega
      step as ⟨out2, hout2⟩
      step as ⟨j1, hj1⟩
      refine ⟨?_, by scalar_tac⟩
      rw [hj1]
      apply MuxMapInv.step ⟨hile, hlen1, hpre1, hwf1, holen, horng, hsem⟩
        hjlt hm1 hm2 hm3 hm4 ?_ hout2
      intro inp
      rw [hm5 inp, pEvalLit_stable hpre1 oor hoor inp,
        pEvalLit_stable hpre1 f hf inp, hl,
        pEvalLit_stable hpre1 _ (hcur _ (List.getElem_mem hjlt)) inp,
        getD_eq_getElem_of_lt hjlt]
    · rename_i hge
      have hjeq : j.val = cur.val.length := by scalar_tac
      refine ⟨by dsimp only; omega, hpre1, by dsimp only; omega, hwf1,
        horng, ?_⟩
      intro inp j' hj'
      exact hsem inp j' hj'
  · exact MuxMapInv.init aig cur.val.length _

/- ══════════════════ COMPOSITION: `barrel_right` ══════════════════ -/

/-- Transporting `Denotes` back along append-monotonicity: a word denoting
    `V` under the EXTENDED aig's simulation also denotes `V` under the
    original aig's simulation (all its literals are pre-existing). -/
theorem Denotes.of_prefix {ns ns' : List Node} (hpre : ns <+: ns')
    {word : List Lit} {w : Nat} {V : BitVec w}
    (hrng : ∀ l ∈ word, l.node.val < ns.length) (inp : List Bool)
    (h : Denotes (pSim inp ns') word w V) :
    Denotes (pSim inp ns) word w V := by
  obtain ⟨hlen, hj⟩ := h
  refine ⟨hlen, fun j hjl => ?_⟩
  rw [← pEvalLit_stable hpre _ (hrng _ (List.getElem_mem _)) inp]
  exact hj j hjl

/-- **Spec of `barrel_right`** (the shared right-shift skeleton,
    parameterized by the fill literal): gate count
    `3·w·stages + (|b| - stages) + 3·w`; output bit `j` is the fill if the
    amount is out of range, else bit `j + pAmt … stages` of the input word
    (the fill past the end), everything under the ORIGINAL aig. -/
theorem barrel_right_spec (aig : Aig) (a b : Slice Lit) (stages : Std.Usize)
    (fill : Lit)
    (hstages : stages.val ≤ b.val.length)
    (hpow : 2 ^ stages.val = a.val.length)
    (hcap : aig.nodes.val.length + (3 * a.val.length * stages.val
      + (b.val.length - stages.val) + 3 * a.val.length) ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hfill : fill.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False) :
    barrel_right aig a b stages fill ⦃ p =>
      p.1.val.length = a.val.length ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.2.nodes.val.length = aig.nodes.val.length
        + (3 * a.val.length * stages.val + (b.val.length - stages.val)
          + 3 * a.val.length) ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ l ∈ p.1.val, l.node.val < p.2.nodes.val.length) ∧
      ∀ (inp : List Bool) (j : Nat) (hj : j < p.1.val.length),
        pEvalLit (pSim inp p.2.nodes.val) p.1.val[j]
          = if pHigh (pSim inp aig.nodes.val) b.val stages.val b.val.length
            then pEvalLit (pSim inp aig.nodes.val) fill
            else if j + pAmt (pSim inp aig.nodes.val) b.val stages.val
                < a.val.length
              then pEvalLit (pSim inp aig.nodes.val)
                (a.val.getD
                  (j + pAmt (pSim inp aig.nodes.val) b.val stages.val) dLit)
              else pEvalLit (pSim inp aig.nodes.val) fill ⦄ := by
  unfold barrel_right
  step with (barrel_right_loop0_spec a (alloc.vec.Vec.new Lit)
    (Slice.len a) (by scalar_tac) (by simp; scalar_tac)) as ⟨cur, hcurv⟩
  have hcur : cur.val = a.val := by
    rw [hcurv]
    simp
  step with (barrel_right_loop1_spec aig a b stages fill cur hcur hstages
    hpow (by omega) ha hb hfill) as
    ⟨aig1, cur1, h11, h12, h13, h14, h15, h16⟩
  have hb1 : ∀ l ∈ b.val, l.node.val < aig1.nodes.val.length := by
    intro l hl
    have := hb l hl
    have := h12.length_le
    omega
  have hne1 : 0 < aig1.nodes.val.length := by
    have := h12.length_le
    omega
  have h01 : aig1.nodes.val[0]'hne1 = Node.False :=
    node0_of_prefix h12 hne h0 hne1
  step with (out_of_range_spec aig1 b stages hstages (by omega) hb1
    hne1 h01) as ⟨oor, aig2, ho1, ho2, ho3, ho4, ho5⟩
  have hcur2 : ∀ l ∈ cur1.val, l.node.val < aig2.nodes.val.length := by
    intro l hl
    have := h15 l hl
    have := ho2.length_le
    omega
  have hfill2 : fill.node.val < aig2.nodes.val.length := by
    have := h12.length_le
    have := ho2.length_le
    omega
  apply WP.spec_mono (barrel_right_loop2_spec aig2 fill cur1
    (Slice.len a) oor (by rw [h14]; scalar_tac) (by omega) hcur2 ho4 hfill2)
  rintro ⟨out, aig3⟩ ⟨hf1, hf2, hf3, hf4, hf5, hf6⟩
  refine ⟨by omega, h12.trans (ho2.trans hf2), by omega,
    fun L hL => hf4 L (ho3 L (h13 L hL)), hf5, ?_⟩
  intro inp j hj
  have hjc : j < cur1.val.length := by omega
  rw [hf6 inp j hj, ho5 inp,
    pHigh_stable h12 hb inp stages.val b.val.length (Nat.le_refl _),
    pEvalLit_stable (h12.trans ho2) fill hfill inp,
    getD_eq_getElem_of_lt hjc,
    pEvalLit_stable ho2 _ (h15 _ (List.getElem_mem hjc)) inp,
    h16 inp j hjc]

/- ══════════════════ HEADLINE: `blast_lshr` ══════════════════ -/

/-- **`blast_lshr` implements SMT-LIB `bvlshr` (`BitVec` `>>>`), for every
    width `w = 2^stages`**: if the input words denote `A` and `B` under the
    post-blast simulation, the output word denotes `A >>> B.toNat`. Core's
    `>>>` on `Nat` amounts already yields `0` for amounts `≥ w`
    (`getLsbD_ushiftRight` reads past the width), matching SMT-LIB. -/
theorem blast_lshr_bitvec (aig : Aig) (a b : Slice Lit) (stages : Std.Usize)
    (hstages : stages.val ≤ b.val.length)
    (hpow : 2 ^ stages.val = a.val.length)
    (hcap : aig.nodes.val.length + (3 * a.val.length * stages.val
      + (b.val.length - stages.val) + 3 * a.val.length) ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (A B : BitVec w) :
    blast_lshr aig a b stages ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          Denotes vals.val p.1.val w (A >>> B.toNat) ⦄ ⦄ := by
  unfold blast_lshr
  step with lit_false_spec as ⟨f, hf⟩
  have hfnode : f.node.val < aig.nodes.val.length := by
    rw [hf]
    scalar_tac
  apply WP.spec_mono (barrel_right_spec aig a b stages f hstages hpow hcap
    ha hb hfnode hne h0)
  rintro ⟨out, aig1⟩ ⟨hL1, hL2, hL3, hL4, hL5, hL6⟩
  intro inputs hwf
  apply WP.spec_mono (simulate_spec aig1 inputs (hL4 _ hwf))
  intro vals hv hA hB
  rw [hv] at hA hB ⊢
  have hA0 : Denotes (pSim inputs.val aig.nodes.val) a.val w A :=
    hA.of_prefix hL2 ha inputs.val
  have hB0 : Denotes (pSim inputs.val aig.nodes.val) b.val w B :=
    hB.of_prefix hL2 hb inputs.val
  have hal : a.val.length = w := hA0.1
  have hbl : b.val.length = w := hB0.1
  refine ⟨by omega, fun j hj => ?_⟩
  have hja : j < a.val.length := by omega
  have hfv : pEvalLit (pSim inputs.val aig.nodes.val) f = false := by
    rw [hf]
    exact pEvalLit_node_zero hne h0 inputs.val false
  rw [hL6 inputs.val j hj, hbl,
    pHigh_eq_decide hB0 (show stages.val ≤ w by omega),
    pAmt_eq_mod hB0 stages.val (by omega), hfv]
  by_cases hge : 2 ^ stages.val ≤ B.toNat
  · rw [if_pos (decide_eq_true hge), BitVec.getLsbD_ushiftRight,
      BitVec.getLsbD_of_ge A _ (by omega)]
  · rw [if_neg (by simp only [decide_eq_true_eq]; exact hge),
      Nat.mod_eq_of_lt (by omega), BitVec.getLsbD_ushiftRight]
    by_cases hjn : j + B.toNat < a.val.length
    · rw [if_pos hjn, getD_eq_getElem_of_lt hjn, hA0.2 _ hjn]
      congr 1
      omega
    · rw [if_neg hjn, BitVec.getLsbD_of_ge A _ (by omega)]

/- ══════════════════ HEADLINE: `blast_ashr` ══════════════════ -/

/-- **`blast_ashr` implements SMT-LIB `bvashr` (`BitVec.sshiftRight`), for
    every width `w = 2^stages`**: the output word denotes
    `A.sshiftRight B.toNat`. Core's `sshiftRight` saturates to the sign bit
    for amounts `≥ w` (`getLsbD_sshiftRight`), matching SMT-LIB. -/
theorem blast_ashr_bitvec (aig : Aig) (a b : Slice Lit) (stages : Std.Usize)
    (hstages : stages.val ≤ b.val.length)
    (hpow : 2 ^ stages.val = a.val.length)
    (hcap : aig.nodes.val.length + (3 * a.val.length * stages.val
      + (b.val.length - stages.val) + 3 * a.val.length) ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (A B : BitVec w) :
    blast_ashr aig a b stages ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          Denotes vals.val p.1.val w (A.sshiftRight B.toNat) ⦄ ⦄ := by
  unfold blast_ashr
  have hw0 : 0 < a.val.length := by
    have := Nat.two_pow_pos stages.val
    omega
  step as ⟨i1, hi1⟩
  have hi1v : i1.val = a.val.length - 1 := by scalar_tac
  have hi1lt : i1.val < a.val.length := by omega
  step as ⟨sign, hsign⟩
  have hsnode : sign.node.val < aig.nodes.val.length := by
    have := ha sign (by rw [hsign]; exact List.getElem_mem _)
    omega
  apply WP.spec_mono (barrel_right_spec aig a b stages sign hstages hpow
    hcap ha hb hsnode hne h0)
  rintro ⟨out, aig1⟩ ⟨hL1, hL2, hL3, hL4, hL5, hL6⟩
  intro inputs hwf
  apply WP.spec_mono (simulate_spec aig1 inputs (hL4 _ hwf))
  intro vals hv hA hB
  rw [hv] at hA hB ⊢
  have hA0 : Denotes (pSim inputs.val aig.nodes.val) a.val w A :=
    hA.of_prefix hL2 ha inputs.val
  have hB0 : Denotes (pSim inputs.val aig.nodes.val) b.val w B :=
    hB.of_prefix hL2 hb inputs.val
  have hal : a.val.length = w := hA0.1
  have hbl : b.val.length = w := hB0.1
  have hwpos : 0 < w := by omega
  have hfv : pEvalLit (pSim inputs.val aig.nodes.val) sign = A.msb := by
    simp only [hi1v] at hsign
    rw [hsign, hA0.2 _ (by omega), BitVec.msb_eq_getLsbD_last, hal]
  refine ⟨by omega, fun j hj => ?_⟩
  have hja : j < a.val.length := by omega
  have hjw : j < w := by omega
  rw [hL6 inputs.val j hj, hbl,
    pHigh_eq_decide hB0 (show stages.val ≤ w by omega),
    pAmt_eq_mod hB0 stages.val (by omega), hfv,
    BitVec.getLsbD_sshiftRight, decide_eq_false (show ¬(w ≤ j) by omega),
    Bool.not_false, Bool.true_and]
  by_cases hge : 2 ^ stages.val ≤ B.toNat
  · rw [if_pos (decide_eq_true hge), if_neg (by omega)]
  · rw [if_neg (by simp only [decide_eq_true_eq]; exact hge),
      Nat.mod_eq_of_lt (by omega)]
    by_cases hjn : j + B.toNat < a.val.length
    · rw [if_pos hjn, if_pos (by omega), getD_eq_getElem_of_lt hjn,
        hA0.2 _ hjn]
      congr 1
      omega
    · rw [if_neg hjn, if_neg (by omega)]

/- ══════════════════ HEADLINE: `blast_shl` ══════════════════ -/

/-- **`blast_shl` implements SMT-LIB `bvshl` (`BitVec` `<<<`), for every
    width `w = 2^stages`**: the output word denotes `A <<< B.toNat`. Core's
    `<<<` on `Nat` amounts already yields `0` for amounts `≥ w` (the
    `decide (i < n)` guard in `getLsbD_shiftLeft`), matching SMT-LIB. -/
theorem blast_shl_bitvec (aig : Aig) (a b : Slice Lit) (stages : Std.Usize)
    (hstages : stages.val ≤ b.val.length)
    (hpow : 2 ^ stages.val = a.val.length)
    (hcap : aig.nodes.val.length + (3 * a.val.length * stages.val
      + (b.val.length - stages.val) + 3 * a.val.length) ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (A B : BitVec w) :
    blast_shl aig a b stages ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          Denotes vals.val p.1.val w (A <<< B.toNat) ⦄ ⦄ := by
  unfold blast_shl
  step with (blast_shl_loop0_spec a (alloc.vec.Vec.new Lit)
    (Slice.len a) (by scalar_tac) (by simp; scalar_tac)) as ⟨cur, hcurv⟩
  have hcur : cur.val = a.val := by
    rw [hcurv]
    simp
  step with (blast_shl_loop1_spec aig a b stages cur hcur hstages
    hpow (by omega) ha hb hne h0) as
    ⟨aig1, cur1, h11, h12, h13, h14, h15, h16⟩
  have hb1 : ∀ l ∈ b.val, l.node.val < aig1.nodes.val.length := by
    intro l hl
    have := hb l hl
    have := h12.length_le
    omega
  have hne1 : 0 < aig1.nodes.val.length := by
    have := h12.length_le
    omega
  have h01 : aig1.nodes.val[0]'hne1 = Node.False :=
    node0_of_prefix h12 hne h0 hne1
  step with (out_of_range_spec aig1 b stages hstages (by omega) hb1
    hne1 h01) as ⟨oor, aig2, ho1, ho2, ho3, ho4, ho5⟩
  step with lit_false_spec as ⟨f, hf⟩
  have hne2 : 0 < aig2.nodes.val.length := by
    have := ho2.length_le
    omega
  have h02 : aig2.nodes.val[0]'hne2 = Node.False :=
    node0_of_prefix ho2 hne1 h01 hne2
  have hfnode : f.node.val < aig2.nodes.val.length := by
    rw [hf]
    scalar_tac
  have hcur2 : ∀ l ∈ cur1.val, l.node.val < aig2.nodes.val.length := by
    intro l hl
    have := h15 l hl
    have := ho2.length_le
    omega
  apply WP.spec_mono (blast_shl_loop2_spec aig2 cur1 (Slice.len a) oor f
    (by rw [h14]; scalar_tac) (by omega) hcur2 ho4 hfnode)
  rintro ⟨out, aig3⟩ ⟨hf1, hf2, hf3, hf4, hf5, hf6⟩
  intro inputs hwf
  apply WP.spec_mono (simulate_spec aig3 inputs
    (hf4 _ (ho3 _ (h13 _ hwf))))
  intro vals hv hA hB
  rw [hv] at hA hB ⊢
  have hpre02 : aig.nodes.val <+: aig2.nodes.val := h12.trans ho2
  have hA0 : Denotes (pSim inputs.val aig.nodes.val) a.val w A :=
    hA.of_prefix (hpre02.trans hf2) ha inputs.val
  have hB0 : Denotes (pSim inputs.val aig.nodes.val) b.val w B :=
    hB.of_prefix (hpre02.trans hf2) hb inputs.val
  have hal : a.val.length = w := hA0.1
  have hbl : b.val.length = w := hB0.1
  refine ⟨by omega, fun j hj => ?_⟩
  have hja : j < a.val.length := by omega
  have hjw : j < w := by omega
  have hjc : j < cur1.val.length := by omega
  have hfv : pEvalLit (pSim inputs.val aig2.nodes.val) f = false := by
    rw [hf]
    exact pEvalLit_node_zero hne2 h02 inputs.val false
  rw [hf6 inputs.val j hj, ho5 inputs.val,
    pHigh_stable h12 hb inputs.val stages.val b.val.length (Nat.le_refl _),
    hfv, getD_eq_getElem_of_lt hjc,
    pEvalLit_stable ho2 _ (h15 _ (List.getElem_mem hjc)) inputs.val,
    h16 inputs.val j hjc, hbl,
    pHigh_eq_decide hB0 (show stages.val ≤ w by omega),
    pAmt_eq_mod hB0 stages.val (by omega),
    BitVec.getLsbD_shiftLeft, decide_eq_true hjw, Bool.true_and]
  by_cases hge : 2 ^ stages.val ≤ B.toNat
  · rw [if_pos (decide_eq_true hge),
      decide_eq_true (show j < B.toNat by omega)]
    simp
  · rw [if_neg (by simp only [decide_eq_true_eq]; exact hge),
      Nat.mod_eq_of_lt (by omega)]
    by_cases hjn : B.toNat ≤ j
    · rw [if_pos hjn, decide_eq_false (show ¬(j < B.toNat) by omega),
        Bool.not_false, Bool.true_and,
        getD_eq_getElem_of_lt (show j - B.toNat < a.val.length by omega),
        hA0.2 _ (by omega)]
    · rw [if_neg hjn, decide_eq_true (show j < B.toNat by omega)]
      simp

/- ══════════════════ HEADLINE: `blast_rotr` ══════════════════ -/

/-- **`blast_rotr` implements SMT-LIB `rotate_right`
    (`BitVec.rotateRight`), for every width `w = 2^stages`**: the output
    word denotes `A.rotateRight (B.toNat % w)` — only the low `stages` bits
    of the amount matter, mod-width semantics, no out-of-range fill. -/
theorem blast_rotr_bitvec (aig : Aig) (a b : Slice Lit) (stages : Std.Usize)
    (hstages : stages.val ≤ b.val.length)
    (hpow : 2 ^ stages.val = a.val.length)
    (hcap : aig.nodes.val.length + 3 * a.val.length * stages.val
      ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    {w : Nat} (A B : BitVec w) :
    blast_rotr aig a b stages ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          Denotes vals.val p.1.val w (A.rotateRight (B.toNat % w)) ⦄ ⦄ := by
  unfold blast_rotr
  step with (blast_rotr_loop0_spec a (alloc.vec.Vec.new Lit)
    (Slice.len a) (by scalar_tac) (by simp; scalar_tac)) as ⟨cur, hcurv⟩
  have hcur : cur.val = a.val := by
    rw [hcurv]
    simp
  apply WP.spec_mono (blast_rotr_loop1_spec aig a b stages cur hcur hstages
    hpow hcap ha hb)
  rintro ⟨out, aig1⟩ ⟨h11, h12, h13, h14, h15, h16⟩
  intro inputs hwf
  apply WP.spec_mono (simulate_spec aig1 inputs (h13 _ hwf))
  intro vals hv hA hB
  rw [hv] at hA hB ⊢
  have hA0 : Denotes (pSim inputs.val aig.nodes.val) a.val w A :=
    hA.of_prefix h12 ha inputs.val
  have hB0 : Denotes (pSim inputs.val aig.nodes.val) b.val w B :=
    hB.of_prefix h12 hb inputs.val
  have hal : a.val.length = w := hA0.1
  have hbl : b.val.length = w := hB0.1
  have hwpos : 0 < w := by
    have := Nat.two_pow_pos stages.val
    omega
  have hr : B.toNat % w < w := Nat.mod_lt _ hwpos
  have hrot : ∀ i : Nat, i < w →
      (A.rotateRight (B.toNat % w)).getLsbD i
        = A.getLsbD ((i + B.toNat % w) % w) := by
    intro i hi
    rw [BitVec.getLsbD_rotateRight, Nat.mod_eq_of_lt hr]
    by_cases hc : i < w - B.toNat % w
    · have hlt : i + B.toNat % w < w := by omega
      have hmod : (i + B.toNat % w) % w = i + B.toNat % w :=
        Nat.mod_eq_of_lt hlt
      rw [decide_eq_true hc, cond_true, hmod]
      congr 1
      omega
    · have hge : w ≤ i + B.toNat % w := by omega
      have hlt2 : i + B.toNat % w - w < w := by omega
      have hmod : (i + B.toNat % w) % w = i + B.toNat % w - w := by
        rw [Nat.mod_eq_sub_mod hge]
        exact Nat.mod_eq_of_lt hlt2
      rw [decide_eq_false hc, cond_false, decide_eq_true hi,
        Bool.true_and, hmod]
      congr 1
      omega
  refine ⟨by omega, fun j hj => ?_⟩
  have hja : j < a.val.length := by omega
  have hjw : j < w := by omega
  have hmlt : (j + pAmt (pSim inputs.val aig.nodes.val) b.val stages.val)
      % a.val.length < a.val.length := Nat.mod_lt _ (by omega)
  rw [h16 inputs.val j hj, getD_eq_getElem_of_lt hmlt, hA0.2 _ hmlt,
    hrot j hjw]
  congr 1
  rw [pAmt_eq_mod hB0 stages.val (by omega), hpow, hal]

end blast_kernel.spec
