/- Satisfiability preservation of the model Tseitin encoder (issue #192,
   phase 1 / v0.25.0).

   This file is HAND-WRITTEN (BlastKernel.lean is generated by regen.sh and
   must not be edited). It proves, for the Aeneas model of
   `blast_kernel::tseitin` — which mirrors the shipped `cnf::tseitin` clause
   for clause (pinned by `tseitin_matches_cnf_rs_*` in blast_kernel.rs) —
   the direction an UNSAT verdict needs:

     if some input assignment makes every asserted output literal true,
     the generated CNF is SATISFIABLE — in fact the simulation values
     themselves satisfy it (DIMACS variable `v` := AIG node `v - 1`).

   Contrapositive: a refuted CNF (what `lrat_check_sound` establishes from an
   accepted certificate) means NO input assignment satisfies the asserted
   outputs. `tseitin_refutes_outputs` states exactly that composition over
   the kernel's own `unsat` (Sound.lean), so the two proven halves meet in
   one theorem: `check_steps` accepts ⟹ the encoded AIG outputs are
   unsatisfiable.

   The CNF semantics are REUSED from Sound.lean (`litHolds` / `clauseHolds`
   / `cnfHolds` / `unsat` over `Std.I32` DIMACS literals): the encoder's
   output is judged by the same meaning the checker's soundness theorem is
   stated in, so nothing is lost at the seam. -/
import BlastKernel
import BlasterProof
import Sound

open Aeneas Aeneas.Std Result

set_option maxHeartbeats 1000000

namespace blast_kernel.spec

open kernel.spec (Asn litVar litHolds clauseHolds cnfHolds unsat)

/- ══════════════════ THE SIMULATION AS A DIMACS ASSIGNMENT ══════════════════ -/

/-- The assignment the Tseitin CNF inherits from a simulation: DIMACS
    variable `v` is the value of AIG node `v - 1` (CNF variable `node + 1`,
    exactly `cnf_lit` / `cnf::TseitinMap::cnf_lit`). -/
def simAsn (vals : List Bool) : Asn := fun v => vals.getD (v - 1) false

/- ══════════════════ READING ONE NODE OF THE PURE SIMULATION ══════════════════ -/

/-- Node `i`'s simulated value is its `pNodeVal` over the simulation of the
    nodes before it. -/
theorem pSim_getD_eq (inp : List Bool) (ns : List Node) (i : Nat)
    (hi : i < ns.length) :
    (pSim inp ns).getD i false = pNodeVal inp (pSim inp (ns.take i)) ns[i] := by
  have htake : ns.take (i + 1) = ns.take i ++ [ns[i]] := by
    rw [List.take_add_one, List.getElem?_eq_getElem hi]
    simp
  have hpre : ns.take (i + 1) <+: ns := List.take_prefix _ _
  have hlen : i < (pSim inp (ns.take (i + 1))).length := by
    rw [pSim_length, List.length_take]
    omega
  rw [getD_of_prefix (pSim_prefix_of_prefix inp hpre) hlen, htake, pSim_snoc]
  have hl : (pSim inp (ns.take i)).length = i := by
    rw [pSim_length, List.length_take]
    omega
  have hsnoc := getD_snoc_length (pSim inp (ns.take i))
    (pNodeVal inp (pSim inp (ns.take i)) ns[i]) false
  rw [hl] at hsnoc
  exact hsnoc

/-- An AND node's simulated value is the conjunction of its children's
    literal values under the FULL simulation (append-monotonicity moves the
    children's reads from the prefix to the whole list). -/
theorem pSim_getD_and (inp : List Bool) (ns : List Node) (i : Nat)
    (hi : i < ns.length) (x y : Lit) (hnd : ns[i] = Node.And x y)
    (hx : x.node.val < i) (hy : y.node.val < i) :
    (pSim inp ns).getD i false
      = (pEvalLit (pSim inp ns) x && pEvalLit (pSim inp ns) y) := by
  rw [pSim_getD_eq inp ns i hi, hnd]
  simp only [pNodeVal]
  have hpre : ns.take i <+: ns := List.take_prefix _ _
  have hlt : (ns.take i).length = i := by
    rw [List.length_take]
    omega
  rw [pEvalLit_stable hpre x (by omega) inp, pEvalLit_stable hpre y (by omega) inp]

/-- The constant node simulates to `false`. -/
theorem pSim_getD_false (inp : List Bool) (ns : List Node)
    (h0 : ns[0]? = some Node.False) :
    (pSim inp ns).getD 0 false = false := by
  have hi : 0 < ns.length := by
    cases ns with
    | nil => simp at h0
    | cons _ _ => simp
  have hnd : ns[0] = Node.False := by
    rw [List.getElem?_eq_getElem hi] at h0
    exact Option.some.inj h0
  rw [pSim_getD_eq inp ns 0 hi, hnd]
  rfl

/- ══════════════════ DIMACS LITERALS OF AIG LITERALS ══════════════════ -/

/-- The DIMACS value `cnf_lit` assigns to an AIG literal. -/
def dimacsOf (l : Lit) : Int :=
  if l.neg then -((l.node.val : Int) + 1) else (l.node.val : Int) + 1

theorem cnf_lit_spec (l : Lit) (h : (l.node.val : Int) + 1 ≤ I32.max) :
    cnf_lit l ⦃ c => c.val = dimacsOf l ⦄ := by
  unfold cnf_lit
  have hcap : l.node.val + 1 ≤ Usize.max := by scalar_tac
  step as ⟨i, hi⟩
  step with (UScalar.hcast_inBounds_spec .I32 i (by simp only [hi]; scalar_tac)) as
    ⟨v, hv⟩
  split
  · rename_i hneg
    step with (IScalar.neg_step v (by
      intro heq
      simp only [hv, hi] at heq
      scalar_tac)) as ⟨nv, hnv⟩
    simp [dimacsOf, hneg, hnv, hv, hi]
  · rename_i hneg
    simp only [Bool.not_eq_true] at hneg
    simp [dimacsOf, hneg, hv, hi]

/-- A DIMACS literal `dimacsOf l` holds under the simulation assignment iff
    the AIG literal is true. -/
theorem litHolds_dimacsOf (vals : List Bool) (l : Lit) (c : Std.I32)
    (hc : c.val = dimacsOf l) :
    litHolds (simAsn vals) c ↔ pEvalLit vals l = true := by
  unfold litHolds litVar simAsn pEvalLit
  rw [hc]
  unfold dimacsOf
  cases l.neg with
  | false =>
    simp only [Bool.false_eq_true, ↓reduceIte]
    have hpos : (0 : Int) < (l.node.val : Int) + 1 := by omega
    simp only [hpos, ↓reduceIte]
    have : ((l.node.val : Int) + 1).natAbs - 1 = l.node.val := by omega
    rw [this]
  | true =>
    simp only [↓reduceIte]
    have hneg : ¬ (0 : Int) < -((l.node.val : Int) + 1) := by omega
    simp only [hneg, ↓reduceIte]
    have : (-((l.node.val : Int) + 1)).natAbs - 1 = l.node.val := by omega
    rw [this]
    cases vals.getD l.node.val false <;> simp

/-- The negation of `dimacsOf l` holds iff the AIG literal is false. -/
theorem litHolds_neg_dimacsOf (vals : List Bool) (l : Lit) (c : Std.I32)
    (hc : c.val = -dimacsOf l) :
    litHolds (simAsn vals) c ↔ pEvalLit vals l = false := by
  unfold litHolds litVar simAsn pEvalLit
  rw [hc]
  unfold dimacsOf
  cases l.neg with
  | false =>
    simp only [Bool.false_eq_true, ↓reduceIte]
    have hneg : ¬ (0 : Int) < -((l.node.val : Int) + 1) := by omega
    simp only [hneg, ↓reduceIte]
    have : (-((l.node.val : Int) + 1)).natAbs - 1 = l.node.val := by omega
    rw [this]
  | true =>
    simp only [↓reduceIte, neg_neg]
    have hpos : (0 : Int) < (l.node.val : Int) + 1 := by omega
    simp only [hpos, ↓reduceIte]
    have : ((l.node.val : Int) + 1).natAbs - 1 = l.node.val := by omega
    rw [this]
    cases vals.getD l.node.val false <;> simp

/-- The gate-output literal of node `i` (positive, un-negated) holds iff the
    node's value is true; its negation iff the value is false. -/
theorem litHolds_node (vals : List Bool) (i : Nat) (c : Std.I32)
    (hc : c.val = (i : Int) + 1) :
    litHolds (simAsn vals) c ↔ vals.getD i false = true := by
  unfold litHolds litVar simAsn
  rw [hc]
  have hpos : (0 : Int) < (i : Int) + 1 := by omega
  simp only [hpos, ↓reduceIte]
  have : ((i : Int) + 1).natAbs - 1 = i := by omega
  rw [this]

theorem litHolds_neg_node (vals : List Bool) (i : Nat) (c : Std.I32)
    (hc : c.val = -((i : Int) + 1)) :
    litHolds (simAsn vals) c ↔ vals.getD i false = false := by
  unfold litHolds litVar simAsn
  rw [hc]
  have hneg : ¬ (0 : Int) < -((i : Int) + 1) := by omega
  simp only [hneg, ↓reduceIte]
  have : (-((i : Int) + 1)).natAbs - 1 = i := by omega
  rw [this]

/- ══════════════════ CLAUSE-LEVEL HELPERS ══════════════════ -/

theorem clauseHolds_of_mem (σ : Asn) (c : List Std.I32) (lit : Std.I32)
    (hmem : lit ∈ c) (h : litHolds σ lit) : clauseHolds σ c :=
  ⟨lit, hmem, h⟩

/-- Appending a clause that holds keeps the CNF holding. -/
theorem cnfHolds_snoc (σ : Asn) (cs : List (alloc.vec.Vec Std.I32))
    (c : alloc.vec.Vec Std.I32)
    (h : cnfHolds σ (cs.map (fun c => c.val))) (hc : clauseHolds σ c.val) :
    cnfHolds σ ((cs ++ [c]).map (fun c => c.val)) := by
  intro d hd
  rw [List.map_append, List.mem_append] at hd
  rcases hd with hd | hd
  · exact h d hd
  · simp only [List.map_cons, List.map_nil, List.mem_singleton] at hd
    rw [hd]
    exact hc

/-- The three Tseitin clauses of an AND gate `o = x ∧ y` hold under the
    simulation assignment, because the gate's value IS the conjunction. -/
theorem and_clauses_hold (vals : List Bool) (i : Nat) (x y : Lit)
    (hval : vals.getD i false = (pEvalLit vals x && pEvalLit vals y))
    (o no la lb nla nlb : Std.I32)
    (ho : o.val = (i : Int) + 1) (hno : no.val = -((i : Int) + 1))
    (hla : la.val = dimacsOf x) (hlb : lb.val = dimacsOf y)
    (hnla : nla.val = -dimacsOf x) (hnlb : nlb.val = -dimacsOf y) :
    clauseHolds (simAsn vals) [no, la] ∧
    clauseHolds (simAsn vals) [no, lb] ∧
    clauseHolds (simAsn vals) [o, nla, nlb] := by
  have h1 := litHolds_neg_node vals i no hno
  have h2 := litHolds_dimacsOf vals x la hla
  have h3 := litHolds_dimacsOf vals y lb hlb
  have h4 := litHolds_node vals i o ho
  have h5 := litHolds_neg_dimacsOf vals x nla hnla
  have h6 := litHolds_neg_dimacsOf vals y nlb hnlb
  rw [hval] at h1 h4
  cases hx : pEvalLit vals x <;> cases hy : pEvalLit vals y <;>
    simp only [hx, hy, Bool.and_self, Bool.and_false, Bool.and_true]
      at h1 h2 h3 h4 h5 h6
  · exact ⟨clauseHolds_of_mem _ _ no (by simp) (h1.mpr trivial),
      clauseHolds_of_mem _ _ no (by simp) (h1.mpr trivial),
      clauseHolds_of_mem _ _ nla (by simp) (h5.mpr trivial)⟩
  · exact ⟨clauseHolds_of_mem _ _ no (by simp) (h1.mpr trivial),
      clauseHolds_of_mem _ _ no (by simp) (h1.mpr trivial),
      clauseHolds_of_mem _ _ nla (by simp) (h5.mpr trivial)⟩
  · exact ⟨clauseHolds_of_mem _ _ no (by simp) (h1.mpr trivial),
      clauseHolds_of_mem _ _ no (by simp) (h1.mpr trivial),
      clauseHolds_of_mem _ _ nlb (by simp) (h6.mpr trivial)⟩
  · exact ⟨clauseHolds_of_mem _ _ la (by simp) (h2.mpr trivial),
      clauseHolds_of_mem _ _ lb (by simp) (h3.mpr trivial),
      clauseHolds_of_mem _ _ o (by simp) (h4.mpr trivial)⟩

/- ══════════════════ THE GATE LOOP ══════════════════ -/

/-- Loop invariant of the gate loop after `i` nodes: at most three clauses
    per node were emitted (the capacity bookkeeping `Vec::push` needs) and
    every clause emitted so far holds under the simulation assignment. -/
def TseitinInv (vals : List Bool) (base per nodesLen : Nat)
    (s : alloc.vec.Vec (alloc.vec.Vec Std.I32) × Std.Usize) : Prop :=
  s.2.val ≤ nodesLen ∧
  s.1.val.length ≤ base + per * s.2.val ∧
  cnfHolds (simAsn vals) (s.1.val.map (fun c => c.val))

theorem tseitin_loop0_spec (v : alloc.vec.Vec Node)
    (clauses : alloc.vec.Vec (alloc.vec.Vec Std.I32)) (n i : Std.Usize)
    (inp : List Bool) (L : Nat)
    (hwf : AigWF v.val L)
    (hn : n.val = v.val.length)
    (hi32 : (v.val.length : Int) ≤ I32.max)
    (hcap : 1 + 3 * v.val.length < Usize.max)
    (hinv : TseitinInv (pSim inp v.val) 1 3 v.val.length (clauses, i)) :
    tseitin_loop0 v clauses n i ⦃ cs =>
      cs.val.length ≤ 1 + 3 * v.val.length ∧
      cnfHolds (simAsn (pSim inp v.val)) (cs.val.map (fun c => c.val)) ⦄ := by
  unfold tseitin_loop0
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec (alloc.vec.Vec Std.I32) × Std.Usize) =>
      v.val.length - s.2.val)
    (inv := TseitinInv (pSim inp v.val) 1 3 v.val.length)
  · rintro ⟨cl, i⟩ ⟨hile, hlen, hhold⟩
    dsimp only at hile hlen hhold
    unfold tseitin_loop0.body
    dsimp only
    split
    · rename_i hlt
      have hilt : i.val < v.val.length := by scalar_tac
      step as ⟨node, hnode⟩
      have hNW := hwf i.val hilt
      cases node with
      | False =>
        dsimp only
        step as ⟨i1, hi1⟩
        refine ⟨⟨by scalar_tac, by scalar_tac, hhold⟩, by scalar_tac⟩
      | Input k =>
        dsimp only
        step as ⟨i1, hi1⟩
        refine ⟨⟨by scalar_tac, by scalar_tac, hhold⟩, by scalar_tac⟩
      | And x y =>
        rw [← hnode] at hNW
        simp only [NodeWF] at hNW
        obtain ⟨hxw, hyw⟩ := hNW
        dsimp only
        have hval : (pSim inp v.val).getD i.val false
            = (pEvalLit (pSim inp v.val) x && pEvalLit (pSim inp v.val) y) :=
          pSim_getD_and inp v.val i.val hilt x y hnode.symm hxw hyw
        step as ⟨i1, hi1⟩
        step with (UScalar.hcast_inBounds_spec .I32 i1 (by
          simp only [hi1]; scalar_tac)) as ⟨o, ho⟩
        step with (cnf_lit_spec x (by scalar_tac)) as ⟨la, hla⟩
        step with (cnf_lit_spec y (by scalar_tac)) as ⟨lb, hlb⟩
        step with (IScalar.neg_step o (by
          intro heq; simp only [ho, hi1] at heq; scalar_tac)) as ⟨no, hno⟩
        step as ⟨c1, hc1⟩
        step as ⟨c11, hc11⟩
        have hcl : cl.val.length < Usize.max := by scalar_tac
        step as ⟨cl2, hcl2⟩
        step as ⟨c2, hc2⟩
        step as ⟨c21, hc21⟩
        have hcl2' : cl2.val.length < Usize.max := by
          rw [hcl2]; simp only [List.length_append, List.length_singleton]; scalar_tac
        step as ⟨cl3, hcl3⟩
        step as ⟨c3, hc3⟩
        step with (IScalar.neg_step la (by
          intro heq; simp only [hla, dimacsOf] at heq
          split at heq <;> scalar_tac)) as ⟨nla, hnla⟩
        step as ⟨c31, hc31⟩
        step with (IScalar.neg_step lb (by
          intro heq; simp only [hlb, dimacsOf] at heq
          split at heq <;> scalar_tac)) as ⟨nlb, hnlb⟩
        step as ⟨c32, hc32⟩
        have hcl3' : cl3.val.length < Usize.max := by
          rw [hcl3, hcl2]; simp only [List.length_append, List.length_singleton]
          scalar_tac
        step as ⟨cl4, hcl4⟩
        step as ⟨i2, hi2⟩
        obtain ⟨hA, hB, hC⟩ := and_clauses_hold (pSim inp v.val) i.val x y hval
          o no la lb nla nlb (by rw [ho, hi1]; simp) (by rw [hno, ho, hi1]; simp)
          hla hlb (by rw [hnla, hla]) (by rw [hnlb, hlb])
        have hc11v : c11.val = [no, la] := by rw [hc11, hc1]; simp
        have hc21v : c21.val = [no, lb] := by rw [hc21, hc2]; simp
        have hc32v : c32.val = [o, nla, nlb] := by rw [hc32, hc31, hc3]; simp
        refine ⟨⟨by scalar_tac, ?_, ?_⟩, by scalar_tac⟩
        · rw [hcl4, hcl3, hcl2]
          simp only [List.length_append, List.length_singleton]
          scalar_tac
        · rw [hcl4, hcl3, hcl2]
          apply cnfHolds_snoc _ _ _ (cnfHolds_snoc _ _ _ (cnfHolds_snoc _ _ _ hhold ?_) ?_) ?_
          · rw [hc11v]; exact hA
          · rw [hc21v]; exact hB
          · rw [hc32v]; exact hC
    · rename_i hge
      have hieq : i.val = v.val.length := by scalar_tac
      exact ⟨by rw [hieq] at hlen; exact hlen, hhold⟩
  · exact hinv

/- ══════════════════ THE OUTPUT LOOP ══════════════════ -/

theorem tseitin_loop1_spec (outputs : Slice Lit)
    (clauses : alloc.vec.Vec (alloc.vec.Vec Std.I32)) (m j : Std.Usize)
    (vals : List Bool) (base : Nat)
    (hm : m.val = outputs.val.length)
    (hi32 : ∀ l ∈ outputs.val, (l.node.val : Int) + 1 ≤ I32.max)
    (houts : ∀ l ∈ outputs.val, pEvalLit vals l = true)
    (hcap : base + outputs.val.length < Usize.max)
    (hinv : TseitinInv vals base 1 outputs.val.length (clauses, j)) :
    tseitin_loop1 outputs clauses m j ⦃ cs =>
      cs.val.length ≤ base + outputs.val.length ∧
      cnfHolds (simAsn vals) (cs.val.map (fun c => c.val)) ⦄ := by
  unfold tseitin_loop1
  apply loop.spec_decr_nat
    (measure := fun (s : alloc.vec.Vec (alloc.vec.Vec Std.I32) × Std.Usize) =>
      outputs.val.length - s.2.val)
    (inv := TseitinInv vals base 1 outputs.val.length)
  · rintro ⟨cl, j⟩ ⟨hjle, hlen, hhold⟩
    dsimp only at hjle hlen hhold
    unfold tseitin_loop1.body
    dsimp only
    split
    · rename_i hlt
      have hjlt : j.val < outputs.val.length := by scalar_tac
      step as ⟨l, hl⟩
      have hmem : l ∈ outputs.val := by rw [hl]; exact List.getElem_mem _
      step with (cnf_lit_spec l (hi32 l hmem)) as ⟨c, hc⟩
      step as ⟨c1, hc1⟩
      have hcl : cl.val.length < Usize.max := by scalar_tac
      step as ⟨cl1, hcl1⟩
      step as ⟨j1, hj1⟩
      have hc1v : c1.val = [c] := by rw [hc1]; simp
      refine ⟨⟨by scalar_tac, ?_, ?_⟩, by scalar_tac⟩
      · rw [hcl1]; simp only [List.length_append, List.length_singleton]; scalar_tac
      · rw [hcl1]
        apply cnfHolds_snoc _ _ _ hhold
        rw [hc1v]
        exact clauseHolds_of_mem _ _ c (by simp)
          ((litHolds_dimacsOf vals l c hc).mpr (houts l hmem))
    · rename_i hge
      have hjeq : j.val = outputs.val.length := by scalar_tac
      exact ⟨by rw [hjeq] at hlen; omega, hhold⟩
  · exact hinv

/- ══════════════════ THE CAPSTONE ══════════════════ -/

/-- **Tseitin preserves satisfiability** (issue #192 phase 1): for an AIG
    whose gates point strictly backwards (`AigWF`, for any input count `L`)
    with the constant node at index 0, if some input assignment `inp` makes
    every asserted output literal true, then the CNF `tseitin` emits is
    satisfied by the simulation itself — DIMACS variable `v` carrying AIG
    node `v - 1`'s value (`simAsn`). Total correctness: the encoder cannot
    fail under the stated capacity bounds (`i32` variable numbers, `usize`
    clause count: one constant clause, three per node, one per output).
    The semantics `cnfHolds` is Sound.lean's — the meaning
    `lrat_check_sound` refutes. -/
theorem tseitin_sat_preserving (aig : Aig) (outputs : Slice Lit)
    (inp : List Bool) (L : Nat)
    (hwf : AigWF aig.nodes.val L)
    (h0 : aig.nodes.val[0]? = some Node.False)
    (hi32 : (aig.nodes.val.length : Int) ≤ I32.max)
    (hcap : 1 + 3 * aig.nodes.val.length + outputs.val.length < Usize.max)
    (houts : ∀ l ∈ outputs.val,
      l.node.val < aig.nodes.val.length ∧
      pEvalLit (pSim inp aig.nodes.val) l = true) :
    tseitin aig outputs ⦃ cnf =>
      cnfHolds (simAsn (pSim inp aig.nodes.val)) (cnf.val.map (fun c => c.val)) ⦄ := by
  unfold tseitin
  step as ⟨c0, hc0⟩
  step as ⟨clauses, hcl⟩
  have hinit : TseitinInv (pSim inp aig.nodes.val) 1 3 aig.nodes.val.length
      (clauses, 0#usize) := by
    refine ⟨by simp, by simp [hcl], ?_⟩
    intro d hd
    rw [hcl] at hd
    simp only [List.nil_append, List.map_cons, List.map_nil, List.mem_singleton] at hd
    rw [hd, hc0]
    simp only [List.nil_append]
    apply clauseHolds_of_mem _ _ ((-1)#i32) (by simp)
    apply (litHolds_neg_node (pSim inp aig.nodes.val) 0 ((-1)#i32) (by simp)).mpr
    exact pSim_getD_false inp aig.nodes.val h0
  step with (tseitin_loop0_spec aig.nodes clauses (alloc.vec.Vec.len aig.nodes)
    0#usize inp L hwf (by simp) hi32 (by omega) hinit) as ⟨cs1, hcs1a, hcs1b⟩
  have hi32' : ∀ l ∈ outputs.val, (l.node.val : Int) + 1 ≤ I32.max := by
    intro l hl
    have := (houts l hl).1
    omega
  apply WP.spec_mono (tseitin_loop1_spec outputs cs1 (Slice.len outputs) 0#usize
    (pSim inp aig.nodes.val) (1 + 3 * aig.nodes.val.length) (by simp) hi32'
    (fun l hl => (houts l hl).2) (by omega) ⟨by simp, by simp; exact hcs1a, hcs1b⟩)
  intro cs ⟨_, h⟩
  exact h

/-- The CNF `tseitin` emits is SATISFIABLE in the checker's sense (not
    `unsat`, Sound.lean) whenever some input assignment satisfies the asserted
    outputs — the contrapositive of what an accepted certificate needs. -/
theorem tseitin_satisfiable (aig : Aig) (outputs : Slice Lit)
    (inp : List Bool) (L : Nat)
    (hwf : AigWF aig.nodes.val L)
    (h0 : aig.nodes.val[0]? = some Node.False)
    (hi32 : (aig.nodes.val.length : Int) ≤ I32.max)
    (hcap : 1 + 3 * aig.nodes.val.length + outputs.val.length < Usize.max)
    (houts : ∀ l ∈ outputs.val,
      l.node.val < aig.nodes.val.length ∧
      pEvalLit (pSim inp aig.nodes.val) l = true) :
    tseitin aig outputs ⦃ cnf => ¬ unsat (cnf.val.map (fun c => c.val)) ⦄ := by
  apply WP.spec_mono (tseitin_sat_preserving aig outputs inp L hwf h0 hi32 hcap houts)
  intro cnf h hun
  exact hun _ h

/-- **The two proven halves meet**: if the model Tseitin encoder produced
    `cnf` from an AIG and its asserted outputs, and the trusted checker
    (`kernel.check_steps`, Sound.lean's `lrat_check_sound`) accepts an LRAT
    step list against that very `cnf`, then NO input assignment makes every
    asserted output literal true. This is the UNSAT direction of the
    query→CNF gap (issue #192) closed at the AIG level: a certified CNF
    refutation refutes the circuit it was encoded from. -/
theorem tseitin_refutes_outputs (aig : Aig) (outputs : Slice Lit) (L : Nat)
    (hwf : AigWF aig.nodes.val L)
    (h0 : aig.nodes.val[0]? = some Node.False)
    (hi32 : (aig.nodes.val.length : Int) ≤ I32.max)
    (hcap : 1 + 3 * aig.nodes.val.length + outputs.val.length < Usize.max)
    (cnf : alloc.vec.Vec (alloc.vec.Vec Std.I32))
    (henc : tseitin aig outputs = ok cnf)
    (steps : Slice kernel.Step)
    (hfit : cnf.val.length + steps.val.length ≤ Std.Usize.max)
    (hchk : kernel.check_steps ⟨cnf.val, cnf.property⟩ steps
      = ok (core.result.Result.Ok ())) :
    ∀ inp : List Bool, ¬ (∀ l ∈ outputs.val,
      l.node.val < aig.nodes.val.length ∧
      pEvalLit (pSim inp aig.nodes.val) l = true) := by
  intro inp houts
  have hsat := tseitin_satisfiable aig outputs inp L hwf h0 hi32 hcap houts
  rw [henc, WP.spec_ok] at hsat
  exact hsat (kernel.spec.lrat_check_sound ⟨cnf.val, cnf.property⟩ steps hfit hchk)

end blast_kernel.spec
