/- Correctness of `blast_rotr` at EVERY width `w ≥ 1` (issue #201; the
   rotate half of the barrel-shifter family of issue #68).

   This file is HAND-WRITTEN (BlastKernel.lean is generated by regen.sh
   and must not be edited). It lives after BlasterDiv.lean because the
   rule composes the rotate barrel (`rotr_stages`, BlasterShift.lean) with
   the divider: at a power-of-two width the low `log2 w` amount bits ARE
   the amount mod `w`, so the barrel rotates on `b` directly; at any other
   width the amount is first reduced mod `w` with `blast_urem` against the
   constant word `w` (`word_const`), and the reduced amount `< w ≤
   2^stages` drives the barrel. Both branches feed `rotr_stages` an amount
   word whose low `stages` bits value `B.toNat % w`, which is the single
   fact the barrel's spec needs (`tail` below).

   * `blast_urem_frame` / `blast_urem_full`: the structural frame of the
     multiplicative remainder (`blast_udiv` + `blast_mul` + `blast_sub`),
     glued to `blast_urem_bitvec` with `spec_and` — the same idiom
     BlasterDiv.lean uses for the #101 composition.
   * `blast_rotr_bitvec`: the output word denotes
     `A.rotateRight (B.toNat % w)` (`getLsbD_rotateRight`), for every width.
     Pinned axiom-clean in AxiomCheck.lean.
-/
import BlasterDiv

open Aeneas Aeneas.Std Result

set_option maxHeartbeats 1000000

namespace kernel.blast_kernel.spec

/- ══════════════════ THE REMAINDER'S STRUCTURAL FRAME ══════════════════ -/

/-- **Structural frame of `blast_urem`**: at most `22·w² + 17·w` gates
    are appended (`12·w² + 8·w` udiv, `≤ 10·w²` mul, `9·w` sub), nothing
    existing is touched, well-formedness is preserved, and the remainder
    word has width `w` with every literal in range. -/
theorem blast_urem_frame (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length
      + (12 * a.val.length * a.val.length + 8 * a.val.length)
      + 10 * a.val.length * a.val.length
      + 9 * a.val.length
      ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False) :
    blast_urem aig a b ⦃ p =>
      p.1.val.length = a.val.length ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.2.nodes.val.length ≤ aig.nodes.val.length
        + (12 * a.val.length * a.val.length + 8 * a.val.length)
        + 10 * a.val.length * a.val.length
        + 9 * a.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ l ∈ p.1.val, l.node.val < p.2.nodes.val.length) ⦄ := by
  unfold blast_urem
  step with (blast_udiv_frame aig a b hab (by omega) ha hb hne h0) as
    ⟨q, aig1, hql, hpre1, hlen1, hwf1, hqrng⟩
  have hderefq : (alloc.vec.Vec.deref q).val = q.val := rfl
  have hqlen' : (alloc.vec.Vec.deref q).val.length = a.val.length := by
    rw [hderefq, hql]
  have hne1 : 0 < aig1.nodes.val.length := by
    have := hpre1.length_le
    omega
  have h01 : aig1.nodes.val[0]'hne1 = Node.False :=
    node0_of_prefix hpre1 hne h0 hne1
  have hb1 : ∀ l ∈ b.val, l.node.val < aig1.nodes.val.length := by
    intro l hl
    have h1 := hb l hl
    have h2 := hpre1.length_le
    omega
  have hqrng' : ∀ l ∈ (alloc.vec.Vec.deref q).val,
      l.node.val < aig1.nodes.val.length := by
    rw [hderefq]
    exact hqrng
  step with (blast_mul_frame aig1 (alloc.vec.Vec.deref q) b
    (by omega) (by rw [hqlen']; omega) hqrng' hb1 hne1 h01) as
    ⟨prod, aig2, hpl, hpre2, hlen2, hwf2, hprng⟩
  rw [hqlen'] at hpl hlen2
  have hderefp : (alloc.vec.Vec.deref prod).val = prod.val := rfl
  have hplen' : (alloc.vec.Vec.deref prod).val.length = a.val.length := by
    rw [hderefp]
    exact hpl
  have hne2 : 0 < aig2.nodes.val.length := by
    have := hpre2.length_le
    omega
  have ha2 : ∀ l ∈ a.val, l.node.val < aig2.nodes.val.length := by
    intro l hl
    have h1 := ha l hl
    have h2 := hpre1.length_le
    have h3 := hpre2.length_le
    omega
  have hprng' : ∀ l ∈ (alloc.vec.Vec.deref prod).val,
      l.node.val < aig2.nodes.val.length := by
    rw [hderefp]
    exact hprng
  apply WP.spec_mono (blast_sub_frame aig2 a (alloc.vec.Vec.deref prod)
    (by omega) (by omega) ha2 hprng' hne2)
  rintro ⟨out, aig3⟩ ⟨hol, hpre3, hlen3, hwf3, horng⟩
  exact ⟨hol, hpre1.trans (hpre2.trans hpre3), by omega,
    fun L hL => hwf3 L (hwf2 L (hwf1 L hL)), horng⟩

/-- `blast_urem`, frame AND semantics in one spec (via `spec_and`). -/
theorem blast_urem_full (aig : Aig) (a b : Slice Lit)
    (hab : a.val.length ≤ b.val.length)
    (hcap : aig.nodes.val.length
      + (12 * a.val.length * a.val.length + 8 * a.val.length)
      + 10 * a.val.length * a.val.length
      + 9 * a.val.length
      ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (A B : BitVec w) :
    blast_urem aig a b ⦃ p =>
      p.1.val.length = a.val.length ∧
      aig.nodes.val <+: p.2.nodes.val ∧
      p.2.nodes.val.length ≤ aig.nodes.val.length
        + (12 * a.val.length * a.val.length + 8 * a.val.length)
        + 10 * a.val.length * a.val.length
        + 9 * a.val.length ∧
      (∀ L, AigWF aig.nodes.val L → AigWF p.2.nodes.val L) ∧
      (∀ l ∈ p.1.val, l.node.val < p.2.nodes.val.length) ∧
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          Denotes vals.val p.1.val w (A % B) ⦄ ⦄ := by
  apply WP.spec_mono (spec_and
    (blast_urem_frame aig a b hab hcap ha hb hne h0)
    (blast_urem_bitvec aig a b hab hcap ha hb hne h0 A B))
  rintro ⟨out, aig1⟩ ⟨⟨h1, h2, h3, h4, h5⟩, h6⟩
  exact ⟨h1, h2, h3, h4, h5, h6⟩

/- ══════════════════ HEADLINE: `blast_rotr` ══════════════════ -/

/-- **`blast_rotr` implements SMT-LIB `rotate_right`
    (`BitVec.rotateRight`), for EVERY width `w ≥ 1`**: the output word
    denotes `A.rotateRight (B.toNat % w)` — mod-width semantics, no
    out-of-range fill. At a power-of-two width only the low `log2 w`
    amount bits matter (`B.toNat % w = B.toNat % 2^stages`); at any other
    width the amount is reduced mod `w` by `blast_urem` first, and the
    barrel rotates by that reduced amount (`< w ≤ 2^stages`). The capacity
    bound covers the worst case (the reduction's `22·w² + 17·w` gates plus
    the barrel's `3·w·stages`). -/
theorem blast_rotr_bitvec (aig : Aig) (a b : Slice Lit)
    (hw : 0 < a.val.length)
    (hab : b.val.length = a.val.length)
    (hcap : aig.nodes.val.length
      + (12 * a.val.length * a.val.length + 8 * a.val.length)
      + 10 * a.val.length * a.val.length
      + 9 * a.val.length
      + 3 * a.val.length * pStages a.val.length
      ≤ Usize.max)
    (ha : ∀ l ∈ a.val, l.node.val < aig.nodes.val.length)
    (hb : ∀ l ∈ b.val, l.node.val < aig.nodes.val.length)
    (hne : 0 < aig.nodes.val.length)
    (h0 : aig.nodes.val[0]'hne = Node.False)
    {w : Nat} (A B : BitVec w) :
    blast_rotr aig a b ⦃ p =>
      ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        simulate p.2 inputs ⦃ vals =>
          Denotes vals.val a.val w A → Denotes vals.val b.val w B →
          Denotes vals.val p.1.val w (A.rotateRight (B.toNat % w)) ⦄ ⦄ := by
  unfold blast_rotr
  have hlen : (Slice.len a).val = a.val.length := by scalar_tac
  step with (stage_count_spec (Slice.len a) (by scalar_tac)) as
    ⟨stages, pow2, hst1, hst2, hst3, hst4⟩
  rw [hlen] at hst1 hst2 hst3 hst4
  rw [← hst1] at hcap
  have hsle : stages.val ≤ a.val.length := stages_le hst3
  -- The shared tail: the barrel, on an amount word `amt` living in an
  -- extension `aig1` of the original aig, whose low `stages` bits value
  -- `B.toNat % w` whenever `b` denotes `B`.
  have tail : ∀ (aig1 : Aig) (amt : Slice Lit),
      aig.nodes.val <+: aig1.nodes.val →
      (∀ L, AigWF aig.nodes.val L → AigWF aig1.nodes.val L) →
      aig1.nodes.val.length + 3 * a.val.length * stages.val ≤ Usize.max →
      stages.val ≤ amt.val.length →
      (∀ l ∈ amt.val, l.node.val < aig1.nodes.val.length) →
      (∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
        Denotes (pSim inputs.val aig.nodes.val) b.val w B →
        pAmt (pSim inputs.val aig1.nodes.val) amt.val stages.val
          = B.toNat % w) →
      rotr_stages aig1 a amt stages ⦃ p =>
        ∀ (inputs : Slice Bool), AigWF aig.nodes.val inputs.val.length →
          simulate p.2 inputs ⦃ vals =>
            Denotes vals.val a.val w A → Denotes vals.val b.val w B →
            Denotes vals.val p.1.val w (A.rotateRight (B.toNat % w)) ⦄ ⦄ := by
    intro aig1 amt hpre1 hwf1 hcap1 hstages1 hamt hpamt
    have ha1 : ∀ l ∈ a.val, l.node.val < aig1.nodes.val.length := by
      intro l hl
      have := ha l hl
      have := hpre1.length_le
      omega
    apply WP.spec_mono (rotr_stages_spec aig1 a amt stages hstages1 hst3
      hcap1 ha1 hamt)
    rintro ⟨out, aig2⟩ ⟨h11, h12, h13, h14, h15, h16⟩
    intro inputs hwf
    apply WP.spec_mono (simulate_spec aig2 inputs (h14 _ (hwf1 _ hwf)))
    intro vals hv hA hB
    rw [hv] at hA hB ⊢
    have hpre02 : aig.nodes.val <+: aig2.nodes.val := hpre1.trans h12
    have hA0 : Denotes (pSim inputs.val aig.nodes.val) a.val w A :=
      hA.of_prefix hpre02 ha inputs.val
    have hB0 : Denotes (pSim inputs.val aig.nodes.val) b.val w B :=
      hB.of_prefix hpre02 hb inputs.val
    have hA1 : Denotes (pSim inputs.val aig1.nodes.val) a.val w A :=
      hA0.up hpre1 ha inputs.val
    have hal : a.val.length = w := hA0.1
    have hwpos : 0 < w := by omega
    have hr : B.toNat % w < w := Nat.mod_lt _ hwpos
    have hrot : ∀ i : Nat, i < w →
        (A.rotateRight (B.toNat % w)).getLsbD i
          = A.getLsbD ((i + B.toNat % w) % w) := by
      intro i hi
      rw [BitVec.getLsbD_rotateRight, Nat.mod_eq_of_lt hr]
      by_cases hc : i < w - B.toNat % w
      · have hlt : i + B.toNat % w < w := by omega
        have hmod : (i + B.toNat % w) % w = i + B.toNat % w :=
          Nat.mod_eq_of_lt hlt
        rw [decide_eq_true hc, cond_true, hmod]
        congr 1
        omega
      · have hge : w ≤ i + B.toNat % w := by omega
        have hlt2 : i + B.toNat % w - w < w := by omega
        have hmod : (i + B.toNat % w) % w = i + B.toNat % w - w := by
          rw [Nat.mod_eq_sub_mod hge]
          exact Nat.mod_eq_of_lt hlt2
        rw [decide_eq_false hc, cond_false, decide_eq_true hi,
          Bool.true_and, hmod]
        congr 1
        omega
    refine ⟨by omega, fun j hj => ?_⟩
    have hjw : j < w := by omega
    have hmlt : (j + pAmt (pSim inputs.val aig1.nodes.val) amt.val stages.val)
        % a.val.length < a.val.length := Nat.mod_lt _ (by omega)
    rw [h16 inputs.val j hj, getD_eq_getElem_of_lt hmlt, hA1.2 _ hmlt,
      hrot j hjw, hpamt inputs hwf hB0, hal]
  split
  · -- power-of-two width: the barrel reads `b` directly
    rename_i hp
    have hpow : a.val.length = 2 ^ stages.val := by
      rw [hp] at hst4
      exact of_decide_eq_true hst4.symm
    apply tail aig b (List.prefix_refl _) (fun _ h => h) (by omega)
      (by omega) hb
    intro inputs hwf hB0
    have hbl : b.val.length = w := hB0.1
    have hal : a.val.length = w := by omega
    rw [pAmt_eq_mod hB0 stages.val (by omega), ← hpow, hal]
  · -- any other width: reduce the amount mod `w` first
    rename_i hp
    step with (word_const_spec (Slice.len a) (Slice.len a)) as
      ⟨modulus, hml, hmbits⟩
    rw [hlen] at hml hmbits
    have hderefm : (alloc.vec.Vec.deref modulus).val = modulus.val := rfl
    have hmrng : ∀ l ∈ (alloc.vec.Vec.deref modulus).val,
        l.node.val < aig.nodes.val.length := by
      rw [hderefm]
      intro l hl
      obtain ⟨j, hj, rfl⟩ := List.mem_iff_getElem.mp hl
      rw [hmbits j hj]
      scalar_tac
    have hmlen' : (alloc.vec.Vec.deref modulus).val.length = a.val.length := by
      rw [hderefm, hml]
    step with (blast_urem_full aig b (alloc.vec.Vec.deref modulus)
      (by omega) (by rw [hab]; omega) hb hmrng hne h0
      B (BitVec.ofNat w a.val.length)) as
      ⟨reduced, aig1, hrl, hpre1, hlen1, hwf1, hrrng, hsimR⟩
    have hderefr : (alloc.vec.Vec.deref reduced).val = reduced.val := rfl
    have hrlen' : (alloc.vec.Vec.deref reduced).val.length = a.val.length := by
      rw [hderefr, hrl, hab]
    have hrrng' : ∀ l ∈ (alloc.vec.Vec.deref reduced).val,
        l.node.val < aig1.nodes.val.length := by
      rw [hderefr]
      exact hrrng
    apply tail aig1 (alloc.vec.Vec.deref reduced) hpre1 hwf1
      (by rw [hab] at hlen1; omega) (by omega) hrrng'
    intro inputs hwf hB0
    -- harvest the remainder's semantics under aig1
    obtain ⟨v1, hv1, hf1⟩ :=
      simulate_spec_pSim aig1 inputs (hwf1 _ hwf) (hsimR inputs hwf)
    rw [hv1, hderefm] at hf1
    have hbl : b.val.length = w := hB0.1
    have hal : a.val.length = w := by omega
    have hW : Denotes (pSim inputs.val aig.nodes.val) modulus.val w
        (BitVec.ofNat w a.val.length) := by
      refine ⟨by omega, fun j hj => ?_⟩
      rw [hmbits j hj, pEvalLit_node_zero hne h0, BitVec.getLsbD_ofNat,
        decide_eq_true (show j < w by omega), Bool.true_and]
    have hR1 : Denotes (pSim inputs.val aig1.nodes.val) reduced.val w
        (B % BitVec.ofNat w a.val.length) :=
      hf1 (hB0.up hpre1 hb inputs.val) (hW.up hpre1 hmrng inputs.val)
    have hwpos : 0 < w := by omega
    have hr : B.toNat % w < w := Nat.mod_lt _ hwpos
    rw [hderefr, pAmt_eq_mod hR1 stages.val (by omega), BitVec.toNat_umod,
      BitVec.toNat_ofNat, hal, Nat.mod_eq_of_lt Nat.lt_two_pow_self]
    exact Nat.mod_eq_of_lt (by omega)

end kernel.blast_kernel.spec
