/- The query→CNF capstone (issue #192, phase 3 / v0.26.0): a certified
   refutation of the CNF refutes the term DAG it was encoded from.

   This file is HAND-WRITTEN (BlastKernel.lean is generated by regen.sh and
   must not be edited). It composes the three proven stages of the shipped
   lowering pipeline (`solver.rs::lower_with`) with the checker's soundness
   theorem:

     encode  — `encode_sound`         (BlasterDag.lean):   the AIG's output
               literals simulate to the DAG roots' boolean values;
     compact — `compact_sound_lit`    (BlasterCompact.lean): the folding +
               hashing pass preserves every literal's value;
     tseitin — `tseitin_refutes_outputs` (BlasterTseitin.lean, already
               composed with Sound.lean's `lrat_check_sound`): an accepted
               LRAT certificate against the emitted CNF refutes the asserted
               AIG outputs.

   `dag_refuted` is the headline: if the trusted checker accepts a step list
   against the CNF that `encode`, `compact`, `map_word` and `tseitin`
   produced from a well-formed DAG, then NO primary-input assignment makes
   every root true — the DAG (the query, up to the untrusted DAG builder) is
   unsatisfiable. `dag_refuted_raw` is the same without the compaction pass.
   Both are stated over the kernel's own `unsat` semantics for the CNF, so
   nothing is lost at the seam with the checker. -/
import BlasterDag
import BlasterCompact

open Aeneas Aeneas.Std Result

set_option maxHeartbeats 1000000

namespace kernel.blast_kernel.spec

/-- `aig_new` yields the one-node arena: node 0 is the constant, no inputs. -/
theorem aig_new_fresh (aig0 : Aig) (h : aig_new = ok aig0) :
    aig0.nodes.val = [Node.False] := by
  have := aig_new_spec
  rw [h, WP.spec_ok] at this
  exact this

/-- **The query→CNF capstone with compaction** (issue #192 phase 3). -/
theorem dag_refuted (ns : Slice DagNode) (bits : Slice Bool) (roots : Slice Std.Usize)
    (W : Nat)
    (hdag : DagWF ns.val bits.val.length)
    (hW : ∀ w ∈ dagWidths ns.val, w ≤ W)
    (hcap : 1 + ns.val.length * gateBound W ≤ Usize.max)
    (hroots : ∀ r ∈ roots.val, r.val < ns.val.length ∧ (dagWidths ns.val).getD r.val 0 = 1)
    (aig0 : Aig) (hnew : aig_new = ok aig0)
    (words : alloc.vec.Vec (alloc.vec.Vec Lit)) (outs : alloc.vec.Vec Lit) (aig1 : Aig)
    (henc : encode aig0 ns bits roots = ok ((words, outs), aig1))
    (hints : Slice Std.Usize) (aig2 : Aig) (map : alloc.vec.Vec Lit)
    (hcomp : compact aig1 hints = ok (aig2, map))
    (outs2 : alloc.vec.Vec Lit)
    (hmap : map_word (alloc.vec.Vec.deref map) (alloc.vec.Vec.deref outs) = ok outs2)
    (hi32 : (aig2.nodes.val.length : Int) ≤ I32.max)
    (hcapT : 1 + 3 * aig2.nodes.val.length + outs2.val.length < Usize.max)
    (cnf : alloc.vec.Vec (alloc.vec.Vec Std.I32))
    (htse : tseitin aig2 (alloc.vec.Vec.deref outs2) = ok cnf)
    (steps : Slice kernel.Step)
    (hfit : cnf.val.length + steps.val.length ≤ Std.Usize.max)
    (hchk : kernel.check_steps ⟨cnf.val, cnf.property⟩ steps
      = ok (core.result.Result.Ok ())) :
    ∀ inp : List Bool, ¬ (∀ (k : Nat) (hk : k < roots.val.length),
      dagBool inp bits.val ns.val (roots.val[k]).val = true) := by
  have h0list := aig_new_fresh aig0 hnew
  have hne0 : 0 < aig0.nodes.val.length := by rw [h0list]; simp
  have h00 : aig0.nodes.val[0]'hne0 = Node.False := by simp [h0list]
  have hwf0 : AigWF aig0.nodes.val 0 := by
    intro i hi
    have hi0 : i = 0 := by
      rw [h0list] at hi
      simp only [List.length_singleton] at hi
      omega
    subst hi0
    rw [h00]
    trivial
  have hcap0 : aig0.nodes.val.length + ns.val.length * gateBound W ≤ Usize.max := by
    rw [h0list]
    simpa using hcap
  -- encode
  obtain ⟨y, hy, hP⟩ := WP.spec_imp_exists
    (encode_sound aig0 ns bits roots W hne0 h00 hwf0 hdag hW hcap0 hroots)
  rw [henc] at hy
  have hy' := Result.ok.inj hy
  subst hy'
  obtain ⟨hpre1, hwf1, _, _, holen, horng, hosem⟩ := hP
  dsimp only at hpre1 hwf1 holen horng hosem
  have hne1 : 0 < aig1.nodes.val.length := by
    have := hpre1.length_le
    rw [h0list] at this
    simp at this
    omega
  have h01 : aig1.nodes.val[0]'hne1 = Node.False := node0_of_prefix hpre1 hne0 h00 hne1
  -- compact
  obtain ⟨z, hz, hQ⟩ := WP.spec_imp_exists
    (compact_sound_lit aig1 hints (dagNin ns.val) hwf1 hne1 h01)
  rw [hcomp] at hz
  have hz' := Result.ok.inj hz
  subst hz'
  obtain ⟨hmlen, hwf2, hne2, h02, _, hmrng, hmsem⟩ := hQ
  dsimp only at hmlen hwf2 hne2 h02 hmrng hmsem
  -- map_word
  obtain ⟨u, hu, hU⟩ := WP.spec_imp_exists
    (map_word_spec (alloc.vec.Vec.deref map) (alloc.vec.Vec.deref outs) (by
      intro l hl
      show l.node.val < map.val.length
      rw [hmlen]
      exact horng l hl))
  rw [hmap] at hu
  have hu' := Result.ok.inj hu
  subst hu'
  have houts2 : outs2.val = outs.val.map (pMapLit map.val) := hU
  -- tseitin + check
  have hwfT : AigWF aig2.nodes.val (dagNin ns.val) := hwf2
  have hcapT' : 1 + 3 * aig2.nodes.val.length + (alloc.vec.Vec.deref outs2).val.length
      < Usize.max := hcapT
  have hrefute := tseitin_refutes_outputs aig2 (alloc.vec.Vec.deref outs2) (dagNin ns.val)
    hwfT h02 hi32 hcapT' cnf htse steps hfit hchk
  intro inp hall
  apply hrefute inp
  intro l hl
  change l ∈ outs2.val at hl
  rw [houts2, List.mem_map] at hl
  obtain ⟨l0, hl0, rfl⟩ := hl
  obtain ⟨k, hk, rfl⟩ := List.getElem_of_mem hl0
  have hk' : k < roots.val.length := by rw [← holen]; exact hk
  have hl0rng : (outs.val[k]).node.val < aig1.nodes.val.length := horng _ (List.getElem_mem _)
  refine ⟨hmrng _ hl0rng, ?_⟩
  rw [hmsem inp _ hl0rng, hosem inp k hk, getD_eq_getElem_of_lt hk']
  exact hall k hk'

/-- **The query→CNF capstone without compaction**: `encode` straight into
    `tseitin`. -/
theorem dag_refuted_raw (ns : Slice DagNode) (bits : Slice Bool) (roots : Slice Std.Usize)
    (W : Nat)
    (hdag : DagWF ns.val bits.val.length)
    (hW : ∀ w ∈ dagWidths ns.val, w ≤ W)
    (hcap : 1 + ns.val.length * gateBound W ≤ Usize.max)
    (hroots : ∀ r ∈ roots.val, r.val < ns.val.length ∧ (dagWidths ns.val).getD r.val 0 = 1)
    (aig0 : Aig) (hnew : aig_new = ok aig0)
    (words : alloc.vec.Vec (alloc.vec.Vec Lit)) (outs : alloc.vec.Vec Lit) (aig1 : Aig)
    (henc : encode aig0 ns bits roots = ok ((words, outs), aig1))
    (hi32 : (aig1.nodes.val.length : Int) ≤ I32.max)
    (hcapT : 1 + 3 * aig1.nodes.val.length + outs.val.length < Usize.max)
    (cnf : alloc.vec.Vec (alloc.vec.Vec Std.I32))
    (htse : tseitin aig1 (alloc.vec.Vec.deref outs) = ok cnf)
    (steps : Slice kernel.Step)
    (hfit : cnf.val.length + steps.val.length ≤ Std.Usize.max)
    (hchk : kernel.check_steps ⟨cnf.val, cnf.property⟩ steps
      = ok (core.result.Result.Ok ())) :
    ∀ inp : List Bool, ¬ (∀ (k : Nat) (hk : k < roots.val.length),
      dagBool inp bits.val ns.val (roots.val[k]).val = true) := by
  have h0list := aig_new_fresh aig0 hnew
  have hne0 : 0 < aig0.nodes.val.length := by rw [h0list]; simp
  have h00 : aig0.nodes.val[0]'hne0 = Node.False := by simp [h0list]
  have hwf0 : AigWF aig0.nodes.val 0 := by
    intro i hi
    have hi0 : i = 0 := by
      rw [h0list] at hi
      simp only [List.length_singleton] at hi
      omega
    subst hi0
    rw [h00]
    trivial
  have hcap0 : aig0.nodes.val.length + ns.val.length * gateBound W ≤ Usize.max := by
    rw [h0list]
    simpa using hcap
  obtain ⟨y, hy, hP⟩ := WP.spec_imp_exists
    (encode_sound aig0 ns bits roots W hne0 h00 hwf0 hdag hW hcap0 hroots)
  rw [henc] at hy
  have hy' := Result.ok.inj hy
  subst hy'
  obtain ⟨hpre1, hwf1, _, _, holen, horng, hosem⟩ := hP
  dsimp only at hpre1 hwf1 holen horng hosem
  have hne1 : 0 < aig1.nodes.val.length := by
    have := hpre1.length_le
    rw [h0list] at this
    simp at this
    omega
  have h01 : aig1.nodes.val[0]? = some Node.False := by
    rw [List.getElem?_eq_getElem hne1, node0_of_prefix hpre1 hne0 h00 hne1]
  have hcapT' : 1 + 3 * aig1.nodes.val.length + (alloc.vec.Vec.deref outs).val.length
      < Usize.max := hcapT
  have hrefute := tseitin_refutes_outputs aig1 (alloc.vec.Vec.deref outs) (dagNin ns.val)
    hwf1 h01 hi32 hcapT' cnf htse steps hfit hchk
  intro inp hall
  apply hrefute inp
  intro l hl
  change l ∈ outs.val at hl
  obtain ⟨k, hk, rfl⟩ := List.getElem_of_mem hl
  have hk' : k < roots.val.length := by rw [← holen]; exact hk
  refine ⟨horng _ (List.getElem_mem _), ?_⟩
  rw [hosem inp k hk, getD_eq_getElem_of_lt hk']
  exact hall k hk'

end kernel.blast_kernel.spec
