-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace kernel

/-- [kernel::Step]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 27:0-43:1
    Visibility: public -/
@[discriminant isize]
inductive Step where
| Add :
  Std.Usize →
  alloc.vec.Vec Std.I32 →
  alloc.vec.Vec Std.Usize →
  Step
| Delete : alloc.vec.Vec Std.Usize → Step

/-- [kernel::{impl core::clone::Clone for kernel::Step}::clone]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 26:9-26:14
    Visibility: public -/
def Step.Insts.CoreCloneClone.clone (self : Step) : Result Step := do
  match self with
  | Step.Add __self_0 __self_1 __self_2 =>
    let i ← lift (core.clone.impls.CloneUsize.clone __self_0)
    let v ← alloc.vec.CloneVec.clone core.clone.CloneI32 __self_1
    let v1 ← alloc.vec.CloneVec.clone core.clone.CloneUsize __self_2
    ok (Step.Add i v v1)
  | Step.Delete __self_0 =>
    let v ← alloc.vec.CloneVec.clone core.clone.CloneUsize __self_0
    ok (Step.Delete v)

/-- Trait implementation: [kernel::{impl core::clone::Clone for kernel::Step}]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 26:9-26:14 -/
@[reducible]
def Step.Insts.CoreCloneClone : core.clone.Clone Step := {
  clone := Step.Insts.CoreCloneClone.clone
}

/-- [kernel::{impl core::fmt::Debug for kernel::Step}::fmt]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 26:16-26:21
    Visibility: public -/
def Step.Insts.CoreFmtDebug.fmt
  (self : Step) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | Step.Add __self_0 __self_1 __self_2 =>
    let __self_01 := Dyn.mk _ core.fmt.DebugUsize __self_0
    let __self_11 := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugI32) __self_1
    let __self_21 :=
      Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec core.fmt.DebugUsize))
        __self_2
    core.fmt.Formatter.debug_struct_field3_finish f (toStr "Add") (toStr "id")
      __self_01 (toStr "clause") __self_11 (toStr "hints") __self_21
  | Step.Delete __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugVec core.fmt.DebugUsize))
        __self_0
    core.fmt.Formatter.debug_struct_field1_finish f (toStr "Delete") (toStr
      "ids") __self_01

/-- Trait implementation: [kernel::{impl core::fmt::Debug for kernel::Step}]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 26:16-26:21 -/
@[reducible]
def Step.Insts.CoreFmtDebug : core.fmt.Debug Step := {
  fmt := Step.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [kernel::{impl core::marker::StructuralPartialEq for kernel::Step}]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 26:23-26:32 -/
@[reducible]
def Step.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Step := {
}

/-- [kernel::{impl core::cmp::PartialEq<kernel::Step> for kernel::Step}::eq]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 26:23-26:32
    Visibility: public -/
def Step.Insts.CoreCmpPartialEqStep.eq
  (self : Step) (other : Step) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | Step.Add __self_0 __self_1 __self_2 =>
      match other with
      | Step.Add __arg1_0 __arg1_1 __arg1_2 =>
        let b ← lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
        if b
        then
          let b1 ←
            alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqI32 __self_1
              __arg1_1
          if b1
          then
            alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqUsize
              __self_2 __arg1_2
          else ok false
        else ok false
      | Step.Delete _ => fail panic
    | Step.Delete __self_0 =>
      match other with
      | Step.Add _ _ _ => fail panic
      | Step.Delete __arg1_0 =>
        alloc.vec.partial_eq.PartialEqVec.eq core.cmp.PartialEqUsize __self_0
          __arg1_0
  else ok false

/-- Trait implementation: [kernel::{impl core::cmp::PartialEq<kernel::Step> for kernel::Step}]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 26:23-26:32 -/
@[reducible]
def Step.Insts.CoreCmpPartialEqStep : core.cmp.PartialEq Step Step := {
  eq := Step.Insts.CoreCmpPartialEqStep.eq
}

/-- [kernel::{impl core::cmp::Eq for kernel::Step}::assert_fields_are_eq]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 26:34-26:36
    Visibility: public -/
def Step.Insts.CoreCmpEq.assert_fields_are_eq (self : Step) : Result Unit := do
  ok ()

/-- Trait implementation: [kernel::{impl core::cmp::Eq for kernel::Step}]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 26:34-26:36 -/
@[reducible]
def Step.Insts.CoreCmpEq : core.cmp.Eq Step := {
  partialEqInst := Step.Insts.CoreCmpPartialEqStep
  assert_fields_are_eq := Step.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [kernel::CoreError]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 49:0-101:1
    Visibility: public -/
@[discriminant isize]
inductive CoreError where
| InvalidCnfLiteral : Std.Usize → CoreError
| InvalidStepLiteral : Std.Usize → CoreError
| NonSequentialId : Std.Usize → Std.Usize → Std.Usize → CoreError
| UnknownId : Std.Usize → Std.Usize → CoreError
| DeletedId : Std.Usize → Std.Usize → CoreError
| HintNotUnit : Std.Usize → Std.Usize → CoreError
| HintsExhausted : Std.Usize → CoreError
| NoEmptyClause : CoreError

/-- [kernel::{impl core::clone::Clone for kernel::CoreError}::clone]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 48:9-48:14
    Visibility: public -/
def CoreError.Insts.CoreCloneClone.clone
  (self : CoreError) : Result CoreError := do
  match self with
  | CoreError.InvalidCnfLiteral __self_0 =>
    let i ← lift (core.clone.impls.CloneUsize.clone __self_0)
    ok (CoreError.InvalidCnfLiteral i)
  | CoreError.InvalidStepLiteral __self_0 =>
    let i ← lift (core.clone.impls.CloneUsize.clone __self_0)
    ok (CoreError.InvalidStepLiteral i)
  | CoreError.NonSequentialId __self_0 __self_1 __self_2 =>
    let i ← lift (core.clone.impls.CloneUsize.clone __self_0)
    let i1 ← lift (core.clone.impls.CloneUsize.clone __self_1)
    let i2 ← lift (core.clone.impls.CloneUsize.clone __self_2)
    ok (CoreError.NonSequentialId i i1 i2)
  | CoreError.UnknownId __self_0 __self_1 =>
    let i ← lift (core.clone.impls.CloneUsize.clone __self_0)
    let i1 ← lift (core.clone.impls.CloneUsize.clone __self_1)
    ok (CoreError.UnknownId i i1)
  | CoreError.DeletedId __self_0 __self_1 =>
    let i ← lift (core.clone.impls.CloneUsize.clone __self_0)
    let i1 ← lift (core.clone.impls.CloneUsize.clone __self_1)
    ok (CoreError.DeletedId i i1)
  | CoreError.HintNotUnit __self_0 __self_1 =>
    let i ← lift (core.clone.impls.CloneUsize.clone __self_0)
    let i1 ← lift (core.clone.impls.CloneUsize.clone __self_1)
    ok (CoreError.HintNotUnit i i1)
  | CoreError.HintsExhausted __self_0 =>
    let i ← lift (core.clone.impls.CloneUsize.clone __self_0)
    ok (CoreError.HintsExhausted i)
  | CoreError.NoEmptyClause => ok CoreError.NoEmptyClause

/-- Trait implementation: [kernel::{impl core::clone::Clone for kernel::CoreError}]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 48:9-48:14 -/
@[reducible]
def CoreError.Insts.CoreCloneClone : core.clone.Clone CoreError := {
  clone := CoreError.Insts.CoreCloneClone.clone
}

/-- [kernel::{impl core::fmt::Debug for kernel::CoreError}::fmt]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 48:16-48:21
    Visibility: public -/
def CoreError.Insts.CoreFmtDebug.fmt
  (self : CoreError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | CoreError.InvalidCnfLiteral __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) __self_0
    core.fmt.Formatter.debug_struct_field1_finish f (toStr "InvalidCnfLiteral")
      (toStr "clause_index") __self_01
  | CoreError.InvalidStepLiteral __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) __self_0
    core.fmt.Formatter.debug_struct_field1_finish f (toStr
      "InvalidStepLiteral") (toStr "step") __self_01
  | CoreError.NonSequentialId __self_0 __self_1 __self_2 =>
    let __self_01 := Dyn.mk _ core.fmt.DebugUsize __self_0
    let __self_11 := Dyn.mk _ core.fmt.DebugUsize __self_1
    let __self_21 :=
      Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) __self_2
    core.fmt.Formatter.debug_struct_field3_finish f (toStr "NonSequentialId")
      (toStr "step") __self_01 (toStr "expected") __self_11 (toStr "found")
      __self_21
  | CoreError.UnknownId __self_0 __self_1 =>
    let __self_01 := Dyn.mk _ core.fmt.DebugUsize __self_0
    let __self_11 :=
      Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) __self_1
    core.fmt.Formatter.debug_struct_field2_finish f (toStr "UnknownId") (toStr
      "step") __self_01 (toStr "id") __self_11
  | CoreError.DeletedId __self_0 __self_1 =>
    let __self_01 := Dyn.mk _ core.fmt.DebugUsize __self_0
    let __self_11 :=
      Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) __self_1
    core.fmt.Formatter.debug_struct_field2_finish f (toStr "DeletedId") (toStr
      "step") __self_01 (toStr "id") __self_11
  | CoreError.HintNotUnit __self_0 __self_1 =>
    let __self_01 := Dyn.mk _ core.fmt.DebugUsize __self_0
    let __self_11 :=
      Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) __self_1
    core.fmt.Formatter.debug_struct_field2_finish f (toStr "HintNotUnit")
      (toStr "step") __self_01 (toStr "hint") __self_11
  | CoreError.HintsExhausted __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) __self_0
    core.fmt.Formatter.debug_struct_field1_finish f (toStr "HintsExhausted")
      (toStr "step") __self_01
  | CoreError.NoEmptyClause =>
    core.fmt.Formatter.write_str f (toStr "NoEmptyClause")

/-- Trait implementation: [kernel::{impl core::fmt::Debug for kernel::CoreError}]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 48:16-48:21 -/
@[reducible]
def CoreError.Insts.CoreFmtDebug : core.fmt.Debug CoreError := {
  fmt := CoreError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [kernel::{impl core::marker::StructuralPartialEq for kernel::CoreError}]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 48:23-48:32 -/
@[reducible]
def CoreError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq CoreError := {
}

/-- [kernel::{impl core::cmp::PartialEq<kernel::CoreError> for kernel::CoreError}::eq]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 48:23-48:32
    Visibility: public -/
def CoreError.Insts.CoreCmpPartialEqCoreError.eq
  (self : CoreError) (other : CoreError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | CoreError.InvalidCnfLiteral __self_0 =>
      match other with
      | CoreError.InvalidCnfLiteral __arg1_0 =>
        lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
      | CoreError.InvalidStepLiteral _ => ok true
      | CoreError.NonSequentialId _ _ _ => ok true
      | CoreError.UnknownId _ _ => ok true
      | CoreError.DeletedId _ _ => ok true
      | CoreError.HintNotUnit _ _ => ok true
      | CoreError.HintsExhausted _ => ok true
      | CoreError.NoEmptyClause => ok true
    | CoreError.InvalidStepLiteral __self_0 =>
      match other with
      | CoreError.InvalidCnfLiteral _ => ok true
      | CoreError.InvalidStepLiteral __arg1_0 =>
        lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
      | CoreError.NonSequentialId _ _ _ => ok true
      | CoreError.UnknownId _ _ => ok true
      | CoreError.DeletedId _ _ => ok true
      | CoreError.HintNotUnit _ _ => ok true
      | CoreError.HintsExhausted _ => ok true
      | CoreError.NoEmptyClause => ok true
    | CoreError.NonSequentialId __self_0 __self_1 __self_2 =>
      match other with
      | CoreError.InvalidCnfLiteral _ => ok true
      | CoreError.InvalidStepLiteral _ => ok true
      | CoreError.NonSequentialId __arg1_0 __arg1_1 __arg1_2 =>
        let b ← lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
        if b
        then
          let b1 ← lift (core.cmp.impls.PartialEqUsize.eq __self_1 __arg1_1)
          if b1
          then lift (core.cmp.impls.PartialEqUsize.eq __self_2 __arg1_2)
          else ok false
        else ok false
      | CoreError.UnknownId _ _ => ok true
      | CoreError.DeletedId _ _ => ok true
      | CoreError.HintNotUnit _ _ => ok true
      | CoreError.HintsExhausted _ => ok true
      | CoreError.NoEmptyClause => ok true
    | CoreError.UnknownId __self_0 __self_1 =>
      match other with
      | CoreError.InvalidCnfLiteral _ => ok true
      | CoreError.InvalidStepLiteral _ => ok true
      | CoreError.NonSequentialId _ _ _ => ok true
      | CoreError.UnknownId __arg1_0 __arg1_1 =>
        let b ← lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
        if b
        then lift (core.cmp.impls.PartialEqUsize.eq __self_1 __arg1_1)
        else ok false
      | CoreError.DeletedId _ _ => ok true
      | CoreError.HintNotUnit _ _ => ok true
      | CoreError.HintsExhausted _ => ok true
      | CoreError.NoEmptyClause => ok true
    | CoreError.DeletedId __self_0 __self_1 =>
      match other with
      | CoreError.InvalidCnfLiteral _ => ok true
      | CoreError.InvalidStepLiteral _ => ok true
      | CoreError.NonSequentialId _ _ _ => ok true
      | CoreError.UnknownId _ _ => ok true
      | CoreError.DeletedId __arg1_0 __arg1_1 =>
        let b ← lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
        if b
        then lift (core.cmp.impls.PartialEqUsize.eq __self_1 __arg1_1)
        else ok false
      | CoreError.HintNotUnit _ _ => ok true
      | CoreError.HintsExhausted _ => ok true
      | CoreError.NoEmptyClause => ok true
    | CoreError.HintNotUnit __self_0 __self_1 =>
      match other with
      | CoreError.InvalidCnfLiteral _ => ok true
      | CoreError.InvalidStepLiteral _ => ok true
      | CoreError.NonSequentialId _ _ _ => ok true
      | CoreError.UnknownId _ _ => ok true
      | CoreError.DeletedId _ _ => ok true
      | CoreError.HintNotUnit __arg1_0 __arg1_1 =>
        let b ← lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
        if b
        then lift (core.cmp.impls.PartialEqUsize.eq __self_1 __arg1_1)
        else ok false
      | CoreError.HintsExhausted _ => ok true
      | CoreError.NoEmptyClause => ok true
    | CoreError.HintsExhausted __self_0 =>
      match other with
      | CoreError.InvalidCnfLiteral _ => ok true
      | CoreError.InvalidStepLiteral _ => ok true
      | CoreError.NonSequentialId _ _ _ => ok true
      | CoreError.UnknownId _ _ => ok true
      | CoreError.DeletedId _ _ => ok true
      | CoreError.HintNotUnit _ _ => ok true
      | CoreError.HintsExhausted __arg1_0 =>
        lift (core.cmp.impls.PartialEqUsize.eq __self_0 __arg1_0)
      | CoreError.NoEmptyClause => ok true
    | CoreError.NoEmptyClause => ok true
  else ok false

/-- Trait implementation: [kernel::{impl core::cmp::PartialEq<kernel::CoreError> for kernel::CoreError}]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 48:23-48:32 -/
@[reducible]
def CoreError.Insts.CoreCmpPartialEqCoreError : core.cmp.PartialEq CoreError
  CoreError := {
  eq := CoreError.Insts.CoreCmpPartialEqCoreError.eq
}

/-- [kernel::{impl core::cmp::Eq for kernel::CoreError}::assert_fields_are_eq]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 48:34-48:36
    Visibility: public -/
def CoreError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : CoreError) : Result Unit := do
  ok ()

/-- Trait implementation: [kernel::{impl core::cmp::Eq for kernel::CoreError}]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 48:34-48:36 -/
@[reducible]
def CoreError.Insts.CoreCmpEq : core.cmp.Eq CoreError := {
  partialEqInst := CoreError.Insts.CoreCmpPartialEqCoreError
  assert_fields_are_eq := CoreError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [kernel::lit_var]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 109:0-115:1 -/
def lit_var (lit : Std.I32) : Result Std.Usize := do
  if lit >= 0#i32
  then ok (IScalar.hcast .Usize lit)
  else let i ← -. lit
       ok (IScalar.hcast .Usize i)

/-- [kernel::Assignment]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 121:0-123:1 -/
structure Assignment where
  values : alloc.vec.Vec (Option Bool)

/-- [kernel::{kernel::Assignment}::new]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 126:4-128:5 -/
def Assignment.new : Result Assignment := do
  ok { values := (alloc.vec.Vec.new (Option Bool)) }

/-- [kernel::{kernel::Assignment}::value]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 133:4-148:5 -/
def Assignment.value
  (self : Assignment) (lit : Std.I32) : Result (Option Bool) := do
  let var ← lit_var lit
  let i := alloc.vec.Vec.len self.values
  if var >= i
  then ok none
  else
    let o ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Option Bool))
        self.values var
    match o with
    | none => ok none
    | some var_value => if lit > 0#i32
                        then ok o
                        else ok (some (¬ var_value))

/-- [kernel::{kernel::Assignment}::assign_true]: loop body 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 158:16-160:17 -/
@[rust_loop_body]
def Assignment.assign_true_loop.body
  (var : Std.Usize) (self : Assignment) :
  Result (ControlFlow Assignment (alloc.vec.Vec (Option Bool)))
  := do
  let i := alloc.vec.Vec.len self.values
  if i <= var
  then let v ← alloc.vec.Vec.push self.values none
       ok (cont { values := v })
  else ok (done self.values)

/-- [kernel::{kernel::Assignment}::assign_true]: loop 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 158:16-160:17 -/
@[rust_loop]
def Assignment.assign_true_loop
  (self : Assignment) (var : Std.Usize) :
  Result (alloc.vec.Vec (Option Bool))
  := do
  loop
    (fun self1 => Assignment.assign_true_loop.body var self1)
    self

/-- [kernel::{kernel::Assignment}::assign_true]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 152:4-165:5 -/
def Assignment.assign_true
  (self : Assignment) (lit : Std.I32) : Result (Bool × Assignment) := do
  let o ← Assignment.value self lit
  match o with
  | none =>
    let var ← lit_var lit
    let v ← Assignment.assign_true_loop self var
    let (_, index_mut_back) ←
      alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice (Option
        Bool)) v var
    let v1 := index_mut_back (some (lit > 0#i32))
    ok (false, { values := v1 })
  | some b => if b
              then ok (false, self)
              else ok (true, self)

/-- [kernel::get_live]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 169:0-177:1 -/
def get_live
  (clauses : Slice (Option (alloc.vec.Vec Std.I32))) (id : Std.Usize)
  (step : Std.Usize) :
  Result (core.result.Result (Slice Std.I32) CoreError)
  := do
  if id = 0#usize
  then ok (core.result.Result.Err (CoreError.UnknownId step id))
  else
    let i := Slice.len clauses
    if id > i
    then ok (core.result.Result.Err (CoreError.UnknownId step id))
    else
      let i1 ← id - 1#usize
      let o ← Slice.index_usize clauses i1
      match o with
      | none => ok (core.result.Result.Err (CoreError.DeletedId step id))
      | some clause =>
        let s := alloc.vec.Vec.deref clause
        ok (core.result.Result.Ok s)

/-- [kernel::assume_negation]: loop body 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 184:4-191:1 -/
@[rust_loop_body]
def assume_negation_loop.body
  (clause : Slice Std.I32) (assignment : Assignment) (i : Std.Usize) :
  Result (ControlFlow (Assignment × Std.Usize) (Bool × Assignment))
  := do
  let i1 := Slice.len clause
  if i < i1
  then
    let i2 ← Slice.index_usize clause i
    let i3 ← -. i2
    let (b, assignment1) ← Assignment.assign_true assignment i3
    if b
    then ok (done (true, assignment1))
    else let i4 ← i + 1#usize
         ok (cont (assignment1, i4))
  else ok (done (false, assignment))

/-- [kernel::assume_negation]: loop 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 184:4-191:1 -/
@[rust_loop]
def assume_negation_loop
  (assignment : Assignment) (clause : Slice Std.I32) (i : Std.Usize) :
  Result (Bool × Assignment)
  := do
  loop
    (fun (assignment1, i1) => assume_negation_loop.body clause assignment1 i1)
    (assignment, i)

/-- [kernel::assume_negation]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 182:0-191:1 -/
@[reducible]
def assume_negation
  (assignment : Assignment) (clause : Slice Std.I32) :
  Result (Bool × Assignment)
  := do
  assume_negation_loop assignment clause 0#usize

/-- [kernel::contains_lit]: loop body 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 197:4-204:1 -/
@[rust_loop_body]
def contains_lit_loop.body
  (lits : Slice Std.I32) (lit : Std.I32) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len lits
  if i < i1
  then
    let i2 ← Slice.index_usize lits i
    if i2 = lit
    then ok (done true)
    else let i3 ← i + 1#usize
         ok (cont i3)
  else ok (done false)

/-- [kernel::contains_lit]: loop 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 197:4-204:1 -/
@[rust_loop]
def contains_lit_loop
  (lits : Slice Std.I32) (lit : Std.I32) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => contains_lit_loop.body lits lit i1)
    i

/-- [kernel::contains_lit]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 195:0-204:1 -/
@[reducible]
def contains_lit (lits : Slice Std.I32) (lit : Std.I32) : Result Bool := do
  contains_lit_loop lits lit 0#usize

/-- [kernel::HintClass]
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 207:0-216:1 -/
@[discriminant isize]
inductive HintClass where
| Satisfied : HintClass
| Falsified : HintClass
| Unit : Std.I32 → HintClass
| Multi : HintClass

/-- [kernel::classify_hint]: loop body 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 223:4-241:1 -/
@[rust_loop_body]
def classify_hint_loop.body
  (assignment : Assignment) (clause : Slice Std.I32)
  (unassigned : alloc.vec.Vec Std.I32) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.I32) × Std.Usize) HintClass)
  := do
  let i1 := Slice.len clause
  if i < i1
  then
    let lit ← Slice.index_usize clause i
    let o ← Assignment.value assignment lit
    match o with
    | none =>
      let s := alloc.vec.Vec.deref unassigned
      let b ← contains_lit s lit
      let unassigned1 ←
        if b
        then ok unassigned
        else alloc.vec.Vec.push unassigned lit
      let i2 ← i + 1#usize
      ok (cont (unassigned1, i2))
    | some b =>
      if b
      then ok (done HintClass.Satisfied)
      else let i2 ← i + 1#usize
           ok (cont (unassigned, i2))
  else
    let i2 := alloc.vec.Vec.len unassigned
    match i2.val with
    | 0 => ok (done HintClass.Falsified)
    | 1 =>
      let i3 ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.I32)
          unassigned 0#usize
      ok (done (HintClass.Unit i3))
    | _ => ok (done HintClass.Multi)

/-- [kernel::classify_hint]: loop 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 223:4-241:1 -/
@[rust_loop]
def classify_hint_loop
  (assignment : Assignment) (clause : Slice Std.I32)
  (unassigned : alloc.vec.Vec Std.I32) (i : Std.Usize) :
  Result HintClass
  := do
  loop
    (fun (unassigned1, i1) => classify_hint_loop.body assignment clause
      unassigned1 i1)
    (unassigned, i)

/-- [kernel::classify_hint]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 220:0-241:1 -/
@[reducible]
def classify_hint
  (assignment : Assignment) (clause : Slice Std.I32) : Result HintClass := do
  classify_hint_loop assignment clause (alloc.vec.Vec.new Std.I32) 0#usize

/-- [kernel::check_rup]: loop body 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 1:0-285:5 -/
@[rust_loop_body]
def check_rup_loop.body
  (clauses : Slice (Option (alloc.vec.Vec Std.I32))) (hints : Slice Std.Usize)
  (step : Std.Usize) (assignment : Assignment)
  (outcome : Option (core.result.Result Unit CoreError)) (i : Std.Usize) :
  Result (ControlFlow (Assignment × (Option (core.result.Result Unit
    CoreError)) × Std.Usize) (Option (core.result.Result Unit CoreError)))
  := do
  let b := core.option.Option.is_none outcome
  if b
  then
    let i1 := Slice.len hints
    if i < i1
    then
      let hint_id ← Slice.index_usize hints i
      let r ← get_live clauses hint_id step
      let (assignment1, outcome1) ←
        match r with
        | core.result.Result.Ok clause =>
          do
          let hc ← classify_hint assignment clause
          match hc with
          | HintClass.Satisfied =>
            ok (assignment, some (core.result.Result.Err (CoreError.HintNotUnit
              step hint_id)))
          | HintClass.Falsified =>
            ok (assignment, some (core.result.Result.Ok ()))
          | HintClass.Unit unit =>
            let (conflict, assignment2) ←
              Assignment.assign_true assignment unit
            massert (¬ conflict)
            ok (assignment2, outcome)
          | HintClass.Multi =>
            ok (assignment, some (core.result.Result.Err (CoreError.HintNotUnit
              step hint_id)))
        | core.result.Result.Err e =>
          ok (assignment, some (core.result.Result.Err e))
      let i2 ← i + 1#usize
      ok (cont (assignment1, outcome1, i2))
    else ok (done outcome)
  else ok (done outcome)

/-- [kernel::check_rup]: loop 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 1:0-285:5 -/
@[rust_loop]
def check_rup_loop
  (clauses : Slice (Option (alloc.vec.Vec Std.I32))) (hints : Slice Std.Usize)
  (step : Std.Usize) (assignment : Assignment)
  (outcome : Option (core.result.Result Unit CoreError)) (i : Std.Usize) :
  Result (Option (core.result.Result Unit CoreError))
  := do
  loop
    (fun (assignment1, outcome1, i1) => check_rup_loop.body clauses hints step
      assignment1 outcome1 i1)
    (assignment, outcome, i)

/-- [kernel::check_rup]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 249:0-291:1 -/
def check_rup
  (clauses : Slice (Option (alloc.vec.Vec Std.I32)))
  (new_clause : Slice Std.I32) (hints : Slice Std.Usize) (step : Std.Usize) :
  Result (core.result.Result Unit CoreError)
  := do
  let assignment ← Assignment.new
  let (b, assignment1) ← assume_negation assignment new_clause
  if b
  then ok (core.result.Result.Ok ())
  else
    let outcome ← check_rup_loop clauses hints step assignment1 none 0#usize
    match outcome with
    | none => ok (core.result.Result.Err (CoreError.HintsExhausted step))
    | some result => ok result

/-- [kernel::clause_has_invalid_literal]: loop body 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 297:4-304:1 -/
@[rust_loop_body]
def clause_has_invalid_literal_loop.body
  (clause : Slice Std.I32) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len clause
  if i < i1
  then
    let i2 ← Slice.index_usize clause i
    if i2 = 0#i32
    then ok (done true)
    else
      if i2 = core.num.I32.MIN
      then ok (done true)
      else let i3 ← i + 1#usize
           ok (cont i3)
  else ok (done false)

/-- [kernel::clause_has_invalid_literal]: loop 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 297:4-304:1 -/
@[rust_loop]
def clause_has_invalid_literal_loop
  (clause : Slice Std.I32) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => clause_has_invalid_literal_loop.body clause i1)
    i

/-- [kernel::clause_has_invalid_literal]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 295:0-304:1 -/
@[reducible]
def clause_has_invalid_literal (clause : Slice Std.I32) : Result Bool := do
  clause_has_invalid_literal_loop clause 0#usize

/-- [kernel::load_cnf]: loop body 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 311:4-319:1 -/
@[rust_loop_body]
def load_cnf_loop.body
  (cnf : Slice (alloc.vec.Vec Std.I32))
  (clauses : alloc.vec.Vec (Option (alloc.vec.Vec Std.I32))) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec (Option (alloc.vec.Vec Std.I32))) ×
    Std.Usize) (core.result.Result (alloc.vec.Vec (Option (alloc.vec.Vec
    Std.I32))) CoreError))
  := do
  let i1 := Slice.len cnf
  if i < i1
  then
    let v ← Slice.index_usize cnf i
    let s := alloc.vec.Vec.deref v
    let b ← clause_has_invalid_literal s
    if b
    then ok (done (core.result.Result.Err (CoreError.InvalidCnfLiteral i)))
    else
      let v1 ← alloc.vec.CloneVec.clone core.clone.CloneI32 v
      let clauses1 ← alloc.vec.Vec.push clauses (some v1)
      let i2 ← i + 1#usize
      ok (cont (clauses1, i2))
  else ok (done (core.result.Result.Ok clauses))

/-- [kernel::load_cnf]: loop 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 311:4-319:1 -/
@[rust_loop]
def load_cnf_loop
  (cnf : Slice (alloc.vec.Vec Std.I32))
  (clauses : alloc.vec.Vec (Option (alloc.vec.Vec Std.I32))) (i : Std.Usize) :
  Result (core.result.Result (alloc.vec.Vec (Option (alloc.vec.Vec Std.I32)))
    CoreError)
  := do
  loop
    (fun (clauses1, i1) => load_cnf_loop.body cnf clauses1 i1)
    (clauses, i)

/-- [kernel::load_cnf]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 308:0-319:1 -/
@[reducible]
def load_cnf
  (cnf : Slice (alloc.vec.Vec Std.I32)) :
  Result (core.result.Result (alloc.vec.Vec (Option (alloc.vec.Vec Std.I32)))
    CoreError)
  := do
  load_cnf_loop cnf (alloc.vec.Vec.new (Option (alloc.vec.Vec Std.I32)))
    0#usize

/-- [kernel::clear_slot]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 325:0-327:1 -/
def clear_slot
  (slot : Option (alloc.vec.Vec Std.I32)) :
  Result (Option (alloc.vec.Vec Std.I32))
  := do
  ok none

/-- [kernel::apply_delete]: loop body 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 337:4-344:1 -/
@[rust_loop_body]
def apply_delete_loop.body
  (ids : Slice Std.Usize) (step : Std.Usize)
  (clauses : Slice (Option (alloc.vec.Vec Std.I32))) (i : Std.Usize) :
  Result (ControlFlow ((Slice (Option (alloc.vec.Vec Std.I32))) × Std.Usize)
    ((core.result.Result Unit CoreError) × (Slice (Option (alloc.vec.Vec
    Std.I32)))))
  := do
  let i1 := Slice.len ids
  if i < i1
  then
    let id ← Slice.index_usize ids i
    let r ← get_live clauses id step
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue _ =>
      let i2 ← id - 1#usize
      let (o, index_mut_back) ← Slice.index_mut_usize clauses i2
      let o1 ← clear_slot o
      let i3 ← i + 1#usize
      let s := index_mut_back o1
      ok (cont (s, i3))
    | core.ops.control_flow.ControlFlow.Break residual =>
      let r1 ←
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          Unit (core.convert.FromSame CoreError) residual
      ok (done (r1, clauses))
  else ok (done (core.result.Result.Ok (), clauses))

/-- [kernel::apply_delete]: loop 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 337:4-344:1 -/
@[rust_loop]
def apply_delete_loop
  (clauses : Slice (Option (alloc.vec.Vec Std.I32))) (ids : Slice Std.Usize)
  (step : Std.Usize) (i : Std.Usize) :
  Result ((core.result.Result Unit CoreError) × (Slice (Option (alloc.vec.Vec
    Std.I32))))
  := do
  loop
    (fun (clauses1, i1) => apply_delete_loop.body ids step clauses1 i1)
    (clauses, i)

/-- [kernel::apply_delete]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 331:0-344:1 -/
@[reducible]
def apply_delete
  (clauses : Slice (Option (alloc.vec.Vec Std.I32))) (ids : Slice Std.Usize)
  (step : Std.Usize) :
  Result ((core.result.Result Unit CoreError) × (Slice (Option (alloc.vec.Vec
    Std.I32))))
  := do
  apply_delete_loop clauses ids step 0#usize

/-- [kernel::apply_add]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 348:0-378:1 -/
def apply_add
  (clauses : alloc.vec.Vec (Option (alloc.vec.Vec Std.I32))) (id : Std.Usize)
  (clause : Slice Std.I32) (hints : Slice Std.Usize) (step : Std.Usize) :
  Result ((core.result.Result Bool CoreError) × (alloc.vec.Vec (Option
    (alloc.vec.Vec Std.I32))))
  := do
  let b ← clause_has_invalid_literal clause
  if b
  then ok (core.result.Result.Err (CoreError.InvalidStepLiteral step), clauses)
  else
    let i := alloc.vec.Vec.len clauses
    let expected ← i + 1#usize
    if id != expected
    then
      ok (core.result.Result.Err (CoreError.NonSequentialId step expected id),
        clauses)
    else
      let s := alloc.vec.Vec.deref clauses
      let r ← check_rup s clause hints step
      let cf ← core.result.Result.Insts.CoreOpsTry.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue _ =>
        let i1 := Slice.len clause
        let v ← alloc.slice.Slice.to_vec core.clone.CloneI32 clause
        let clauses1 ← alloc.vec.Vec.push clauses (some v)
        ok (core.result.Result.Ok (i1 = 0#usize), clauses1)
      | core.ops.control_flow.ControlFlow.Break residual =>
        let r1 ←
          core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
            Bool (core.convert.FromSame CoreError) residual
        ok (r1, clauses)

/-- [kernel::check_steps]: loop body 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 1:0-415:5
    Visibility: public -/
@[rust_loop_body]
def check_steps_loop.body
  (steps : Slice Step)
  (clauses : alloc.vec.Vec (Option (alloc.vec.Vec Std.I32)))
  (outcome : Option (core.result.Result Unit CoreError))
  (step_index : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec (Option (alloc.vec.Vec Std.I32))) ×
    (Option (core.result.Result Unit CoreError)) × Std.Usize) (Option
    (core.result.Result Unit CoreError)))
  := do
  let b := core.option.Option.is_none outcome
  if b
  then
    let i := Slice.len steps
    if step_index < i
    then
      let s ← Slice.index_usize steps step_index
      let current ← Step.Insts.CoreCloneClone.clone s
      let (clauses1, outcome1) ←
        match current with
        | Step.Add id clause hints =>
          do
          let s1 := alloc.vec.Vec.deref clause
          let s2 := alloc.vec.Vec.deref hints
          let (r, clauses2) ← apply_add clauses id s1 s2 step_index
          match r with
          | core.result.Result.Ok b1 =>
            let o ←
              if b1
              then ok (some (core.result.Result.Ok ()))
              else ok outcome
            ok (clauses2, o)
          | core.result.Result.Err e =>
            ok (clauses2, some (core.result.Result.Err e))
        | Step.Delete ids =>
          do
          let (s1, deref_mut_back) ← lift (alloc.vec.Vec.deref_mut clauses)
          let s2 := alloc.vec.Vec.deref ids
          let (r, s3) ← apply_delete s1 s2 step_index
          match r with
          | core.result.Result.Ok _ =>
            let clauses2 := deref_mut_back s3
            ok (clauses2, outcome)
          | core.result.Result.Err _ =>
            let clauses2 := deref_mut_back s3
            ok (clauses2, some r)
      let step_index1 ← step_index + 1#usize
      ok (cont (clauses1, outcome1, step_index1))
    else ok (done outcome)
  else ok (done outcome)

/-- [kernel::check_steps]: loop 0:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 1:0-415:5
    Visibility: public -/
@[rust_loop]
def check_steps_loop
  (steps : Slice Step)
  (clauses : alloc.vec.Vec (Option (alloc.vec.Vec Std.I32)))
  (outcome : Option (core.result.Result Unit CoreError))
  (step_index : Std.Usize) :
  Result (Option (core.result.Result Unit CoreError))
  := do
  loop
    (fun (clauses1, outcome1, step_index1) => check_steps_loop.body steps
      clauses1 outcome1 step_index1)
    (clauses, outcome, step_index)

/-- [kernel::check_steps]:
    Source: 'crates/ordeal-lrat/src/kernel.rs', lines 386:0-421:1
    Visibility: public -/
def check_steps
  (cnf : Slice (alloc.vec.Vec Std.I32)) (steps : Slice Step) :
  Result (core.result.Result Unit CoreError)
  := do
  let r ← load_cnf cnf
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let outcome ← check_steps_loop steps val none 0#usize
    match outcome with
    | none => ok (core.result.Result.Err CoreError.NoEmptyClause)
    | some result => ok result
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Unit (core.convert.FromSame CoreError) residual

end kernel
